<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Anicet Ebou">
<title>9&nbsp; Mixed-Effects Models: Beyond Classical ANOVA – Modern Analysis of Variance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04c-when-assumptions-fail.html" rel="next">
<link href="./04a-anova-as-lm.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-modern-framework.html">The Modern Framework</a></li><li class="breadcrumb-item"><a href="./04b-mixed-effects.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Mixed-Effects Models: Beyond Classical ANOVA</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Modern Analysis of Variance</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Ebedthan/maov/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./02-foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02a-what-is-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What is ANOVA, Really ?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02b-assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Assumptions</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./03-classical-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Classical ANOVA Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03a-one-way.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">One-Way ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03b-multiple-comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Multiple Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03c-two-way.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Two-Way ANOVA and Factorial Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03d-repeated-measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Repeated Measures ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03e-split-plot-nested.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Split-Plot and Nested Designs</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./04-modern-framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Modern Framework</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04a-anova-as-lm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA as a Linear Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04b-mixed-effects.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Mixed-Effects Models: Beyond Classical ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04c-when-assumptions-fail.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">When Assumptions Fail, What to Do ?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04d-glmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Generalised Linear Mixed Models</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./05-good-practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Good Practice and Reproductibility</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05a-experimental-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Experimental Design Principles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05b-reporting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Reporting ANOVA Results</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05c-reproducible-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Reproducible Analysis with R</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-a-math.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">The Maths of the Book</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-b-packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Datasets and R Packages</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-c-decision-tree.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Decision Trees for Model Selection</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#when-random-effects-are-necessary" id="toc-when-random-effects-are-necessary" class="nav-link active" data-scroll-target="#when-random-effects-are-necessary"><span class="header-section-number">9.1</span> When Random Effects Are Necessary</a>
  <ul class="collapse">
<li><a href="#the-three-situations-that-demand-random-effects" id="toc-the-three-situations-that-demand-random-effects" class="nav-link" data-scroll-target="#the-three-situations-that-demand-random-effects"><span class="header-section-number">9.1.1</span> The Three Situations That Demand Random Effects</a></li>
  <li><a href="#recognising-random-effects-in-practice" id="toc-recognising-random-effects-in-practice" class="nav-link" data-scroll-target="#recognising-random-effects-in-practice"><span class="header-section-number">9.1.2</span> Recognising Random Effects in Practice</a></li>
  </ul>
</li>
  <li>
<a href="#random-intercepts-and-random-slopes" id="toc-random-intercepts-and-random-slopes" class="nav-link" data-scroll-target="#random-intercepts-and-random-slopes"><span class="header-section-number">9.2</span> Random Intercepts and Random Slopes</a>
  <ul class="collapse">
<li><a href="#the-random-intercept-model" id="toc-the-random-intercept-model" class="nav-link" data-scroll-target="#the-random-intercept-model"><span class="header-section-number">9.2.1</span> The Random Intercept Model</a></li>
  <li><a href="#the-random-slope-model" id="toc-the-random-slope-model" class="nav-link" data-scroll-target="#the-random-slope-model"><span class="header-section-number">9.2.2</span> The Random Slope Model</a></li>
  <li><a href="#visualising-random-intercepts-and-slopes" id="toc-visualising-random-intercepts-and-slopes" class="nav-link" data-scroll-target="#visualising-random-intercepts-and-slopes"><span class="header-section-number">9.2.3</span> Visualising Random Intercepts and Slopes</a></li>
  <li><a href="#choosing-between-random-intercepts-and-random-slopes" id="toc-choosing-between-random-intercepts-and-random-slopes" class="nav-link" data-scroll-target="#choosing-between-random-intercepts-and-random-slopes"><span class="header-section-number">9.2.4</span> Choosing Between Random Intercepts and Random Slopes</a></li>
  </ul>
</li>
  <li>
<a href="#lme4-and-nlme-a-practical-guide" id="toc-lme4-and-nlme-a-practical-guide" class="nav-link" data-scroll-target="#lme4-and-nlme-a-practical-guide"><span class="header-section-number">9.3</span> <code>lme4</code> and <code>nlme</code>: A Practical Guide</a>
  <ul class="collapse">
<li><a href="#two-packages-different-strengths" id="toc-two-packages-different-strengths" class="nav-link" data-scroll-target="#two-packages-different-strengths"><span class="header-section-number">9.3.1</span> Two Packages, Different Strengths</a></li>
  <li><a href="#the-lme4-formula-syntax" id="toc-the-lme4-formula-syntax" class="nav-link" data-scroll-target="#the-lme4-formula-syntax"><span class="header-section-number">9.3.2</span> The <code>lme4</code> Formula Syntax</a></li>
  <li><a href="#sec-rim" id="toc-sec-rim" class="nav-link" data-scroll-target="#sec-rim"><span class="header-section-number">9.3.3</span> Fitting and Interpreting a Random Intercept Model</a></li>
  <li><a href="#sec-reml-ml" id="toc-sec-reml-ml" class="nav-link" data-scroll-target="#sec-reml-ml"><span class="header-section-number">9.3.4</span> REML vs ML Estimation</a></li>
  <li><a href="#extracting-random-effects" id="toc-extracting-random-effects" class="nav-link" data-scroll-target="#extracting-random-effects"><span class="header-section-number">9.3.5</span> Extracting Random Effects</a></li>
  </ul>
</li>
  <li>
<a href="#degrees-of-freedom-and-p-values-the-kenward-roger-and-satterthwaite-debate" id="toc-degrees-of-freedom-and-p-values-the-kenward-roger-and-satterthwaite-debate" class="nav-link" data-scroll-target="#degrees-of-freedom-and-p-values-the-kenward-roger-and-satterthwaite-debate"><span class="header-section-number">9.4</span> Degrees of Freedom and P-Values: The Kenward-Roger and Satterthwaite Debate</a>
  <ul class="collapse">
<li><a href="#why-lme4-does-not-give-p-values" id="toc-why-lme4-does-not-give-p-values" class="nav-link" data-scroll-target="#why-lme4-does-not-give-p-values"><span class="header-section-number">9.4.1</span> Why <code>lme4</code> Does Not Give P-Values</a></li>
  <li><a href="#satterthwaites-approximation" id="toc-satterthwaites-approximation" class="nav-link" data-scroll-target="#satterthwaites-approximation"><span class="header-section-number">9.4.2</span> Satterthwaite’s Approximation</a></li>
  <li><a href="#kenward-roger-approximation" id="toc-kenward-roger-approximation" class="nav-link" data-scroll-target="#kenward-roger-approximation"><span class="header-section-number">9.4.3</span> Kenward-Roger Approximation</a></li>
  <li><a href="#which-method-to-use" id="toc-which-method-to-use" class="nav-link" data-scroll-target="#which-method-to-use"><span class="header-section-number">9.4.4</span> Which Method to Use?</a></li>
  </ul>
</li>
  <li>
<a href="#example-patient-nested-in-hospital-nested-in-region" id="toc-example-patient-nested-in-hospital-nested-in-region" class="nav-link" data-scroll-target="#example-patient-nested-in-hospital-nested-in-region"><span class="header-section-number">9.5</span> Example: Patient Nested in Hospital Nested in Region</a>
  <ul class="collapse">
<li><a href="#the-study" id="toc-the-study" class="nav-link" data-scroll-target="#the-study"><span class="header-section-number">9.5.1</span> The Study</a></li>
  <li><a href="#visualising-the-nested-structure" id="toc-visualising-the-nested-structure" class="nav-link" data-scroll-target="#visualising-the-nested-structure"><span class="header-section-number">9.5.2</span> Visualising the Nested Structure</a></li>
  <li><a href="#fitting-the-three-level-nested-model" id="toc-fitting-the-three-level-nested-model" class="nav-link" data-scroll-target="#fitting-the-three-level-nested-model"><span class="header-section-number">9.5.3</span> Fitting the Three-Level Nested Model</a></li>
  <li><a href="#diagnosing-the-model" id="toc-diagnosing-the-model" class="nav-link" data-scroll-target="#diagnosing-the-model"><span class="header-section-number">9.5.4</span> Diagnosing the Model</a></li>
  <li><a href="#testing-the-fixed-effect" id="toc-testing-the-fixed-effect" class="nav-link" data-scroll-target="#testing-the-fixed-effect"><span class="header-section-number">9.5.5</span> Testing the Fixed Effect</a></li>
  <li><a href="#comparing-nested-models" id="toc-comparing-nested-models" class="nav-link" data-scroll-target="#comparing-nested-models"><span class="header-section-number">9.5.6</span> Comparing Nested Models</a></li>
  <li><a href="#reporting-the-result" id="toc-reporting-the-result" class="nav-link" data-scroll-target="#reporting-the-result"><span class="header-section-number">9.5.7</span> Reporting the Result</a></li>
  </ul>
</li>
  <li>
<a href="#sec-repeat-mixed" id="toc-sec-repeat-mixed" class="nav-link" data-scroll-target="#sec-repeat-mixed"><span class="header-section-number">9.6</span> Repeated Measures as a Mixed Model</a>
  <ul class="collapse">
<li><a href="#the-connection-to-chapter-6" id="toc-the-connection-to-chapter-6" class="nav-link" data-scroll-target="#the-connection-to-chapter-6"><span class="header-section-number">9.6.1</span> The Connection to Chapter 6</a></li>
  <li><a href="#refitting-the-clinical-example" id="toc-refitting-the-clinical-example" class="nav-link" data-scroll-target="#refitting-the-clinical-example"><span class="header-section-number">9.6.2</span> Refitting the Clinical Example</a></li>
  <li><a href="#where-the-two-approaches-diverge" id="toc-where-the-two-approaches-diverge" class="nav-link" data-scroll-target="#where-the-two-approaches-diverge"><span class="header-section-number">9.6.3</span> Where the Two Approaches Diverge</a></li>
  <li><a href="#a-practical-recommendation" id="toc-a-practical-recommendation" class="nav-link" data-scroll-target="#a-practical-recommendation"><span class="header-section-number">9.6.4</span> A Practical Recommendation</a></li>
  </ul>
</li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/Ebedthan/maov/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li><li><a href="https://github.com/Ebedthan/maov/edit/main/04b-mixed-effects.qmd" class="toc-action"><i class="bi empty"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-modern-framework.html">The Modern Framework</a></li><li class="breadcrumb-item"><a href="./04b-mixed-effects.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Mixed-Effects Models: Beyond Classical ANOVA</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-chap9" class="quarto-section-identifier"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Mixed-Effects Models: Beyond Classical ANOVA</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>The repeated measures and split-plot designs of Chapters <a href="#sec-chap6" class="quarto-xref"><span class="quarto-unresolved-ref ref-noprefix">sec-chap6</span></a> and <a href="#sec-chap7" class="quarto-xref"><span class="quarto-unresolved-ref ref-noprefix">sec-chap7</span></a> introduced the idea that not all sources of variation in biological data are equal. Some variation is systematic and of direct scientific interest like the effect of a treatment, a drug, a genotype. Some variation is structural and must be accounted for but is not itself the focus like the fact that patients differ from one another, that plots within the same field are more similar than plots in different fields, that repeated measurements on the same individual are correlated.</p>
<p>Classical ANOVA handles these structural sources of variation through explicit error terms like the <code>Error()</code> specification in <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code>. This works well for simple, balanced designs with one or two levels of nesting. It becomes unwieldy, and eventually impossible, when the hierarchical structure is more complex, when data are missing, when the design is unbalanced, or when you want to make inferences that generalise beyond the specific levels of a grouping factor that happen to appear in your data.</p>
<p>Mixed-effects models are the modern solution to all of these problems. They extend the linear model framework by including both <strong>fixed effects</strong>, the systematic, estimable treatment effects that classical ANOVA tests, and <strong>random effects</strong>, the structural variation attributable to grouping factors whose levels are a random sample from a larger population. The result is a framework that is simultaneously more flexible, more honest about the structure of biological data, and more directly connected to the scientific questions being asked.</p>
<section id="when-random-effects-are-necessary" class="level2" data-number="9.1"><h2 data-number="9.1" class="anchored" data-anchor-id="when-random-effects-are-necessary">
<span class="header-section-number">9.1</span> When Random Effects Are Necessary</h2>
<section id="the-three-situations-that-demand-random-effects" class="level3" data-number="9.1.1"><h3 data-number="9.1.1" class="anchored" data-anchor-id="the-three-situations-that-demand-random-effects">
<span class="header-section-number">9.1.1</span> The Three Situations That Demand Random Effects</h3>
<p>Random effects are not merely a statistical convenience, they are the correct model for specific, recognisable data structures. Three situations arise repeatedly in biological research where failing to include random effects leads directly to incorrect inference.</p>
<p><strong>Situation 1: Clustered observations.</strong> Measurements taken on units that belong to the same higher-level group will be more similar to each other than measurements from different groups, regardless of any treatment. Patients recruited from the same hospital share clinical practices, patient population, and staffing. Plants in the same greenhouse bench share light and temperature. Students in the same classroom share a teacher. This within-cluster similarity, quantified by the intraclass correlation coefficient introduced in Section 2.6, means the observations are not independent, and the effective sample size is smaller than the raw count of observations suggests. A random effect for the cluster absorbs this similarity and produces correct standard errors.</p>
<p><strong>Situation 2: Repeated measurements.</strong> When the same individual is measured multiple times at different time points, under different conditions, or in different locations, the repeated measurements on the same individual are correlated. Chapter <a href="#sec-chap6" class="quarto-xref"><span class="quarto-unresolved-ref ref-noprefix">sec-chap6</span></a> handled this with repeated measures ANOVA. Mixed models handle it more flexibly: the individual is modelled as a random effect, and the covariance structure of the repeated measurements can be specified explicitly. Mixed models also handle missing data gracefully, which repeated measures ANOVA cannot.</p>
<p><strong>Situation 3: Generalising beyond the observed levels.</strong> If the levels of a grouping factor in your study are a random sample from a larger population like hospitals drawn from a healthcare system, farms drawn from a region or batches drawn from a production run and you want your conclusions to generalise to that larger population, the grouping factor must be treated as random. A fixed effect estimates the mean of each specific level observed; a random effect estimates the distribution of levels in the population.</p>
</section><section id="recognising-random-effects-in-practice" class="level3" data-number="9.1.2"><h3 data-number="9.1.2" class="anchored" data-anchor-id="recognising-random-effects-in-practice">
<span class="header-section-number">9.1.2</span> Recognising Random Effects in Practice</h3>
<p>The practical question is: for each grouping factor in your data, are the levels the specific entities of interest, or a sample representing a broader population?</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 51%">
<col style="width: 24%">
</colgroup>
<thead><tr class="header">
<th>Factor</th>
<th>Fixed or random?</th>
<th>Reason</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Fertiliser type (control, N, P)</td>
<td>Fixed</td>
<td>Specific treatments of interest</td>
</tr>
<tr class="even">
<td>Hospital (12 of 200 in region)</td>
<td>Random</td>
<td>Sample from a population</td>
</tr>
<tr class="odd">
<td>Patient (20 recruited volunteers)</td>
<td>Random</td>
<td>Sample from a population</td>
</tr>
<tr class="even">
<td>Genotype (4 specific varieties)</td>
<td>Fixed</td>
<td>Specific varieties of interest</td>
</tr>
<tr class="odd">
<td>Field (6 randomly selected)</td>
<td>Random</td>
<td>Sample from a population</td>
</tr>
<tr class="even">
<td>Time point (weeks 0, 4, 8, 12)</td>
<td>Fixed</td>
<td>Specific times of interest</td>
</tr>
</tbody>
</table>
<p>When in doubt, ask: <strong>would you want your conclusions to apply to levels of this factor that were not in your study?</strong> If yes, the factor is random.</p>
</section></section><section id="random-intercepts-and-random-slopes" class="level2" data-number="9.2"><h2 data-number="9.2" class="anchored" data-anchor-id="random-intercepts-and-random-slopes">
<span class="header-section-number">9.2</span> Random Intercepts and Random Slopes</h2>
<section id="the-random-intercept-model" class="level3" data-number="9.2.1"><h3 data-number="9.2.1" class="anchored" data-anchor-id="the-random-intercept-model">
<span class="header-section-number">9.2.1</span> The Random Intercept Model</h3>
<p>The simplest mixed model adds a random intercept for each level of a grouping factor. For a study with patients nested within hospitals, the random intercept model is:</p>
<p><span class="math display">\[y_{ij} = \underbrace{\beta_0 + \beta_1 x_{ij}}_{\text{fixed effects}} +
           \underbrace{b_j}_{\text{random intercept}} +
           \underbrace{\varepsilon_{ij}}_{\text{residual}}\]</span></p>
<p>where <span class="math inline">\(y_{ij}\)</span> is the response for patient <span class="math inline">\(i\)</span> in hospital <span class="math inline">\(j\)</span>, <span class="math inline">\(x_{ij}\)</span> is a predictor (treatment, time, covariate), <span class="math inline">\(b_j\)</span> is the random intercept for hospital <span class="math inline">\(j\)</span>, and <span class="math inline">\(\varepsilon_{ij}\)</span> is the residual. The random intercepts are assumed normally distributed:</p>
<p><span class="math display">\[b_j \sim \mathcal{N}(0, \sigma^2_b)\]</span></p>
<p>The random intercept <span class="math inline">\(b_j\)</span> captures the fact that some hospitals have systematically higher or lower outcomes than average, for reasons unrelated to the treatment being studied. By modelling this explicitly, the fixed effect <span class="math inline">\(\beta_1\)</span> is estimated after accounting for hospital-level differences which is a more honest and more precise estimate than one that ignores the clustering.</p>
</section><section id="the-random-slope-model" class="level3" data-number="9.2.2"><h3 data-number="9.2.2" class="anchored" data-anchor-id="the-random-slope-model">
<span class="header-section-number">9.2.2</span> The Random Slope Model</h3>
<p>A <strong>random intercept</strong> allows each group to have a different baseline level of the response. A <strong>random slope</strong> allows each group to have a different relationship between a predictor and the response:</p>
<p><span class="math display">\[y_{ij} = (\beta_0 + b_{0j}) + (\beta_1 + b_{1j}) x_{ij} +
           \varepsilon_{ij}\]</span></p>
<p>where <span class="math inline">\(b_{0j}\)</span> is the random intercept for group <span class="math inline">\(j\)</span> and <span class="math inline">\(b_{1j}\)</span> is the random slope i.e.&nbsp;the deviation of group <span class="math inline">\(j\)</span>’s slope from the average slope <span class="math inline">\(\beta_1\)</span>. Together they form a bivariate normal distribution:</p>
<p><span class="math display">\[\begin{pmatrix} b_{0j} \\ b_{1j} \end{pmatrix} \sim
  \mathcal{N}\left(
    \begin{pmatrix} 0 \\ 0 \end{pmatrix},
    \begin{pmatrix} \sigma^2_0 &amp; \sigma_{01} \\
                    \sigma_{01} &amp; \sigma^2_1 \end{pmatrix}
  \right)\]</span></p>
<p>The covariance <span class="math inline">\(\sigma_{01}\)</span> captures whether groups that start higher also tend to change more (or less) rapidly, an estimate that is a biologically important quantity in longitudinal studies.</p>
</section><section id="visualising-random-intercepts-and-slopes" class="level3" data-number="9.2.3"><h3 data-number="9.2.3" class="anchored" data-anchor-id="visualising-random-intercepts-and-slopes">
<span class="header-section-number">9.2.3</span> Visualising Random Intercepts and Slopes</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">42</span><span class="op">)</span></span>
<span></span>
<span><span class="va">n_groups</span> <span class="op">&lt;-</span> <span class="fl">8</span></span>
<span><span class="va">n_obs</span> <span class="op">&lt;-</span> <span class="fl">10</span></span>
<span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span>, length.out <span class="op">=</span> <span class="va">n_obs</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Random intercept model</span></span>
<span><span class="va">ri_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/do.call.html">do.call</a></span><span class="op">(</span><span class="va">rbind</span>, <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="va">n_groups</span><span class="op">)</span>, <span class="kw">function</span><span class="op">(</span><span class="va">g</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">b0</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">0</span>, <span class="fl">2</span><span class="op">)</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="va">x</span>,</span>
<span>    y <span class="op">=</span> <span class="fl">3</span> <span class="op">+</span> <span class="va">b0</span> <span class="op">+</span> <span class="fl">2</span> <span class="op">*</span> <span class="va">x</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n_obs</span>, <span class="fl">0</span>, <span class="fl">0.5</span><span class="op">)</span>,</span>
<span>    group <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">g</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">}</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Random slope model</span></span>
<span><span class="va">rs_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/do.call.html">do.call</a></span><span class="op">(</span><span class="va">rbind</span>, <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="va">n_groups</span><span class="op">)</span>, <span class="kw">function</span><span class="op">(</span><span class="va">g</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">b0</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">0</span>, <span class="fl">2</span><span class="op">)</span></span>
<span>  <span class="va">b1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">0</span>, <span class="fl">1.5</span><span class="op">)</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="va">x</span>,</span>
<span>    y <span class="op">=</span> <span class="fl">3</span> <span class="op">+</span> <span class="va">b0</span> <span class="op">+</span> <span class="op">(</span><span class="fl">2</span> <span class="op">+</span> <span class="va">b1</span><span class="op">)</span> <span class="op">*</span> <span class="va">x</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n_obs</span>, <span class="fl">0</span>, <span class="fl">0.5</span><span class="op">)</span>,</span>
<span>    group <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">g</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">}</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">ri_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, y <span class="op">=</span> <span class="va">y</span>, group <span class="op">=</span> <span class="va">group</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span>colour <span class="op">=</span> <span class="st">"#2E86AB"</span>, alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_abline</a></span><span class="op">(</span>intercept <span class="op">=</span> <span class="fl">3</span>, slope <span class="op">=</span> <span class="fl">2</span>,</span>
<span>              linetype <span class="op">=</span> <span class="st">"dashed"</span>, colour <span class="op">=</span> <span class="st">"grey30"</span>,</span>
<span>              linewidth <span class="op">=</span> <span class="fl">1.2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Time"</span>, y <span class="op">=</span> <span class="st">"Response"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">rs_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, y <span class="op">=</span> <span class="va">y</span>, group <span class="op">=</span> <span class="va">group</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span>colour <span class="op">=</span> <span class="st">"#E84855"</span>, alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_abline</a></span><span class="op">(</span>intercept <span class="op">=</span> <span class="fl">3</span>, slope <span class="op">=</span> <span class="fl">2</span>,</span>
<span>              linetype <span class="op">=</span> <span class="st">"dashed"</span>, colour <span class="op">=</span> <span class="st">"grey30"</span>,</span>
<span>              linewidth <span class="op">=</span> <span class="fl">1.2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Time"</span>, y <span class="op">=</span> <span class="st">"Response"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p1</span> <span class="op">+</span> <span class="va">p2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-random-effects-plot" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-random-effects-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04b-mixed-effects_files/figure-html/fig-random-effects-plot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-random-effects-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.1: Left: a random intercept model, all groups share the same slope but have different intercepts. The dashed line is the population-level (fixed effect) trajectory; solid lines are group-specific trajectories. Right: a random slope model, groups differ in both their starting level and their rate of change. The variation in slopes is itself a scientifically meaningful quantity.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="choosing-between-random-intercepts-and-random-slopes" class="level3" data-number="9.2.4"><h3 data-number="9.2.4" class="anchored" data-anchor-id="choosing-between-random-intercepts-and-random-slopes">
<span class="header-section-number">9.2.4</span> Choosing Between Random Intercepts and Random Slopes</h3>
<p>The choice between a random intercept model and a random slope model is not merely statistical but it reflects a scientific question. A random intercept model asks: do groups differ in their average response level? A random slope model asks additionally: do groups differ in how the response changes with the predictor?</p>
<p>In a clinical trial measuring recovery over time, a random intercept captures the fact that some patients start sicker than others. A random slope captures the additional possibility that some patients improve faster than others which is a clinically important question about treatment response heterogeneity.</p>
<p>Include a random slope when you have scientific reason to believe that the relationship between the predictor and the response genuinely varies across groups, and you got enough data to estimate the additional variance component reliably.</p>
<p>As a practical guide, at least 5-6 groups are needed to estimate a random intercept variance reliably, and at least 10-15 groups for a random intercept plus slope model. With fewer groups, the variance estimates will be unstable and the model may fail to converge.</p>
</section></section><section id="lme4-and-nlme-a-practical-guide" class="level2" data-number="9.3"><h2 data-number="9.3" class="anchored" data-anchor-id="lme4-and-nlme-a-practical-guide">
<span class="header-section-number">9.3</span> <code>lme4</code> and <code>nlme</code>: A Practical Guide</h2>
<section id="two-packages-different-strengths" class="level3" data-number="9.3.1"><h3 data-number="9.3.1" class="anchored" data-anchor-id="two-packages-different-strengths">
<span class="header-section-number">9.3.1</span> Two Packages, Different Strengths</h3>
<p>Two R packages dominate mixed-effects modelling in biology: <code>lme4</code> <span class="citation" data-cites="Bates2015">(<a href="#ref-Bates2015" role="doc-biblioref">Bates et al. 2015</a>)</span> and <code>nlme</code> <span class="citation" data-cites="Pinheiro2000">(<a href="#ref-Pinheiro2000" role="doc-biblioref">Pinheiro and Bates 2000</a>)</span>. They fit the same broad class of models but differ in their syntax, capabilities, and defaults.</p>
<p><strong><code>lme4</code></strong> is the modern standard for most applications. It is fast, handles crossed and nested random effects naturally, and uses a clean formula syntax. Its main limitation is that it does not directly provide p-values for fixed effects which is a deliberate design decision by its authors that reflects genuine statistical controversy (see Section 9.4).</p>
<p><strong><code>nlme</code></strong> is older but offers features that <code>lme4</code> does not: direct specification of residual covariance structures (useful for repeated measures with heterogeneous variances) and nonlinear mixed models. Its syntax is more verbose and it handles crossed random effects less elegantly than <code>lme4</code>.</p>
<p>For most applications in this book, <code>lme4</code> is the right choice.</p>
</section><section id="the-lme4-formula-syntax" class="level3" data-number="9.3.2"><h3 data-number="9.3.2" class="anchored" data-anchor-id="the-lme4-formula-syntax">
<span class="header-section-number">9.3.2</span> The <code>lme4</code> Formula Syntax</h3>
<p><code>lme4</code> extends R’s standard model formula with a notation for random effects: <code>(random_effect | grouping_factor)</code>. The vertical bar <code>|</code> separates the random effect structure from the grouping factor.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 56%">
<col style="width: 43%">
</colgroup>
<thead><tr class="header">
<th>Formula</th>
<th>Model</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>y ~ x + (1 | group)</code></td>
<td>Fixed slope for x; random intercept by group</td>
</tr>
<tr class="even">
<td><code>y ~ x + (x | group)</code></td>
<td>Fixed slope for x; random intercept and slope by group</td>
</tr>
<tr class="odd">
<td><code>y ~ x + (1 | group) + (1 | block)</code></td>
<td>Two crossed random effects</td>
</tr>
<tr class="even">
<td><code>y ~ x + (1 | region/hospital)</code></td>
<td>Hospital nested within region</td>
</tr>
<tr class="odd">
<td><code>y ~ x + (1 | region) + (1 | region:hospital)</code></td>
<td>Equivalent nested specification</td>
</tr>
</tbody>
</table></section><section id="sec-rim" class="level3" data-number="9.3.3"><h3 data-number="9.3.3" class="anchored" data-anchor-id="sec-rim">
<span class="header-section-number">9.3.3</span> Fitting and Interpreting a Random Intercept Model</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/lme4/lme4/">lme4</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>#&gt; Loading required package: Matrix</code></pre>
</div>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">42</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Simulate a simple random intercept dataset</span></span>
<span><span class="co"># 20 patients per hospital, 10 hospitals, one treatment covariate</span></span>
<span><span class="va">n_hospitals</span> <span class="op">&lt;-</span> <span class="fl">10</span></span>
<span><span class="va">n_patients</span>  <span class="op">&lt;-</span> <span class="fl">20</span></span>
<span><span class="va">hospital_sd</span> <span class="op">&lt;-</span> <span class="fl">3</span></span>
<span><span class="va">patient_sd</span>  <span class="op">&lt;-</span> <span class="fl">2</span></span>
<span></span>
<span><span class="va">df_lme</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/do.call.html">do.call</a></span><span class="op">(</span><span class="va">rbind</span>, <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="va">n_hospitals</span><span class="op">)</span>, <span class="kw">function</span><span class="op">(</span><span class="va">h</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">hospital_effect</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">0</span>, <span class="va">hospital_sd</span><span class="op">)</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>    outcome <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n_patients</span>, mean <span class="op">=</span> <span class="fl">50</span> <span class="op">+</span> <span class="va">hospital_effect</span> <span class="op">+</span></span>
<span>                             <span class="fl">2</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">n_patients</span>, <span class="fl">1</span>, <span class="fl">0.5</span><span class="op">)</span>,</span>
<span>                      sd   <span class="op">=</span> <span class="va">patient_sd</span><span class="op">)</span>,</span>
<span>    treatment <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Control"</span>, <span class="st">"Treatment"</span><span class="op">)</span>, each <span class="op">=</span> <span class="va">n_patients</span> <span class="op">/</span> <span class="fl">2</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    hospital <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">h</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">}</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Fit random intercept model</span></span>
<span><span class="va">fit_ri</span> <span class="op">&lt;-</span> <span class="fu">lme4</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">outcome</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">hospital</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">df_lme</span>, REML <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_ri</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Linear mixed model fit by REML ['lmerMod']
#&gt; Formula: outcome ~ treatment + (1 | hospital)
#&gt;    Data: df_lme
#&gt; 
#&gt; REML criterion at convergence: 897.6
#&gt; 
#&gt; Scaled residuals: 
#&gt;     Min      1Q  Median      3Q     Max 
#&gt; -2.8980 -0.6451  0.0198  0.5870  3.3917 
#&gt; 
#&gt; Random effects:
#&gt;  Groups   Name        Variance Std.Dev.
#&gt;  hospital (Intercept) 5.609    2.368   
#&gt;  Residual             4.486    2.118   
#&gt; Number of obs: 200, groups:  hospital, 10
#&gt; 
#&gt; Fixed effects:
#&gt;                    Estimate Std. Error t value
#&gt; (Intercept)         52.8446     0.7783  67.895
#&gt; treatmentTreatment   0.2663     0.2995   0.889
#&gt; 
#&gt; Correlation of Fixed Effects:
#&gt;             (Intr)
#&gt; trtmntTrtmn -0.192</code></pre>
</div>
</div>
<p>The summary output has four sections worth reading carefully.</p>
<p><strong>Random effects:</strong> the variance components. <code>(Intercept)</code> under <code>hospital</code> is <span class="math inline">\(\hat{\sigma}^2_b\)</span>: the estimated variance in baseline outcomes across hospitals. <code>Residual</code> is <span class="math inline">\(\hat{\sigma}^2_\varepsilon\)</span>: the within-hospital, within-patient variation. Their ratio tells you how much of the total variation is attributable to hospital-level differences. From the result, the intraclass correlation is therefore <span class="math inline">\(\text{ICC} = 5.61 / (5.61 + 4.49) = 0.56\)</span>, meaning that 56% of the total variation in outcomes is attributable to systematic differences between hospitals which a substantial clustering effect that would badly distort any analysis that ignored it.</p>
<p><strong>Fixed effects:</strong> the coefficient table. The <code>(Intercept)</code> is the estimated mean outcome in the reference group (Control) at an average hospital. The treatment coefficient (here <code>treatmentTreatment</code>) is the estimated average difference between treatment and control, after accounting for hospital-level variation.</p>
<p><strong>Correlation of fixed effects:</strong> the correlation between the intercept and treatment coefficient estimates. Large correlations (close to ±1) can indicate collinearity or model specification problems.</p>
<p><strong>Number of observations and groups:</strong> always verify these match your data. Here 200 observations are nested in 10 hospitals, 20 patients per hospital, as specified. A mismatch between these numbers and your intended design is the first sign of a coding error in the grouping factor.</p>
</section><section id="sec-reml-ml" class="level3" data-number="9.3.4"><h3 data-number="9.3.4" class="anchored" data-anchor-id="sec-reml-ml">
<span class="header-section-number">9.3.4</span> REML vs ML Estimation</h3>
<p><code>lme4</code> offers two estimation methods, controlled by the <code>REML</code> argument:</p>
<p><strong>REML (Restricted Maximum Likelihood)</strong> is the default (<code>REML = TRUE</code>)and should be used when the goal is to estimate variance components. REML produces unbiased estimates of <span class="math inline">\(\sigma^2_b\)</span> and <span class="math inline">\(\sigma^2_\varepsilon\)</span>, analogous to dividing by <span class="math inline">\(n-1\)</span> rather than <span class="math inline">\(n\)</span> when estimating a variance.</p>
<p><strong>ML (Maximum Likelihood)</strong> should be used (<code>REML = FALSE</code>) when comparing models with different fixed effect structures using likelihood ratio tests. REML likelihoods are not comparable across models with different fixed effects because they are computed on different effective datasets.</p>
<p>The practical workflow is therefore always two steps: use <code>REML = FALSE</code> to compare models and identify which fixed effects belong in the model, then refit the winning model with <code>REML = TRUE</code> to obtain the final, unbiased variance component estimates for reporting.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Step 1: fit both models with ML = FALSE to enable</span></span>
<span><span class="co"># a valid likelihood ratio test comparing their fixed effects.</span></span>
<span><span class="co"># REML = FALSE is mandatory here. Comparing REML likelihoods</span></span>
<span><span class="co"># across models with different fixed effects is not valid.</span></span>
<span><span class="va">fit_ri_ml</span>   <span class="op">&lt;-</span> <span class="fu">lme4</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">outcome</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">hospital</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">df_lme</span>, REML <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">fit_null_ml</span> <span class="op">&lt;-</span> <span class="fu">lme4</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">outcome</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">hospital</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">df_lme</span>, REML <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Likelihood ratio test: does adding treatment improve the fit?</span></span>
<span><span class="co"># The chi-squared statistic is -2 * (logLik(null) - logLik(full))</span></span>
<span><span class="co"># with degrees of freedom equal to the difference in parameters.</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">fit_null_ml</span>, <span class="va">fit_ri_ml</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Data: df_lme
#&gt; Models:
#&gt; fit_null_ml: outcome ~ 1 + (1 | hospital)
#&gt; fit_ri_ml: outcome ~ treatment + (1 | hospital)
#&gt;             npar    AIC    BIC  logLik -2*log(L)  Chisq Df Pr(&gt;Chisq)
#&gt; fit_null_ml    3 905.11 915.00 -449.55    899.11                     
#&gt; fit_ri_ml      4 906.31 919.51 -449.16    898.31 0.7931  1     0.3732</code></pre>
</div>
</div>
<p>The likelihood ratio test compares the log-likelihoods of the two models: the null model (hospital random effect only, no treatment) against the full model (hospital random effect plus treatment). The test statistic is <span class="math inline">\(\chi^2 = 0.79\)</span> on 1 degree of freedom (<span class="math inline">\(p = 0.373\)</span>), indicating that adding treatment does not significantly improve the fit. This is consistent with the small and imprecise treatment coefficient seen in the summary output indicating that the simulated treatment effect was too small relative to the within-hospital noise to be detectable with this sample size.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Step 2: refit the chosen model with REML = TRUE to obtain</span></span>
<span><span class="co"># unbiased variance component estimates for reporting.</span></span>
<span><span class="co"># Never report variance components from a model fitted with</span></span>
<span><span class="co"># REML = FALSE, they will be systematically underestimated,</span></span>
<span><span class="co"># particularly when the number of groups is small.</span></span>
<span><span class="va">fit_ri_reml</span> <span class="op">&lt;-</span> <span class="fu">lme4</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">outcome</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">hospital</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">df_lme</span>, REML <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_ri_reml</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Linear mixed model fit by REML ['lmerMod']
#&gt; Formula: outcome ~ treatment + (1 | hospital)
#&gt;    Data: df_lme
#&gt; 
#&gt; REML criterion at convergence: 897.6
#&gt; 
#&gt; Scaled residuals: 
#&gt;     Min      1Q  Median      3Q     Max 
#&gt; -2.8980 -0.6451  0.0198  0.5870  3.3917 
#&gt; 
#&gt; Random effects:
#&gt;  Groups   Name        Variance Std.Dev.
#&gt;  hospital (Intercept) 5.609    2.368   
#&gt;  Residual             4.486    2.118   
#&gt; Number of obs: 200, groups:  hospital, 10
#&gt; 
#&gt; Fixed effects:
#&gt;                    Estimate Std. Error t value
#&gt; (Intercept)         52.8446     0.7783  67.895
#&gt; treatmentTreatment   0.2663     0.2995   0.889
#&gt; 
#&gt; Correlation of Fixed Effects:
#&gt;             (Intr)
#&gt; trtmntTrtmn -0.192</code></pre>
</div>
</div>
<p>The REML-fitted model is the one whose random effect variances and fixed effect standard errors should be reported. In this dataset the difference between ML and REML estimates will be modest because there are a reasonable number of groups (10 hospitals). With only 5 or 6 groups, the ML variance estimates can be substantially smaller than the REML estimates, and using ML for final reporting would meaningfully understate the uncertainty in the fixed effects.</p>
</section><section id="extracting-random-effects" class="level3" data-number="9.3.5"><h3 data-number="9.3.5" class="anchored" data-anchor-id="extracting-random-effects">
<span class="header-section-number">9.3.5</span> Extracting Random Effects</h3>
<p>Going back to our previous fit (<a href="#sec-rim" class="quarto-xref"><span class="quarto-unresolved-ref">sec-rim</span></a>), we will extract and plot the random effects.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># The estimated random intercepts for each hospital</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/nlme/man/random.effects.html">ranef</a></span><span class="op">(</span><span class="va">fit_ri</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; $hospital
#&gt;     (Intercept)
#&gt; 1   1.835227326
#&gt; 2  -0.161331276
#&gt; 3   0.488976769
#&gt; 4   1.282251747
#&gt; 5  -2.168889243
#&gt; 6  -5.474238894
#&gt; 7   0.142364080
#&gt; 8   2.454755367
#&gt; 9   0.004538835
#&gt; 10  1.596345288
#&gt; 
#&gt; with conditional variances for "hospital"</code></pre>
</div>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Visualise: caterpillar plot of random intercepts</span></span>
<span><span class="va">re_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/nlme/man/random.effects.html">ranef</a></span><span class="op">(</span><span class="va">fit_ri</span>, condVar <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">re_df</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/reorder.factor.html">reorder</a></span><span class="op">(</span><span class="va">grp</span>, <span class="va">condval</span><span class="op">)</span>, y <span class="op">=</span> <span class="va">condval</span>,</span>
<span>                  ymin <span class="op">=</span> <span class="va">condval</span> <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> <span class="va">condsd</span>,</span>
<span>                  ymax <span class="op">=</span> <span class="va">condval</span> <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> <span class="va">condsd</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, linetype <span class="op">=</span> <span class="st">"dashed"</span>, colour <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_pointrange</a></span><span class="op">(</span>colour <span class="op">=</span> <span class="st">"#2E86AB"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_flip.html">coord_flip</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Hospital"</span>, y <span class="op">=</span> <span class="st">"Random intercept estimate"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-random-effects-extraction" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-random-effects-extraction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04b-mixed-effects_files/figure-html/fig-random-effects-extraction-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-random-effects-extraction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.2: Hospital random intercepts. Estimated deviation of each hospital from the grand mean.
</figcaption></figure>
</div>
</div>
</div>
<p>The caterpillar plot shows the estimated random intercept for each hospital with its 95% uncertainty interval. Hospitals whose intervals do not overlap zero are performing notably above or below average, after accounting for the treatment effect.</p>
</section></section><section id="degrees-of-freedom-and-p-values-the-kenward-roger-and-satterthwaite-debate" class="level2" data-number="9.4"><h2 data-number="9.4" class="anchored" data-anchor-id="degrees-of-freedom-and-p-values-the-kenward-roger-and-satterthwaite-debate">
<span class="header-section-number">9.4</span> Degrees of Freedom and P-Values: The Kenward-Roger and Satterthwaite Debate</h2>
<section id="why-lme4-does-not-give-p-values" class="level3" data-number="9.4.1"><h3 data-number="9.4.1" class="anchored" data-anchor-id="why-lme4-does-not-give-p-values">
<span class="header-section-number">9.4.1</span> Why <code>lme4</code> Does Not Give P-Values</h3>
<p>Users fitting their first mixed model in R are often surprised to find that <code>summary(fit_ri)</code> produces <span class="math inline">\(t\)</span> values for the fixed effects but no p-values. This is not an oversight but a deliberate design decision by the <code>lme4</code> authors, rooted in a genuine and unresolved statistical problem.</p>
<p>In a standard linear model, the denominator degrees of freedom for each <span class="math inline">\(F\)</span> or <span class="math inline">\(t\)</span> test are well defined and exact. In a mixed model, they are not. The sampling distribution of the <span class="math inline">\(t\)</span> statistic for a fixed effect in a mixed model is approximately <span class="math inline">\(t\)</span>-distributed, but the degrees of freedom of that approximation depend on the covariance structure of the random effects, the balance of the data, and the specific parameter being tested and there is no universally agreed formula for computing them. Using the wrong degrees of freedom can make tests either too liberal or too conservative.</p>
<p>Two approximations are in common use, and both are implemented in the <code>lmerTest</code> package <span class="citation" data-cites="Kuznetsova2017">(<a href="#ref-Kuznetsova2017" role="doc-biblioref">Kuznetsova, Brockhoff, and Christensen 2017</a>)</span>:</p>
</section><section id="satterthwaites-approximation" class="level3" data-number="9.4.2"><h3 data-number="9.4.2" class="anchored" data-anchor-id="satterthwaites-approximation">
<span class="header-section-number">9.4.2</span> Satterthwaite’s Approximation</h3>
<p>Satterthwaite’s method <span class="citation" data-cites="satterthwaite1946">(<a href="#ref-satterthwaite1946" role="doc-biblioref">Satterthwaite 1946</a>)</span> estimates the effective degrees of freedom for each fixed effect test by matching the moments of the approximate <span class="math inline">\(t\)</span> distribution to the variance components of the model. It is computationally fast and works well for many standard designs.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># lmerTest automatically upgrades lmer() to provide p-values</span></span>
<span><span class="va">fit_ri_test</span> <span class="op">&lt;-</span> <span class="fu">lmerTest</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lmerTest/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">outcome</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">hospital</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">df_lme</span>, REML <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_ri_test</span><span class="op">)</span> <span class="co"># now includes df and p-values</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Linear mixed model fit by REML. t-tests use Satterthwaite's method [
#&gt; lmerModLmerTest]
#&gt; Formula: outcome ~ treatment + (1 | hospital)
#&gt;    Data: df_lme
#&gt; 
#&gt; REML criterion at convergence: 897.6
#&gt; 
#&gt; Scaled residuals: 
#&gt;     Min      1Q  Median      3Q     Max 
#&gt; -2.8980 -0.6451  0.0198  0.5870  3.3917 
#&gt; 
#&gt; Random effects:
#&gt;  Groups   Name        Variance Std.Dev.
#&gt;  hospital (Intercept) 5.609    2.368   
#&gt;  Residual             4.486    2.118   
#&gt; Number of obs: 200, groups:  hospital, 10
#&gt; 
#&gt; Fixed effects:
#&gt;                    Estimate Std. Error       df t value Pr(&gt;|t|)    
#&gt; (Intercept)         52.8446     0.7783   9.7048  67.895 2.54e-14 ***
#&gt; treatmentTreatment   0.2663     0.2995 189.0000   0.889    0.375    
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; Correlation of Fixed Effects:
#&gt;             (Intr)
#&gt; trtmntTrtmn -0.192</code></pre>
</div>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">fit_ri_test</span><span class="op">)</span> <span class="co"># F tests with Satterthwaite df</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Type III Analysis of Variance Table with Satterthwaite's method
#&gt;           Sum Sq Mean Sq NumDF DenDF F value Pr(&gt;F)
#&gt; treatment 3.5466  3.5466     1   189  0.7905 0.3751</code></pre>
</div>
</div>
<p>The output now includes degrees of freedom and p-values for each fixed effect, computed via Satterthwaite’s approximation. The intercept is highly significant (<span class="math inline">\(p &lt; 0.001\)</span>), but this is not a meaningful result as it simply tests whether the grand mean recovery score differs from zero, which is never a question of scientific interest. What matters is the treatment coefficient: the new protocol does not produce a significantly different recovery score from the control (<span class="math inline">\(p = 0.375\)</span>), consistent with the likelihood ratio test result from <a href="#sec-reml-ml" class="quarto-xref"><span class="quarto-unresolved-ref">sec-reml-ml</span></a>.</p>
<p>The <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> call produces a Type III <span class="math inline">\(F\)</span> test (see <a href="#sec-type3" class="quarto-xref"><span class="quarto-unresolved-ref">sec-type3</span></a>) for the treatment fixed effect using Satterthwaite degrees of freedom. It reaches the same conclusion: no significant difference between treatment groups. As a reminder, this reflects the simulated data rather than a real clinical finding. The true treatment effect in the simulation was small relative to the within-hospital noise, and the study as simulated is underpowered to detect it reliably.</p>
</section><section id="kenward-roger-approximation" class="level3" data-number="9.4.3"><h3 data-number="9.4.3" class="anchored" data-anchor-id="kenward-roger-approximation">
<span class="header-section-number">9.4.3</span> Kenward-Roger Approximation</h3>
<p>The Kenward-Roger method <span class="citation" data-cites="Kenward1997">(<a href="#ref-Kenward1997" role="doc-biblioref">Kenward and Roger 1997</a>)</span> uses a more sophisticated adjustment that also corrects the standard errors of the fixed effects for small-sample bias in the variance component estimates. It is more computationally demanding than Satterthwaite but is considered more accurate, particularly with small numbers of groups or unbalanced designs.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># KR F test via lmerTest</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">fit_ri_test</span>, ddf <span class="op">=</span> <span class="st">"Kenward-Roger"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Type III Analysis of Variance Table with Kenward-Roger's method
#&gt;           Sum Sq Mean Sq NumDF DenDF F value Pr(&gt;F)
#&gt; treatment 3.5466  3.5466     1   189  0.7905 0.3751</code></pre>
</div>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Or via pbkrtest directly</span></span>
<span><span class="co">## Kenward-Roger via lmerTest first</span></span>
<span><span class="va">fit_ri_kr</span>  <span class="op">&lt;-</span> <span class="fu">lmerTest</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lmerTest/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">outcome</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">hospital</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">df_lme</span>, REML <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit_null_kr</span> <span class="op">&lt;-</span> <span class="fu">lmerTest</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lmerTest/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">outcome</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">hospital</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">df_lme</span>, REML <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Then test</span></span>
<span><span class="fu">pbkrtest</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pbkrtest/man/kr__modcomp.html">KRmodcomp</a></span><span class="op">(</span><span class="va">fit_ri_kr</span>, <span class="va">fit_null_kr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; large : outcome ~ treatment + (1 | hospital)
#&gt; small : outcome ~ 1 + (1 | hospital)
#&gt;           stat      ndf      ddf F.scaling p.value
#&gt; Ftest   0.7905   1.0000 189.0000         1  0.3751</code></pre>
</div>
</div>
<p>Both methods (<code>lmerTest</code> and <code>pbkrtest</code>) yield similar results which are also similar to the previous one using Satterthwaite’s approximation. This reflects the simulated data and would not be the case in a real case.</p>
</section><section id="which-method-to-use" class="level3" data-number="9.4.4"><h3 data-number="9.4.4" class="anchored" data-anchor-id="which-method-to-use">
<span class="header-section-number">9.4.4</span> Which Method to Use?</h3>
<p>The practical guidance is straightforward:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 36%">
<col style="width: 63%">
</colgroup>
<thead><tr class="header">
<th>Situation</th>
<th>Recommended method</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Large balanced dataset, many groups</td>
<td>Satterthwaite which is fast and accurate</td>
</tr>
<tr class="even">
<td>Small number of groups (<span class="math inline">\(&lt; 20\)</span>)</td>
<td>Kenward-Roger which is better small-sample correction</td>
</tr>
<tr class="odd">
<td>Unbalanced design</td>
<td>Kenward-Roger which is more robust</td>
</tr>
<tr class="even">
<td>Quick exploratory analysis</td>
<td>Satterthwaite which is an acceptable approximation</td>
</tr>
<tr class="odd">
<td>Confirmatory clinical analysis</td>
<td>Kenward-Roger which is conservative and defensible</td>
</tr>
</tbody>
</table>
<p>Both methods give similar results with large, balanced datasets. The differences matter most with small numbers of groups which is a common situation in biology, where experiments often have 5-15 clusters. When in doubt, use Kenward-Roger and note the method in your methods section.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show me the maths!
</div>
</div>
<div class="callout-body-container callout-body">
<p>For the mathematical derivation of both the Satterthwaite and Kenward-Roger degree of freedom approximations, see <a href="#sec-ftest-normality-maths" class="quarto-xref"><span class="quarto-unresolved-ref">sec-ftest-normality-maths</span></a> in Appendix A.</p>
</div>
</div>
</section></section><section id="example-patient-nested-in-hospital-nested-in-region" class="level2" data-number="9.5"><h2 data-number="9.5" class="anchored" data-anchor-id="example-patient-nested-in-hospital-nested-in-region">
<span class="header-section-number">9.5</span> Example: Patient Nested in Hospital Nested in Region</h2>
<section id="the-study" class="level3" data-number="9.5.1"><h3 data-number="9.5.1" class="anchored" data-anchor-id="the-study">
<span class="header-section-number">9.5.1</span> The Study</h3>
<p>A national health study investigates the effect of a new physiotherapy protocol on functional recovery scores (0-100) in patients following knee replacement surgery. Patients are recruited from 15 hospitals distributed across 3 regions (<a href="#sec-physio" class="quarto-xref"><span class="quarto-unresolved-ref">sec-physio</span></a>). Each hospital contributes between 8 and 12 patients, assigned to either the standard protocol (control) or the new physiotherapy protocol (treatment). The hierarchical structure is:</p>
<p><span class="math display">\[\text{Region} \supset \text{Hospital} \supset \text{Patient}\]</span></p>
<p>Treatment is assigned at the patient level: individual patients within the same hospital receive different protocols. This is important: it means hospital and region are nuisance grouping factors that must be accounted for, not treatment factors being tested.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">physio</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;     recovery         treatment     hospital  region 
#&gt;  Min.   :39.19   Control  :78   H14    :12   R1:52  
#&gt;  1st Qu.:57.59   Treatment:70   H23    :12   R2:45  
#&gt;  Median :64.79                  H34    :12   R3:51  
#&gt;  Mean   :64.38                  H12    :11          
#&gt;  3rd Qu.:72.37                  H13    :11          
#&gt;  Max.   :95.10                  H32    :11          
#&gt;                                 (Other):79</code></pre>
</div>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span></span>
<span>  <span class="st">"Total patients:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">physio</span><span class="op">)</span>, </span>
<span>  <span class="st">"\nPatients per hospital:\n"</span>, <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">physio</span><span class="op">$</span><span class="va">hospital</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Total patients: 148 
#&gt; Patients per hospital:
#&gt;  9 11 11 12 9 8 9 12 8 8 10 11 9 12 9</code></pre>
</div>
</div>
</section><section id="visualising-the-nested-structure" class="level3" data-number="9.5.2"><h3 data-number="9.5.2" class="anchored" data-anchor-id="visualising-the-nested-structure">
<span class="header-section-number">9.5.2</span> Visualising the Nested Structure</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Hospital means</span></span>
<span><span class="va">hosp_means</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aggregate.html">aggregate</a></span><span class="op">(</span><span class="va">recovery</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="va">hospital</span> <span class="op">+</span> <span class="va">region</span>, data <span class="op">=</span> <span class="va">physio</span>, FUN <span class="op">=</span> <span class="va">mean</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">physio</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">treatment</span>, y <span class="op">=</span> <span class="va">recovery</span>, colour <span class="op">=</span> <span class="va">hospital</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.15</span>, alpha <span class="op">=</span> <span class="fl">0.4</span>, size <span class="op">=</span> <span class="fl">1.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">hosp_means</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">recovery</span><span class="op">)</span>, size <span class="op">=</span> <span class="fl">4</span>, shape <span class="op">=</span> <span class="fl">18</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">hosp_means</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">recovery</span>, group <span class="op">=</span> <span class="va">hospital</span><span class="op">)</span>, alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span> <span class="va">region</span>, labeller <span class="op">=</span> <span class="va">label_both</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_viridis.html">scale_colour_viridis_d</a></span><span class="op">(</span>option <span class="op">=</span> <span class="st">"D"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="cn">NULL</span>, y <span class="op">=</span> <span class="st">"Recovery score"</span>, colour <span class="op">=</span> <span class="st">"Hospital"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"bottom"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-nested-plot" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-nested-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04b-mixed-effects_files/figure-html/fig-nested-plot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nested-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.3: Recovery scores by treatment group, hospital, and region. Each panel is a region; within each panel, points are coloured by hospital. The substantial variation in hospital means within and across regions illustrates why the nested random effect structure must be modelled explicitly.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="fitting-the-three-level-nested-model" class="level3" data-number="9.5.3"><h3 data-number="9.5.3" class="anchored" data-anchor-id="fitting-the-three-level-nested-model">
<span class="header-section-number">9.5.3</span> Fitting the Three-Level Nested Model</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/lme4/lme4/">lme4</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/runehaubo/lmerTestR">lmerTest</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>#&gt; 
#&gt; Attaching package: 'lmerTest'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>#&gt; The following object is masked from 'package:lme4':
#&gt; 
#&gt;     lmer</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>#&gt; The following object is masked from 'package:stats':
#&gt; 
#&gt;     step</code></pre>
</div>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Three-level nested model:</span></span>
<span><span class="co"># hospital nested within region, both as random intercepts</span></span>
<span><span class="va">fit_nested</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span></span>
<span>  <span class="va">recovery</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">region</span><span class="op">/</span><span class="va">hospital</span><span class="op">)</span>,</span>
<span>  data <span class="op">=</span> <span class="va">physio</span>,</span>
<span>  REML <span class="op">=</span> <span class="cn">TRUE</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_nested</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Linear mixed model fit by REML. t-tests use Satterthwaite's method [
#&gt; lmerModLmerTest]
#&gt; Formula: recovery ~ treatment + (1 | region/hospital)
#&gt;    Data: physio
#&gt; 
#&gt; REML criterion at convergence: 1053.2
#&gt; 
#&gt; Scaled residuals: 
#&gt;      Min       1Q   Median       3Q      Max 
#&gt; -3.07356 -0.62171  0.09592  0.59586  2.31967 
#&gt; 
#&gt; Random effects:
#&gt;  Groups          Name        Variance Std.Dev.
#&gt;  hospital:region (Intercept) 22.799   4.775   
#&gt;  region          (Intercept)  8.732   2.955   
#&gt;  Residual                    64.117   8.007   
#&gt; Number of obs: 148, groups:  hospital:region, 15; region, 3
#&gt; 
#&gt; Fixed effects:
#&gt;                    Estimate Std. Error      df t value Pr(&gt;|t|)    
#&gt; (Intercept)          61.329      2.294   2.351  26.740 0.000564 ***
#&gt; treatmentTreatment    6.097      1.320 132.003   4.619 9.03e-06 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; Correlation of Fixed Effects:
#&gt;             (Intr)
#&gt; trtmntTrtmn -0.272</code></pre>
</div>
</div>
<p>The <code>(1 | region/hospital)</code> notation specifies hospital nested within region, equivalent to <code>(1 | region) + (1 | region:hospital)</code>. It produces three variance components: region-level variance (<span class="math inline">\(\hat{\sigma}^2_{\text{region}}\)</span>), hospital-within-region variance (<span class="math inline">\(\hat{\sigma}^2_{\text{hospital}}\)</span>), and residual patient-level variance (<span class="math inline">\(\hat{\sigma}^2_\varepsilon\)</span>).</p>
<p>The summary output reveals a clear and well-structured result across all three sections.</p>
<p><strong>Random effects:</strong> three variance components are estimated, corresponding to the three levels of the hierarchy. The hospital-within-region variance is <span class="math inline">\(\hat{\sigma}^2_{\text{hospital}} = 22.80\)</span> (SD = 4.78), the region variance is <span class="math inline">\(\hat{\sigma}^2_{\text{region}} = 8.73\)</span> (SD = 2.96), and the residual patient-level variance is <span class="math inline">\(\hat{\sigma}^2_\varepsilon = 64.12\)</span> (SD = 8.01). The total variance is therefore <span class="math inline">\(22.80 + 8.73 + 64.12 = 95.65\)</span>, of which the clustering structure (hospital and region combined) accounts for <span class="math inline">\((22.80 + 8.73) / 95.65 = 33\%\)</span>. This is a substantial ICC: one third of the variation in recovery scores is attributable to which hospital and region a patient belongs to, entirely independent of treatment. An analysis that ignored this structure would dramatically underestimate the uncertainty in the treatment effect estimate.</p>
<p><strong>Fixed effects:</strong> the treatment coefficient is <span class="math inline">\(\hat{\beta} = 6.10\)</span> (SE = 1.32), with a Satterthwaite-approximated <span class="math inline">\(t_{132} = 4.62\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>. Patients receiving the new physiotherapy protocol recovered an estimated 6.1 points higher on the recovery scale than control patients, after accounting for the hospital and region clustering. This is a clinically meaningful and statistically convincing result. Notice that the degrees of freedom for the treatment test (132) are much larger than those for the intercept (2.35) reflecting the fact that treatment was randomised at the patient level (148 patients), while the intercept is estimated at the region level (only 3 regions), where very little information is available. The Satterthwaite approximation correctly propagates this distinction into the inference.</p>
<p>The correlation between the intercept and treatment coefficient estimates is <span class="math inline">\(-0.27\)</span>, indicating modest negative correlation: hospitals with higher baseline recovery tend to show slightly smaller treatment effects in the estimates, though this could be a property of the estimation geometry rather than a substantive finding.</p>
<p><strong>Number of observations:</strong> 148 patients are nested in 15 hospital-region combinations, which are in turn nested in 3 regions. The modest number of regions (3) is the binding constraint on inference about region-level effects and explains the very low degrees of freedom (2.35) for the intercept test. With only 3 regions, the region-level variance estimate (<span class="math inline">\(\hat{\sigma}^2_{\text {region}} = 8.73\)</span>) should be interpreted cautiously as it is based on very sparse information and carries wide uncertainty.</p>
</section><section id="diagnosing-the-model" class="level3" data-number="9.5.4"><h3 data-number="9.5.4" class="anchored" data-anchor-id="diagnosing-the-model">
<span class="header-section-number">9.5.4</span> Diagnosing the Model</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Residual plot</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">fit_nested</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04b-mixed-effects_files/figure-html/nested-diagnostics-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Q-Q plot of residuals</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqnorm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">resid</a></span><span class="op">(</span><span class="va">fit_nested</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqline</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">resid</a></span><span class="op">(</span><span class="va">fit_nested</span><span class="op">)</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04b-mixed-effects_files/figure-html/nested-diagnostics-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Q-Q plot of random effects — should also be approximately normal</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqnorm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/nlme/man/random.effects.html">ranef</a></span><span class="op">(</span><span class="va">fit_nested</span><span class="op">)</span><span class="op">$</span><span class="va">hospital</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span>, main <span class="op">=</span> <span class="st">"Q-Q plot: hospital random effects"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqline</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/nlme/man/random.effects.html">ranef</a></span><span class="op">(</span><span class="va">fit_nested</span><span class="op">)</span><span class="op">$</span><span class="va">hospital</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04b-mixed-effects_files/figure-html/nested-diagnostics-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>A well-fitted mixed model should show approximately normal residuals <em>and</em> approximately normal random effects. The random effects Q-Q plot is often overlooked: it tests the normality assumption on the <span class="math inline">\(b_j\)</span> directly, not just on the observation-level residuals.</p>
</section><section id="testing-the-fixed-effect" class="level3" data-number="9.5.5"><h3 data-number="9.5.5" class="anchored" data-anchor-id="testing-the-fixed-effect">
<span class="header-section-number">9.5.5</span> Testing the Fixed Effect</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># F test with Satterthwaite degrees of freedom</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">fit_nested</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Type III Analysis of Variance Table with Satterthwaite's method
#&gt;           Sum Sq Mean Sq NumDF DenDF F value    Pr(&gt;F)    
#&gt; treatment 1368.2  1368.2     1   132   21.34 9.028e-06 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># F test with Kenward-Roger degrees of freedom (preferred for small n)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">fit_nested</span>, ddf <span class="op">=</span> <span class="st">"Kenward-Roger"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Type III Analysis of Variance Table with Kenward-Roger's method
#&gt;           Sum Sq Mean Sq NumDF  DenDF F value    Pr(&gt;F)    
#&gt; treatment 1367.9  1367.9     1 132.15  21.334 9.044e-06 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Both the Satterthwaite and Kenward-Roger F tests converge on the same conclusion, and the agreement between them is reassuring. The Satterthwaite test gives <span class="math inline">\(F_{1, 132.00} = 21.34\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>; the Kenward-Roger test gives <span class="math inline">\(F_{1, 132.15} = 21.33\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>. The two methods produce virtually identical results here because the dataset is reasonably large at the patient level (148 observations) and the design, while unbalanced, is not severely so. In a study with fewer patients or more extreme imbalance across hospitals and regions, the two methods would diverge more noticeably, and the Kenward-Roger result would be the more trustworthy of the two.</p>
<p>The denominator degrees of freedom (132) confirm what the summary output already showed: treatment is being tested at the patient level, where replication is adequate. This is the correct behaviour as the new protocol was randomised to individual patients, so the patient level is the right level at which to evaluate it.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Effect size: marginal and conditional R-squared</span></span>
<span><span class="co"># install.packages("MuMIn") if needed</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">MuMIn</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/MuMIn/man/r.squaredGLMM.html">r.squaredGLMM</a></span><span class="op">(</span><span class="va">fit_nested</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;             R2m      R2c
#&gt; [1,] 0.08885778 0.389217</code></pre>
</div>
</div>
<p><code><a href="https://rdrr.io/pkg/MuMIn/man/r.squaredGLMM.html">r.squaredGLMM()</a></code> returns two R² values for mixed models:</p>
<ul>
<li>
<strong>Marginal R²</strong> (<span class="math inline">\(R^2_m\)</span>): the proportion of variance explained by the fixed effects alone, here, the treatment effect.</li>
<li>
<strong>Conditional R²</strong> (<span class="math inline">\(R^2_c\)</span>): the proportion of variance explained by both fixed and random effects together which is the full model.</li>
</ul>
<p>The difference between them (<span class="math inline">\(R^2_c - R^2_m\)</span>) reflects how much of the total variation is attributable to the random effects, in this example it correspond to the hospital and region clustering structure.</p>
<p>In the example, the R² values from <code><a href="https://rdrr.io/pkg/MuMIn/man/r.squaredGLMM.html">r.squaredGLMM()</a></code> decompose the explained variance informatively. The marginal R² is <span class="math inline">\(R^2_m = 0.089\)</span>, meaning the treatment fixed effect alone explains approximately 9% of the total variation in recovery scores. The conditional R² is <span class="math inline">\(R^2_c = 0.389\)</span>, meaning the full model explains 39% of total variation. The difference, <span class="math inline">\(R^2_c - R^2_m = 0.300\)</span>, is the contribution of the hospital and region clustering structure: 30% of total variation is attributable to which hospital and region a patient belongs to, over and above the treatment effect. This is a striking reminder of why the random effects cannot be ignored: the clustering explains more than three times as much variation as the treatment itself, and failing to account for it would have produced severely misleading standard errors and p-values for the treatment comparison.</p>
</section><section id="comparing-nested-models" class="level3" data-number="9.5.6"><h3 data-number="9.5.6" class="anchored" data-anchor-id="comparing-nested-models">
<span class="header-section-number">9.5.6</span> Comparing Nested Models</h3>
<p>To formally test whether the random effects are necessary, whether hospital and region clustering is real, compare models with and without the random effects using likelihood ratio tests:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Fit models with ML for comparison of fixed effects</span></span>
<span><span class="va">fit_full</span> <span class="op">&lt;-</span> <span class="fu">lme4</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">recovery</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">region</span><span class="op">/</span><span class="va">hospital</span><span class="op">)</span>,</span>
<span>                       data <span class="op">=</span> <span class="va">physio</span>, REML <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">fit_no_h</span> <span class="op">&lt;-</span> <span class="fu">lme4</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">recovery</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">region</span><span class="op">)</span>,</span>
<span>                       data <span class="op">=</span> <span class="va">physio</span>, REML <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Is hospital-within-region variance significant?</span></span>
<span><span class="co"># Compare model with and without hospital-level random effect</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">fit_no_h</span>, <span class="va">fit_full</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Data: physio
#&gt; Models:
#&gt; fit_no_h: recovery ~ treatment + (1 | region)
#&gt; fit_full: recovery ~ treatment + (1 | region/hospital)
#&gt;          npar    AIC    BIC  logLik -2*log(L) Chisq Df Pr(&gt;Chisq)    
#&gt; fit_no_h    4 1085.1 1097.1 -538.56    1077.1                        
#&gt; fit_full    5 1068.8 1083.8 -529.40    1058.8 18.33  1  1.858e-05 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Is region variance significant?</span></span>
<span><span class="co"># Compare model with and without region-level random effect</span></span>
<span><span class="va">fit_no_r</span> <span class="op">&lt;-</span> <span class="fu">lme4</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">recovery</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">hospital</span><span class="op">)</span>,</span>
<span>                       data <span class="op">=</span> <span class="va">physio</span>, REML <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">fit_no_r</span>, <span class="va">fit_full</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Data: physio
#&gt; Models:
#&gt; fit_no_r: recovery ~ treatment + (1 | hospital)
#&gt; fit_full: recovery ~ treatment + (1 | region/hospital)
#&gt;          npar    AIC    BIC  logLik -2*log(L)  Chisq Df Pr(&gt;Chisq)
#&gt; fit_no_r    4 1067.1 1079.1 -529.57    1059.1                     
#&gt; fit_full    5 1068.8 1083.8 -529.40    1058.8 0.3455  1     0.5567</code></pre>
</div>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Alternative: ranova() tests each random effect term directly</span></span>
<span><span class="co"># without needing to refit models manually</span></span>
<span><span class="fu">lmerTest</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lmerTest/man/ranova.html">ranova</a></span><span class="op">(</span></span>
<span>  <span class="fu">lmerTest</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lmerTest/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">recovery</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">region</span><span class="op">/</span><span class="va">hospital</span><span class="op">)</span>,</span>
<span>                 data <span class="op">=</span> <span class="va">physio</span>, REML <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; ANOVA-like table for random-effects: Single term deletions
#&gt; 
#&gt; Model:
#&gt; recovery ~ treatment + (1 | hospital:region) + (1 | region)
#&gt;                       npar  logLik    AIC     LRT Df Pr(&gt;Chisq)    
#&gt; &lt;none&gt;                   5 -526.60 1063.2                          
#&gt; (1 | hospital:region)    4 -535.64 1079.3 18.0884  1  2.109e-05 ***
#&gt; (1 | region)             4 -527.04 1062.1  0.8802  1     0.3481    
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The model comparison results tell a nuanced but clear story about the necessity of each level of the random effects structure.</p>
<p>The hospital-within-region random effect is strongly supported by the data. Removing it significantly worsens the model fit (<span class="math inline">\(\chi^2_1 = 18.33\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>), and the AIC drops from 1085.1 to 1068.8 when hospital-level clustering is included. The 18 unit improvement in log-likelihood is substantial, the 15 hospitals differ from each other in their baseline recovery levels in ways that cannot be explained by region alone, and ignoring this hospital-level clustering would produce incorrect standard errors for the treatment comparison.</p>
<p>The region random effect, however, tells a different story. Removing it does not significantly worsen the fit (<span class="math inline">\(\chi^2_1 = 0.35\)</span>, <span class="math inline">\(p = 0.557\)</span>), and the AIC is actually slightly lower without it (1067.1 vs 1068.8). The <code><a href="https://rdrr.io/pkg/lmerTest/man/ranova.html">ranova()</a></code> output confirms this: the hospital-within-region term is highly significant (<span class="math inline">\(\chi^2_1 = 18.09\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>) while the region term is not (<span class="math inline">\(\chi^2_1 = 0.88\)</span>, <span class="math inline">\(p = 0.348\)</span>). With only 3 regions in the study, the region-level variance (<span class="math inline">\(\hat{\sigma}^2_{\text{region}} = 8.73\)</span>) is estimated from very sparse information and the likelihood ratio test has almost no power to detect it even if it is real. This is a common situation in hierarchical biological studies: the highest level of the hierarchy is almost always the most sparsely replicated, and non-significant tests for top-level random effects should be interpreted as reflecting limited power rather than genuine absence of region-level variation. In this case, retaining the region random effect is the scientifically conservative and appropriate choice. Indeed, the three regions were sampled from a larger population of regions and their variation should be accounted for regardless of the test result.</p>
</section><section id="reporting-the-result" class="level3" data-number="9.5.7"><h3 data-number="9.5.7" class="anchored" data-anchor-id="reporting-the-result">
<span class="header-section-number">9.5.7</span> Reporting the Result</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Final model refitted with REML for reporting</span></span>
<span><span class="va">fit_final</span> <span class="op">&lt;-</span> <span class="fu">lmerTest</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lmerTest/man/lmer.html">lmer</a></span><span class="op">(</span></span>
<span>  <span class="va">recovery</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">region</span><span class="op">/</span><span class="va">hospital</span><span class="op">)</span>,</span>
<span>  data <span class="op">=</span> <span class="va">physio</span>, REML <span class="op">=</span> <span class="cn">TRUE</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_final</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Linear mixed model fit by REML. t-tests use Satterthwaite's method [
#&gt; lmerModLmerTest]
#&gt; Formula: recovery ~ treatment + (1 | region/hospital)
#&gt;    Data: physio
#&gt; 
#&gt; REML criterion at convergence: 1053.2
#&gt; 
#&gt; Scaled residuals: 
#&gt;      Min       1Q   Median       3Q      Max 
#&gt; -3.07356 -0.62171  0.09592  0.59586  2.31967 
#&gt; 
#&gt; Random effects:
#&gt;  Groups          Name        Variance Std.Dev.
#&gt;  hospital:region (Intercept) 22.799   4.775   
#&gt;  region          (Intercept)  8.732   2.955   
#&gt;  Residual                    64.117   8.007   
#&gt; Number of obs: 148, groups:  hospital:region, 15; region, 3
#&gt; 
#&gt; Fixed effects:
#&gt;                    Estimate Std. Error      df t value Pr(&gt;|t|)    
#&gt; (Intercept)          61.329      2.294   2.351  26.740 0.000564 ***
#&gt; treatmentTreatment    6.097      1.320 132.003   4.619 9.03e-06 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; Correlation of Fixed Effects:
#&gt;             (Intr)
#&gt; trtmntTrtmn -0.272</code></pre>
</div>
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">fit_final</span>, ddf <span class="op">=</span> <span class="st">"Kenward-Roger"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Type III Analysis of Variance Table with Kenward-Roger's method
#&gt;           Sum Sq Mean Sq NumDF  DenDF F value    Pr(&gt;F)    
#&gt; treatment 1367.9  1367.9     1 132.15  21.334 9.044e-06 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/MuMIn/man/r.squaredGLMM.html">r.squaredGLMM</a></span><span class="op">(</span><span class="va">fit_final</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;             R2m      R2c
#&gt; [1,] 0.08885778 0.389217</code></pre>
</div>
</div>
<p>A complete report of the three-level nested analysis:</p>
<blockquote class="blockquote">
<p>Recovery scores following knee replacement surgery were analysed using a three-level linear mixed-effects model with treatment (control vs new physiotherapy protocol) as a fixed effect and random intercepts for hospital nested within region, fitted by REML using <code>lme4</code> version 1.x <span class="citation" data-cites="Bates2015">(<a href="#ref-Bates2015" role="doc-biblioref">Bates et al. 2015</a>)</span>. Degrees of freedom for fixed effect tests were approximated using the Kenward-Roger method <span class="citation" data-cites="Kenward1997">(<a href="#ref-Kenward1997" role="doc-biblioref">Kenward and Roger 1997</a>)</span> via <code>lmerTest</code> <span class="citation" data-cites="Kuznetsova2017">(<a href="#ref-Kuznetsova2017" role="doc-biblioref">Kuznetsova, Brockhoff, and Christensen 2017</a>)</span>.</p>
<p>The new physiotherapy protocol was associated with significantly higher recovery scores than the standard protocol (<span class="math inline">\(\beta = 6.10\)</span>, <span class="math inline">\(SE = 1.32\)</span>, <span class="math inline">\(F_{1, 132.15} = 21.33\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>). The marginal <span class="math inline">\(R^2\)</span> was 0.089, indicating that the treatment effect alone explained 9% of total variance in recovery scores. The conditional <span class="math inline">\(R^2\)</span> was 0.389, with the random effects accounting for an additional 30% of total variance, confirming that the hierarchical structure of the data (patients clustered within hospitals, hospitals clustered within regions) was a substantial source of variation that required explicit modelling.</p>
<p>Likelihood ratio tests confirmed significant variance at the hospital-within-region level (<span class="math inline">\(\chi^2_1 = 18.33\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>), with estimated hospital-level standard deviation of 4.78 recovery points. Region-level variance did not reach significance (<span class="math inline">\(\chi^2_1 = 0.35\)</span>, <span class="math inline">\(p = 0.557\)</span>), though with only three regions the test had limited power, and the region random effect was retained in the model on scientific grounds. Residual patient-level standard deviation was 8.01 recovery points.</p>
</blockquote>
</section></section><section id="sec-repeat-mixed" class="level2" data-number="9.6"><h2 data-number="9.6" class="anchored" data-anchor-id="sec-repeat-mixed">
<span class="header-section-number">9.6</span> Repeated Measures as a Mixed Model</h2>
<section id="the-connection-to-chapter-6" class="level3" data-number="9.6.1"><h3 data-number="9.6.1" class="anchored" data-anchor-id="the-connection-to-chapter-6">
<span class="header-section-number">9.6.1</span> The Connection to Chapter 6</h3>
<p>Chapter <a href="#sec-chap6" class="quarto-xref"><span class="quarto-unresolved-ref ref-noprefix">sec-chap6</span></a> analysed repeated measures data using <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> with an <code>Error()</code> term which is the classical approach that has been standard in biology for decades. That approach works well for balanced designs with complete data, but it has three important limitations that become apparent in practice: it cannot handle missing observations, it assumes a specific covariance structure (compound symmetry, closely related to sphericity), and it becomes unwieldy with more than two levels of nesting.</p>
<p>Mixed-effects models handle all three limitations naturally. And because the repeated measures model is already a mixed model in disguise, subjects are a random effect, time is a fixed effect, the transition requires no new conceptual machinery. It is simply a matter of fitting the same model with <code><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer()</a></code> instead of <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code>.</p>
</section><section id="refitting-the-clinical-example" class="level3" data-number="9.6.2"><h3 data-number="9.6.2" class="anchored" data-anchor-id="refitting-the-clinical-example">
<span class="header-section-number">9.6.2</span> Refitting the Clinical Example</h3>
<p>We return to the cardiac rehabilitation trial from Chapter 6: 40 patients (20 control, 20 intervention) measured at weeks 0, 4, 8, and 12 (<a href="#sec-cardiac-recovery" class="quarto-xref"><span class="quarto-unresolved-ref">sec-cardiac-recovery</span></a>). We first refit the classical repeated measures ANOVA, then refit the same model as a mixed-effects model, and compare the results directly.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/lme4/lme4/">lme4</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/runehaubo/lmerTestR">lmerTest</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Classical repeated measures ANOVA from Chapter 6</span></span>
<span><span class="va">fit_rm_classical</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span></span>
<span>  <span class="va">hr</span> <span class="op">~</span> <span class="va">group</span> <span class="op">*</span> <span class="va">time</span> <span class="op">+</span> <span class="fu">Error</span><span class="op">(</span><span class="va">subject</span><span class="op">/</span><span class="va">time</span><span class="op">)</span>,</span>
<span>  data <span class="op">=</span> <span class="va">cardiac_recovery</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_rm_classical</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt; Error: subject
#&gt;           Df Sum Sq Mean Sq F value   Pr(&gt;F)    
#&gt; group      1  883.3   883.3   19.09 9.29e-05 ***
#&gt; Residuals 38 1757.9    46.3                     
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; Error: subject:time
#&gt;             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
#&gt; time         3 1811.6   603.9   66.98  &lt; 2e-16 ***
#&gt; group:time   3  598.8   199.6   22.14 2.28e-11 ***
#&gt; Residuals  114 1027.7     9.0                     
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># The same model as a linear mixed-effects model</span></span>
<span><span class="co"># subject is the random effect; group and time are fixed</span></span>
<span><span class="va">fit_rm_mixed</span> <span class="op">&lt;-</span> <span class="fu">lmerTest</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lmerTest/man/lmer.html">lmer</a></span><span class="op">(</span></span>
<span>  <span class="va">hr</span> <span class="op">~</span> <span class="va">group</span> <span class="op">*</span> <span class="va">time</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">subject</span><span class="op">)</span>,</span>
<span>  data <span class="op">=</span> <span class="va">cardiac_recovery</span>,</span>
<span>  REML <span class="op">=</span> <span class="cn">TRUE</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_rm_mixed</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Linear mixed model fit by REML. t-tests use Satterthwaite's method [
#&gt; lmerModLmerTest]
#&gt; Formula: hr ~ group * time + (1 | subject)
#&gt;    Data: cardiac_recovery
#&gt; 
#&gt; REML criterion at convergence: 851.7
#&gt; 
#&gt; Scaled residuals: 
#&gt;      Min       1Q   Median       3Q      Max 
#&gt; -3.00986 -0.60094  0.06222  0.49595  2.85033 
#&gt; 
#&gt; Random effects:
#&gt;  Groups   Name        Variance Std.Dev.
#&gt;  subject  (Intercept) 9.311    3.051   
#&gt;  Residual             9.015    3.002   
#&gt; Number of obs: 160, groups:  subject, 40
#&gt; 
#&gt; Fixed effects:
#&gt;                          Estimate Std. Error       df t value Pr(&gt;|t|)    
#&gt; (Intercept)               80.9464     0.9572  85.6600  84.562  &lt; 2e-16 ***
#&gt; groupIntervention          0.2611     1.3537  85.6600   0.193  0.84752    
#&gt; time4                     -2.1052     0.9495 114.0000  -2.217  0.02859 *  
#&gt; time8                     -3.0179     0.9495 114.0000  -3.179  0.00191 ** 
#&gt; time12                    -3.9646     0.9495 114.0000  -4.176 5.84e-05 ***
#&gt; groupIntervention:time4   -2.5790     1.3428 114.0000  -1.921  0.05727 .  
#&gt; groupIntervention:time8   -7.4799     1.3428 114.0000  -5.571 1.72e-07 ***
#&gt; groupIntervention:time12  -9.7825     1.3428 114.0000  -7.285 4.48e-11 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; Correlation of Fixed Effects:
#&gt;             (Intr) grpInt time4  time8  time12 grpI:4 grpI:8
#&gt; grpIntrvntn -0.707                                          
#&gt; time4       -0.496  0.351                                   
#&gt; time8       -0.496  0.351  0.500                            
#&gt; time12      -0.496  0.351  0.500  0.500                     
#&gt; grpIntrvn:4  0.351 -0.496 -0.707 -0.354 -0.354              
#&gt; grpIntrvn:8  0.351 -0.496 -0.354 -0.707 -0.354  0.500       
#&gt; grpIntrv:12  0.351 -0.496 -0.354 -0.354 -0.707  0.500  0.500</code></pre>
</div>
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">fit_rm_mixed</span>, ddf <span class="op">=</span> <span class="st">"Satterthwaite"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Type III Analysis of Variance Table with Satterthwaite's method
#&gt;             Sum Sq Mean Sq NumDF DenDF F value    Pr(&gt;F)    
#&gt; group       172.14  172.14     1    38  19.095 9.292e-05 ***
#&gt; time       1811.55  603.85     3   114  66.983 &lt; 2.2e-16 ***
#&gt; group:time  598.77  199.59     3   114  22.140 2.280e-11 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>With complete, balanced data the two approaches give the same <span class="math inline">\(F\)</span> statistics, the same degrees of freedom, and the same p-values for every effect. This equivalence is not a coincidence: the <code>Error()</code> specification in <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> and the <code>(1 | subject)</code> random intercept in <code><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer()</a></code> are two syntaxes for the same statistical model. The subject random intercept absorbs the stable between-patient differences in heart rate, leaving the within-subject residual as the error term against which the time and group-by-time effects are tested which is exactly what the <code>Error(subject/time)</code> stratum does in the classical output.</p>
</section><section id="where-the-two-approaches-diverge" class="level3" data-number="9.6.3"><h3 data-number="9.6.3" class="anchored" data-anchor-id="where-the-two-approaches-diverge">
<span class="header-section-number">9.6.3</span> Where the Two Approaches Diverge</h3>
<p>The equivalence breaks down in three practically important situations.</p>
<p><strong>Missing data.</strong> <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> with <code>Error()</code> performs listwise deletion: any subject with a missing observation at any time point is excluded entirely from the analysis. <code><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer()</a></code> uses REML or ML estimation, which retains all available observations under the missing-at-random assumption. In a 12-week clinical trial where some patients miss appointments, this difference can be substantial.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb59"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Introduce missing data: remove 5 random observations</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">42</span><span class="op">)</span></span>
<span><span class="va">df_missing</span> <span class="op">&lt;-</span> <span class="va">cardiac_recovery</span></span>
<span><span class="va">missing_idx</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">df_missing</span><span class="op">)</span>, <span class="fl">5</span><span class="op">)</span></span>
<span><span class="va">df_missing</span><span class="op">$</span><span class="va">hr</span><span class="op">[</span><span class="va">missing_idx</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="cn">NA</span></span>
<span></span>
<span><span class="co"># Classical approach: drops entire subjects with any missing value</span></span>
<span><span class="va">fit_classical_miss</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span></span>
<span>  <span class="va">hr</span> <span class="op">~</span> <span class="va">group</span> <span class="op">*</span> <span class="va">time</span> <span class="op">+</span> <span class="fu">Error</span><span class="op">(</span><span class="va">subject</span><span class="op">/</span><span class="va">time</span><span class="op">)</span>,</span>
<span>  data <span class="op">=</span> <span class="va">df_missing</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Classical ANOVA, subjects retained:"</span>,</span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span></span>
<span>      <span class="va">df_missing</span><span class="op">$</span><span class="va">subject</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/stats/complete.cases.html">complete.cases</a></span><span class="op">(</span><span class="va">df_missing</span><span class="op">)</span><span class="op">]</span></span>
<span>    <span class="op">)</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Classical ANOVA, subjects retained: 40</code></pre>
</div>
<div class="sourceCode" id="cb61"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Mixed model: retains all subjects, uses all available observations</span></span>
<span><span class="va">fit_mixed_miss</span> <span class="op">&lt;-</span> <span class="fu">lmerTest</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lmerTest/man/lmer.html">lmer</a></span><span class="op">(</span></span>
<span>  <span class="va">hr</span> <span class="op">~</span> <span class="va">group</span> <span class="op">*</span> <span class="va">time</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">subject</span><span class="op">)</span>,</span>
<span>  data <span class="op">=</span> <span class="va">df_missing</span>,</span>
<span>  REML <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>  na.action <span class="op">=</span> <span class="va">na.omit</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Mixed model, observations used:"</span>, <span class="fu"><a href="https://rdrr.io/r/stats/nobs.html">nobs</a></span><span class="op">(</span><span class="va">fit_mixed_miss</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Mixed model, observations used: 155</code></pre>
</div>
</div>
<p><strong>Unequal time spacing.</strong> <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> treats the time factor as a nominal categorical variable making the spacing between time points is irrelevant. <code><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer()</a></code> can model time as a continuous variable, allowing the trajectory to be estimated as a smooth function (linear, quadratic, or piecewise) rather than a step function. This is more parsimonious and often more biologically sensible.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb63"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Group means per time point</span></span>
<span><span class="va">summ</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aggregate.html">aggregate</a></span><span class="op">(</span><span class="va">hr</span> <span class="op">~</span> <span class="va">group</span> <span class="op">+</span> <span class="va">time</span>, data <span class="op">=</span> <span class="va">cardiac_recovery</span>, FUN <span class="op">=</span> <span class="va">mean</span><span class="op">)</span></span>
<span><span class="va">summ</span><span class="op">$</span><span class="va">time_num</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="va">summ</span><span class="op">$</span><span class="va">time</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">cardiac_recovery</span><span class="op">$</span><span class="va">time_num</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="va">cardiac_recovery</span><span class="op">$</span><span class="va">time</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Model time as continuous, estimates a linear trajectory</span></span>
<span><span class="co"># rather than separate means at each time point</span></span>
<span><span class="va">fit_rm_linear</span> <span class="op">&lt;-</span> <span class="fu">lmerTest</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lmerTest/man/lmer.html">lmer</a></span><span class="op">(</span></span>
<span>  <span class="va">hr</span> <span class="op">~</span> <span class="va">group</span> <span class="op">*</span> <span class="va">time_num</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">subject</span><span class="op">)</span>,</span>
<span>  data <span class="op">=</span> <span class="va">cardiac_recovery</span>,</span>
<span>  REML <span class="op">=</span> <span class="cn">TRUE</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">fit_rm_linear</span>, ddf <span class="op">=</span> <span class="st">"Kenward-Roger"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Type III Analysis of Variance Table with Kenward-Roger's method
#&gt;                 Sum Sq Mean Sq NumDF   DenDF  F value    Pr(&gt;F)    
#&gt; group             1.10    1.10     1  66.583   0.1229     0.727    
#&gt; time_num       1791.70 1791.70     1 118.000 199.4800 &lt; 2.2e-16 ***
#&gt; group:time_num  586.47  586.47     1 118.000  65.2953 6.281e-13 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode" id="cb65"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Model time as continuous with random slope</span></span>
<span><span class="co"># allows each patient to have their own rate of change</span></span>
<span><span class="va">fit_rm_rslope</span> <span class="op">&lt;-</span> <span class="fu">lmerTest</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lmerTest/man/lmer.html">lmer</a></span><span class="op">(</span></span>
<span>  <span class="va">hr</span> <span class="op">~</span> <span class="va">group</span> <span class="op">*</span> <span class="va">time_num</span> <span class="op">+</span> <span class="op">(</span><span class="va">time_num</span> <span class="op">|</span> <span class="va">subject</span><span class="op">)</span>,</span>
<span>  data <span class="op">=</span> <span class="va">cardiac_recovery</span>,</span>
<span>  REML <span class="op">=</span> <span class="cn">TRUE</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">fit_rm_rslope</span>, ddf <span class="op">=</span> <span class="st">"Kenward-Roger"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Type III Analysis of Variance Table with Kenward-Roger's method
#&gt;                Sum Sq Mean Sq NumDF DenDF  F value    Pr(&gt;F)    
#&gt; group            0.91    0.91     1    38   0.1451    0.7054    
#&gt; time_num       762.91  762.91     1    38 121.8251 2.049e-13 ***
#&gt; group:time_num 249.72  249.72     1    38  39.8768 2.108e-07 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode" id="cb67"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Does the random slope improve fit?</span></span>
<span><span class="co"># Use ML for model comparison</span></span>
<span><span class="va">rm_linear_ml</span> <span class="op">&lt;-</span> <span class="fu">lme4</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span></span>
<span>  <span class="va">hr</span> <span class="op">~</span> <span class="va">group</span> <span class="op">*</span> <span class="va">time_num</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">subject</span><span class="op">)</span>,</span>
<span>  data <span class="op">=</span> <span class="va">cardiac_recovery</span>, REML <span class="op">=</span> <span class="cn">FALSE</span></span>
<span>  <span class="op">)</span></span>
<span><span class="va">rm_rslope_ml</span> <span class="op">&lt;-</span> <span class="fu">lme4</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span></span>
<span>  <span class="va">hr</span> <span class="op">~</span> <span class="va">group</span> <span class="op">*</span> <span class="va">time_num</span> <span class="op">+</span> <span class="op">(</span><span class="va">time_num</span> <span class="op">|</span> <span class="va">subject</span><span class="op">)</span>, </span>
<span>  data <span class="op">=</span> <span class="va">cardiac_recovery</span>, REML <span class="op">=</span> <span class="cn">FALSE</span></span>
<span>  <span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">rm_linear_ml</span>, <span class="va">rm_rslope_ml</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Data: cardiac_recovery
#&gt; Models:
#&gt; rm_linear_ml: hr ~ group * time_num + (1 | subject)
#&gt; rm_rslope_ml: hr ~ group * time_num + (time_num | subject)
#&gt;              npar    AIC    BIC  logLik -2*log(L)  Chisq Df Pr(&gt;Chisq)   
#&gt; rm_linear_ml    6 878.79 897.24 -433.39    866.79                        
#&gt; rm_rslope_ml    8 870.27 894.87 -427.14    854.27 12.517  2   0.001914 **
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The random slope model <code>(time_num | subject)</code> asks whether patients differ not only in their baseline heart rate (random intercept) but also in their <em>rate of recovery</em> (random slope). The significant improvement in fit when adding the random slope confirms that individual recovery trajectories genuinely differ. This is a clinically meaningful finding about treatment response heterogeneity that the classical repeated measures ANOVA cannot detect at all.</p>
<p><strong>Covariance structure.</strong> The classical repeated measures model assumes compound symmetry that is equal variances at every time point and equal correlations between every pair of time points. <code><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer()</a></code> with a simple random intercept implies the same structure. But more flexible covariance structures can be specified using <code>nlme</code>, which is worth knowing for situations where the compound symmetry assumption is clearly wrong:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb69"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://svn.r-project.org/R-packages/trunk/nlme/">nlme</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Compound symmetry (equivalent to random intercept in lmer)</span></span>
<span><span class="va">fit_cs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/nlme/man/lme.html">lme</a></span><span class="op">(</span><span class="va">hr</span> <span class="op">~</span> <span class="va">group</span> <span class="op">*</span> <span class="va">time</span>,</span>
<span>              random <span class="op">=</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">|</span> <span class="va">subject</span>,</span>
<span>              data <span class="op">=</span> <span class="va">cardiac_recovery</span>,</span>
<span>              method <span class="op">=</span> <span class="st">"REML"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Autoregressive AR(1): correlations decay with time distance</span></span>
<span><span class="co"># observations closer in time are more correlated than</span></span>
<span><span class="co"># observations further apart which is often more realistic biologically</span></span>
<span><span class="va">fit_ar1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/nlme/man/lme.html">lme</a></span><span class="op">(</span><span class="va">hr</span> <span class="op">~</span> <span class="va">group</span> <span class="op">*</span> <span class="va">time</span>,</span>
<span>               random    <span class="op">=</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">|</span> <span class="va">subject</span>,</span>
<span>               correlation <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/nlme/man/corAR1.html">corAR1</a></span><span class="op">(</span>form <span class="op">=</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">|</span> <span class="va">subject</span><span class="op">)</span>,</span>
<span>               data      <span class="op">=</span> <span class="va">cardiac_recovery</span>,</span>
<span>               method    <span class="op">=</span> <span class="st">"REML"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Compare covariance structures using AIC (refit with ML)</span></span>
<span><span class="va">fit_cs_ml</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/update.html">update</a></span><span class="op">(</span><span class="va">fit_cs</span>,   method <span class="op">=</span> <span class="st">"ML"</span><span class="op">)</span></span>
<span><span class="va">fit_ar1_ml</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/update.html">update</a></span><span class="op">(</span><span class="va">fit_ar1</span>, method <span class="op">=</span> <span class="st">"ML"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">fit_cs_ml</span>, <span class="va">fit_ar1_ml</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;            Model df      AIC      BIC    logLik   Test  L.Ratio p-value
#&gt; fit_cs_ml      1 10 883.0908 913.8426 -431.5454                        
#&gt; fit_ar1_ml     2 11 870.8304 904.6573 -424.4152 1 vs 2 14.26045   2e-04</code></pre>
</div>
</div>
<p>An AR(1) structure assumes that the correlation between two measurements decays exponentially with the time distance between them, for example measurements one week apart are more correlated than measurements four weeks apart. This is biologically plausible for most longitudinal physiological measurements and often fits better than the compound symmetry assumption imposed by the classical repeated measures model.</p>
</section><section id="a-practical-recommendation" class="level3" data-number="9.6.4"><h3 data-number="9.6.4" class="anchored" data-anchor-id="a-practical-recommendation">
<span class="header-section-number">9.6.4</span> A Practical Recommendation</h3>
<p>The decision between <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> and <code><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer()</a></code> for repeated measures data can be guided by a simple set of questions:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 34%">
<col style="width: 65%">
</colgroup>
<thead><tr class="header">
<th>Situation</th>
<th>Recommended approach</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Balanced design, complete data, simple structure</td>
<td>Either, results identical</td>
</tr>
<tr class="even">
<td>Missing observations</td>
<td>
<code><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer()</a></code> retains all available data</td>
</tr>
<tr class="odd">
<td>Unequally spaced time points</td>
<td>
<code><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer()</a></code> with continuous time</td>
</tr>
<tr class="even">
<td>Interest in individual trajectories</td>
<td>
<code><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer()</a></code> with random slopes</td>
</tr>
<tr class="odd">
<td>Non-compound-symmetry covariance</td>
<td>
<code>nlme</code> with explicit correlation structure</td>
</tr>
<tr class="even">
<td>Sphericity clearly violated</td>
<td>
<code><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer()</a></code> no sphericity assumption needed</td>
</tr>
</tbody>
</table>
<p>The broader message is the one that runs through this entire chapter: the classical ANOVA approach and the mixed-effects approach are not competing traditions: they are the same model expressed in different frameworks, with the mixed-effects framework being strictly more general. Mastering <code><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer()</a></code> does not replace what you learned in Chapter <a href="#sec-chap6" class="quarto-xref"><span class="quarto-unresolved-ref ref-noprefix">sec-chap6</span></a>; it extends it, and the extension becomes essential the moment your data depart from the idealised balanced, complete, compound-symmetric structure that classical repeated measures ANOVA requires.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Bates2015" class="csl-entry" role="listitem">
Bates, Douglas, Martin Mächler, Ben Bolker, and Steve Walker. 2015. <span>“Fitting <span>Linear Mixed-Effects Models Using</span> Lme4.”</span> <em>Journal of Statistical Software</em> 67 (October): 1–48. <a href="https://doi.org/10.18637/jss.v067.i01">https://doi.org/10.18637/jss.v067.i01</a>.
</div>
<div id="ref-Kenward1997" class="csl-entry" role="listitem">
Kenward, M. G., and J. H. Roger. 1997. <span>“<a href="https://www.ncbi.nlm.nih.gov/pubmed/9333350">Small Sample Inference for Fixed Effects from Restricted Maximum Likelihood</a>.”</span> <em>Biometrics</em> 53 (3): 983–97.
</div>
<div id="ref-Kuznetsova2017" class="csl-entry" role="listitem">
Kuznetsova, Alexandra, Per B. Brockhoff, and Rune H. B. Christensen. 2017. <span>“<span class="nocase">lmerTest Package</span>: <span>Tests</span> in <span>Linear Mixed Effects Models</span>.”</span> <em>Journal of Statistical Software</em> 82 (December): 1–26. <a href="https://doi.org/10.18637/jss.v082.i13">https://doi.org/10.18637/jss.v082.i13</a>.
</div>
<div id="ref-Pinheiro2000" class="csl-entry" role="listitem">
Pinheiro, J., and D. Bates. 2000. <em>Mixed-Effects Models in <span>S</span> and s-<span>PLUS</span></em>. Statistics and Computing. Springer New York.
</div>
<div id="ref-satterthwaite1946" class="csl-entry" role="listitem">
Satterthwaite, F. E. 1946. <span>“An <span>Approximate Distribution</span> of <span>Estimates</span> of <span>Variance Components</span>.”</span> <em>Biometrics Bulletin</em> 2 (6): 110–14. <a href="https://doi.org/10.2307/3002019">https://doi.org/10.2307/3002019</a>.
</div>
</div>
</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ebedthan\.github\.io\/maov\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./04a-anova-as-lm.html" class="pagination-link" aria-label="ANOVA as a Linear Model">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA as a Linear Model</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04c-when-assumptions-fail.html" class="pagination-link" aria-label="When Assumptions Fail, What to Do ?">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">When Assumptions Fail, What to Do ?</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Modern Analysis of Variance by Anicet Ebou.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Ebedthan/maov/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li><li><a href="https://github.com/Ebedthan/maov/edit/main/04b-mixed-effects.qmd" class="toc-action"><i class="bi empty"></i>Edit this page</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>