<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Anicet Ebou">
<title>6&nbsp; Repeated Measures ANOVA – Modern Analysis of Variance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03e-split-plot-nested.html" rel="next">
<link href="./03c-two-way.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03-classical-anova.html">Classical ANOVA Models</a></li><li class="breadcrumb-item"><a href="./03d-repeated-measures.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Repeated Measures ANOVA</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Modern Analysis of Variance</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Ebedthan/maov/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./02-foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02a-what-is-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What is ANOVA, Really ?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02b-assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Assumptions</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./03-classical-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Classical ANOVA Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03a-one-way.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">One-Way ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03b-multiple-comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Multiple Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03c-two-way.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Two-Way ANOVA and Factorial Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03d-repeated-measures.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Repeated Measures ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03e-split-plot-nested.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Split-Plot and Nested Designs</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./04-modern-framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Modern Framework</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04a-anova-as-lm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA as a Linear Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04b-mixed-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Mixed-Effects Models: Beyond Classical ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04c-when-assumptions-fail.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">When Assumptions Fail, What to Do ?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04d-glmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Generalised Linear Mixed Models</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./05-good-practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Good Practice and Reproductibility</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05a-experimental-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Experimental Design Principles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05b-reporting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Reporting ANOVA Results</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05c-reproducible-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Reproducible Analysis with R</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-a-math.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">The Maths of the Book</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-b-packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Datasets and R Packages</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-c-decision-tree.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Decision Trees for Model Selection</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#within-subject-designs-rationale-and-structure" id="toc-within-subject-designs-rationale-and-structure" class="nav-link active" data-scroll-target="#within-subject-designs-rationale-and-structure"><span class="header-section-number">6.1</span> Within-Subject Designs: Rationale and Structure</a>
  <ul class="collapse">
<li><a href="#the-logic-of-repeated-measures" id="toc-the-logic-of-repeated-measures" class="nav-link" data-scroll-target="#the-logic-of-repeated-measures"><span class="header-section-number">6.1.1</span> The Logic of Repeated Measures</a></li>
  <li><a href="#the-design-structure" id="toc-the-design-structure" class="nav-link" data-scroll-target="#the-design-structure"><span class="header-section-number">6.1.2</span> The Design Structure</a></li>
  <li><a href="#between-subjects-vs-within-subjects-factors" id="toc-between-subjects-vs-within-subjects-factors" class="nav-link" data-scroll-target="#between-subjects-vs-within-subjects-factors"><span class="header-section-number">6.1.3</span> Between-Subjects vs Within-Subjects Factors</a></li>
  <li><a href="#when-to-use-repeated-measures-anova" id="toc-when-to-use-repeated-measures-anova" class="nav-link" data-scroll-target="#when-to-use-repeated-measures-anova"><span class="header-section-number">6.1.4</span> When to Use Repeated Measures ANOVA</a></li>
  </ul>
</li>
  <li>
<a href="#sec-sphericity" id="toc-sec-sphericity" class="nav-link" data-scroll-target="#sec-sphericity"><span class="header-section-number">6.2</span> Sphericity: The Forgotten Assumption</a>
  <ul class="collapse">
<li><a href="#what-is-sphericity" id="toc-what-is-sphericity" class="nav-link" data-scroll-target="#what-is-sphericity"><span class="header-section-number">6.2.1</span> What Is Sphericity?</a></li>
  <li><a href="#why-does-violation-matter" id="toc-why-does-violation-matter" class="nav-link" data-scroll-target="#why-does-violation-matter"><span class="header-section-number">6.2.2</span> Why Does Violation Matter?</a></li>
  <li><a href="#mauchlys-test" id="toc-mauchlys-test" class="nav-link" data-scroll-target="#mauchlys-test"><span class="header-section-number">6.2.3</span> Mauchly’s Test</a></li>
  <li><a href="#varepsilon-corrections" id="toc-varepsilon-corrections" class="nav-link" data-scroll-target="#varepsilon-corrections"><span class="header-section-number">6.2.4</span> <span class="math inline">\(\varepsilon\)</span> Corrections</a></li>
  </ul>
</li>
  <li>
<a href="#one-way-and-two-way-repeated-measures-in-r" id="toc-one-way-and-two-way-repeated-measures-in-r" class="nav-link" data-scroll-target="#one-way-and-two-way-repeated-measures-in-r"><span class="header-section-number">6.3</span> One-Way and Two-Way Repeated Measures in R</a>
  <ul class="collapse">
<li><a href="#one-way-repeated-measures" id="toc-one-way-repeated-measures" class="nav-link" data-scroll-target="#one-way-repeated-measures"><span class="header-section-number">6.3.1</span> One-Way Repeated Measures</a></li>
  <li><a href="#two-way-repeated-measures-mixed-design" id="toc-two-way-repeated-measures-mixed-design" class="nav-link" data-scroll-target="#two-way-repeated-measures-mixed-design"><span class="header-section-number">6.3.2</span> Two-Way Repeated Measures (Mixed Design)</a></li>
  </ul>
</li>
  <li>
<a href="#example-longitudinal-measurements-in-clinical-biology" id="toc-example-longitudinal-measurements-in-clinical-biology" class="nav-link" data-scroll-target="#example-longitudinal-measurements-in-clinical-biology"><span class="header-section-number">6.4</span> Example: Longitudinal Measurements in Clinical Biology</a>
  <ul class="collapse">
<li><a href="#the-study" id="toc-the-study" class="nav-link" data-scroll-target="#the-study"><span class="header-section-number">6.4.1</span> The Study</a></li>
  <li><a href="#visualising-the-data" id="toc-visualising-the-data" class="nav-link" data-scroll-target="#visualising-the-data"><span class="header-section-number">6.4.2</span> Visualising the Data</a></li>
  <li><a href="#checking-sphericity" id="toc-checking-sphericity" class="nav-link" data-scroll-target="#checking-sphericity"><span class="header-section-number">6.4.3</span> Checking Sphericity</a></li>
  <li><a href="#fitting-the-model-and-interpreting-results" id="toc-fitting-the-model-and-interpreting-results" class="nav-link" data-scroll-target="#fitting-the-model-and-interpreting-results"><span class="header-section-number">6.4.4</span> Fitting the Model and Interpreting Results</a></li>
  <li><a href="#effect-sizes-and-reporting" id="toc-effect-sizes-and-reporting" class="nav-link" data-scroll-target="#effect-sizes-and-reporting"><span class="header-section-number">6.4.5</span> Effect Sizes and Reporting</a></li>
  <li><a href="#a-note-on-missing-data" id="toc-a-note-on-missing-data" class="nav-link" data-scroll-target="#a-note-on-missing-data"><span class="header-section-number">6.4.6</span> A Note on Missing Data</a></li>
  </ul>
</li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/Ebedthan/maov/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li><li><a href="https://github.com/Ebedthan/maov/edit/main/03d-repeated-measures.qmd" class="toc-action"><i class="bi empty"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03-classical-anova.html">Classical ANOVA Models</a></li><li class="breadcrumb-item"><a href="./03d-repeated-measures.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Repeated Measures ANOVA</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-chap6" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Repeated Measures ANOVA</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>In every design considered so far, each experimental unit, each plant, each patient, each plot, contributed a single observation to the analysis. The treatment groups were independent: knowing the yield of one plant told you nothing about the yield of any other. This is the between-subjects, or independent groups, structure that one-way and two-way ANOVA are built for.</p>
<p>Many biological questions, however, require measuring the same individual repeatedly. How does a patient’s blood pressure change over eight weeks of treatment? How does a mouse’s body weight evolve across a dietary intervention? How does soil respiration in a plot respond to successive rainfall events? In all of these cases, the observations are not independent. Measurements taken on the same individual at different time points will resemble each other more than measurements taken from different individuals, simply because individuals differ from one another in stable, persistent ways.</p>
<p><em>Repeated measures ANOVA</em> is designed for exactly this structure. It acknowledges that the same individual is measured multiple times, explicitly models the between-individual variation, and in doing so gains considerable statistical power compared to a between-subjects design of the same total size. It also introduces a new assumption, <em>sphericity</em>, that is frequently violated and even more frequently ignored.</p>
<section id="within-subject-designs-rationale-and-structure" class="level2" data-number="6.1"><h2 data-number="6.1" class="anchored" data-anchor-id="within-subject-designs-rationale-and-structure">
<span class="header-section-number">6.1</span> Within-Subject Designs: Rationale and Structure</h2>
<section id="the-logic-of-repeated-measures" class="level3" data-number="6.1.1"><h3 data-number="6.1.1" class="anchored" data-anchor-id="the-logic-of-repeated-measures">
<span class="header-section-number">6.1.1</span> The Logic of Repeated Measures</h3>
<p>The fundamental advantage of a repeated measures design is that <strong>each individual serves as their own control</strong>.</p>
<p>Consider measuring blood pressure at four time points in 20 patients. The total variation in the data has two sources: variation <em>between</em> patients (some people have naturally higher blood pressure than others, regardless of treatment) and variation <em>within</em> patients over time (the change in each person’s blood pressure across the four measurements).</p>
<p>Between-subjects ANOVA cannot separate these two sources, it pools them into the error term. Repeated measures ANOVA partitions them explicitly. The between-patient variation is removed from the error term and accounted for separately, leaving a much smaller residual against which the within-subject effect of time is tested. This is why repeated measures designs are statistically efficient: the between-subject noise that would otherwise obscure the treatment effect is factored out entirely.</p>
<p>This efficiency comes with a responsibility: <strong>the non-independence of repeated observations must be modelled correctly, not ignored</strong>.</p>
</section><section id="the-design-structure" class="level3" data-number="6.1.2"><h3 data-number="6.1.2" class="anchored" data-anchor-id="the-design-structure">
<span class="header-section-number">6.1.2</span> The Design Structure</h3>
<p>In a one-way repeated measures design, <span class="math inline">\(n\)</span> subjects each provide measurements under all <span class="math inline">\(k\)</span> conditions (or at all <span class="math inline">\(k\)</span> time points). The design can be represented as a two-way table with subjects as rows and conditions as columns, where every cell contains exactly one observation:</p>
<table class="caption-top table">
<thead><tr class="header">
<th>Subject</th>
<th style="text-align: center;">Time 1</th>
<th style="text-align: center;">Time 2</th>
<th style="text-align: center;">Time 3</th>
<th style="text-align: center;">Time 4</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>1</td>
<td style="text-align: center;"><span class="math inline">\(y_{11}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{12}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{13}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{14}\)</span></td>
</tr>
<tr class="even">
<td>2</td>
<td style="text-align: center;"><span class="math inline">\(y_{21}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{22}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{23}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{24}\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(n\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{n1}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{n2}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{n3}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{n4}\)</span></td>
</tr>
</tbody>
</table>
<p>The statistical model is:</p>
<p><span class="math display">\[y_{ij} = \mu + \alpha_i + \pi_j + \varepsilon_{ij}\]</span></p>
<p>where <span class="math inline">\(\alpha_i\)</span> is the effect of condition <span class="math inline">\(i\)</span> (the within-subject factor), <span class="math inline">\(\pi_j\)</span> is the effect of subject <span class="math inline">\(j\)</span> (the between-subject random effect, capturing stable individual differences), and <span class="math inline">\(\varepsilon_{ij}\)</span> is the residual. The key point is that <span class="math inline">\(\pi_j\)</span> is estimated and removed before testing <span class="math inline">\(\alpha_i\)</span>: this is the partitioning that gives repeated measures its power advantage.</p>
</section><section id="between-subjects-vs-within-subjects-factors" class="level3" data-number="6.1.3"><h3 data-number="6.1.3" class="anchored" data-anchor-id="between-subjects-vs-within-subjects-factors">
<span class="header-section-number">6.1.3</span> Between-Subjects vs Within-Subjects Factors</h3>
<p>Not all factors in a repeated measures design need to be within-subject. In a <strong>mixed design</strong> (not to be confused with mixed-effects models, though the connection is real), some factors are between-subjects and some are within-subjects. For example:</p>
<ul>
<li>
<strong>Between-subjects factor:</strong> treatment group (patients are assigned to either drug or placebo, they cannot be in both).</li>
<li>
<strong>Within-subjects factor:</strong> time (all patients are measured at baseline, week 4, and week 8).</li>
</ul>
<p>This is the most common structure in clinical biology: a treatment group factor (between) crossed with a time factor (within). The analysis produces three tests: the main effect of group, the main effect of time, and the group-by-time interaction, the last being typically the most scientifically interesting, as it tests whether the trajectory of change over time differs between treatment groups.</p>
</section><section id="when-to-use-repeated-measures-anova" class="level3" data-number="6.1.4"><h3 data-number="6.1.4" class="anchored" data-anchor-id="when-to-use-repeated-measures-anova">
<span class="header-section-number">6.1.4</span> When to Use Repeated Measures ANOVA</h3>
<p>Repeated measures ANOVA is appropriate when:</p>
<ul>
<li>The same individual is measured at multiple time points or under multiple conditions.</li>
<li>The order of conditions is either randomised (crossover design) or irrelevant to the research question (longitudinal time course).</li>
<li>The number of repeated measurements is modest (roughly 2-6). With many time points, linear mixed models (Chapter <a href="#sec-chap9" class="quarto-xref"><span class="quarto-unresolved-ref ref-noprefix">sec-chap9</span></a>) are more flexible and generally preferable.</li>
<li>The assumption of sphericity (Section <a href="#sec-sphericity" class="quarto-xref"><span class="quarto-unresolved-ref ref-noprefix">sec-sphericity</span></a>) is either satisfied or corrected for.</li>
</ul>
<p>It is <strong>not</strong> appropriate when:</p>
<ul>
<li>The repeated measurements are pseudoreplicates: multiple measurements of the same individual that were never intended to capture genuine within-individual change (see Section <a href="#sec-pseudoreplication" class="quarto-xref"><span class="quarto-unresolved-ref ref-noprefix">sec-pseudoreplication</span></a>).</li>
<li>The dropout rate is substantial: repeated measures ANOVA requires complete data, and list-wise deletion of incomplete cases can introduce serious bias. Mixed models handle missing data more gracefully.</li>
</ul></section></section><section id="sec-sphericity" class="level2" data-number="6.2"><h2 data-number="6.2" class="anchored" data-anchor-id="sec-sphericity">
<span class="header-section-number">6.2</span> Sphericity: The Forgotten Assumption</h2>
<section id="what-is-sphericity" class="level3" data-number="6.2.1"><h3 data-number="6.2.1" class="anchored" data-anchor-id="what-is-sphericity">
<span class="header-section-number">6.2.1</span> What Is Sphericity?</h3>
<p><em>Sphericity</em> is the assumption specific to repeated measures ANOVA, and it is the one most routinely overlooked. Understanding it requires first understanding what the repeated measures F test is actually doing.</p>
<p>In a between-subjects one-way ANOVA, the single error term, <span class="math inline">\(MS_{\text{within}}\)</span>, is appropriate because all observations in the same group were collected independently, and the variance is assumed equal across groups (homoscedasticity). In repeated measures ANOVA, the single within-subject error term is appropriate only if a stronger condition holds: not only must the variances of the repeated measurements be equal across time points, but the <strong>covariances</strong> between every pair of time points must also be equal.</p>
<p>More precisely, the assumption requires that the variance of the <em>differences</em> between every pair of time points is the same. If you have four time points, there are <span class="math inline">\(\binom{4}{2} = 6\)</span> pairwise differences, and sphericity requires all six to have equal variance.</p>
<p>This is called the <strong>sphericity assumption</strong> (also known as the Huynh-Feldt condition), and it is a generalisation of the compound symmetry assumption. Compound symmetry, equal variances and equal covariances everywhere, implies sphericity, but sphericity is weaker: it can hold even when compound symmetry does not.</p>
</section><section id="why-does-violation-matter" class="level3" data-number="6.2.2"><h3 data-number="6.2.2" class="anchored" data-anchor-id="why-does-violation-matter">
<span class="header-section-number">6.2.2</span> Why Does Violation Matter?</h3>
<p>When sphericity is violated, the F test in repeated measures ANOVA becomes positively biased: it produces too many significant results. The degrees of freedom used to construct the reference F distribution are inflated, making the test anti-conservative. The simulation below demonstrates this:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://future.futureverse.org">future</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/futureverse/furrr">furrr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://purrr.tidyverse.org/">purrr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://future.futureverse.org/reference/plan.html">plan</a></span><span class="op">(</span><span class="va">multisession</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">42</span><span class="op">)</span></span>
<span><span class="va">n_sim</span> <span class="op">&lt;-</span> <span class="fl">5000</span></span>
<span><span class="va">alpha</span> <span class="op">&lt;-</span> <span class="fl">0.05</span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fl">20</span>    <span class="co"># subjects</span></span>
<span><span class="va">k</span> <span class="op">&lt;-</span> <span class="fl">4</span>     <span class="co"># time points</span></span>
<span></span>
<span><span class="co"># Function to simulate one dataset and return p-value</span></span>
<span><span class="co"># from standard repeated measures ANOVA (via aov with Error term)</span></span>
<span></span>
<span><span class="va">run_rm_anova</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">sigma_matrix</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://www.stats.ox.ac.uk/pub/MASS4/">MASS</a></span><span class="op">)</span></span>
<span>  <span class="co"># Simulate data with given covariance structure</span></span>
<span>  <span class="va">Y</span>     <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/MASS/man/mvrnorm.html">mvrnorm</a></span><span class="op">(</span><span class="va">n</span>, mu <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0</span>, <span class="va">k</span><span class="op">)</span>, Sigma <span class="op">=</span> <span class="va">sigma_matrix</span><span class="op">)</span></span>
<span>  <span class="va">df_long</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>    y       <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/vector.html">as.vector</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">Y</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    subject <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="va">n</span>, each <span class="op">=</span> <span class="va">k</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    time    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="va">k</span>, <span class="va">n</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span>  <span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">time</span> <span class="op">+</span> <span class="fu">Error</span><span class="op">(</span><span class="va">subject</span><span class="op">/</span><span class="va">time</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">df_long</span><span class="op">)</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit</span><span class="op">)</span><span class="op">$</span><span class="va">`Error: subject:time`</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">[[</span><span class="st">"Pr(&gt;F)"</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="co"># Sphericity satisfied: compound symmetry</span></span>
<span><span class="va">sigma_cs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">0.5</span>, <span class="va">k</span>, <span class="va">k</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="va">sigma_cs</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fl">1</span></span>
<span></span>
<span><span class="co"># Sphericity violated: variance increases with time</span></span>
<span><span class="va">sigma_het</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">4</span>, <span class="fl">8</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">sigma_het</span><span class="op">[</span><span class="va">sigma_het</span> <span class="op">==</span> <span class="fl">0</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fl">0.5</span></span>
<span></span>
<span><span class="va">p_sphere</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://furrr.futureverse.org/reference/future_map.html">future_map_dbl</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="va">n_sim</span><span class="op">)</span>, <span class="op">~</span><span class="fu">run_rm_anova</span><span class="op">(</span><span class="va">sigma_cs</span><span class="op">)</span>, .options <span class="op">=</span> <span class="fu"><a href="https://furrr.futureverse.org/reference/furrr_options.html">furrr_options</a></span><span class="op">(</span>seed <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p_nospher</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://furrr.futureverse.org/reference/future_map.html">future_map_dbl</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="va">n_sim</span><span class="op">)</span>, <span class="op">~</span><span class="fu">run_rm_anova</span><span class="op">(</span><span class="va">sigma_het</span><span class="op">)</span>, .options <span class="op">=</span> <span class="fu"><a href="https://furrr.futureverse.org/reference/furrr_options.html">furrr_options</a></span><span class="op">(</span>seed <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://future.futureverse.org/reference/plan.html">plan</a></span><span class="op">(</span><span class="va">sequential</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span></span>
<span>  <span class="st">"False positive rate (sphericity satisfied):"</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">p_sphere</span>  <span class="op">&lt;</span> <span class="va">alpha</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span>,</span>
<span>  <span class="st">"\nFalse positive rate (sphericity violated):"</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">p_nospher</span> <span class="op">&lt;</span> <span class="va">alpha</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">"\n"</span></span>
<span>  <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; False positive rate (sphericity satisfied): 0.047 
#&gt; False positive rate (sphericity violated): 0.078</code></pre>
</div>
</div>
<p>The false positive rate under sphericity violation is above 5%, confirming that the standard <span class="math inline">\(F\)</span> test cannot be trusted when the assumption fails.</p>
</section><section id="mauchlys-test" class="level3" data-number="6.2.3"><h3 data-number="6.2.3" class="anchored" data-anchor-id="mauchlys-test">
<span class="header-section-number">6.2.3</span> Mauchly’s Test</h3>
<p>Mauchly’s test is the standard formal test of the sphericity assumption. It tests the null hypothesis that the variance-covariance matrix of the repeated measurements has the sphericity property.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Mauchly's test is produced automatically by summary()</span></span>
<span><span class="co"># when using the idata / mauchly argument in car::Anova</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/bprice2652/car_repo">car</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Fit the model as a multivariate linear model first</span></span>
<span><span class="co"># (required for Mauchly's test via car)</span></span>
<span><span class="va">fit_mlm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">t1</span>, <span class="va">t2</span>, <span class="va">t3</span>, <span class="va">t4</span><span class="op">)</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">df_wide</span><span class="op">)</span></span>
<span><span class="va">idata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>time <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="va">k</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">rm_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span><span class="op">(</span><span class="va">fit_mlm</span>, idata <span class="op">=</span> <span class="va">idata</span>, idesign <span class="op">=</span> <span class="op">~</span> <span class="va">time</span>, type <span class="op">=</span> <span class="st">"III"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">rm_model</span>, multivariate <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="co"># Mauchly's test and epsilon corrections appear automatically</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mauchly’s test shares the same sample-size sensitivity as the Shapiro-Wilk and Levene tests discussed in Chapter 2. With small samples it has low power to detect real violations; with large samples it will flag trivially small departures. As always, the test result should inform your judgement rather than make the decision for you. With <span class="math inline">\(k \geq 3\)</span> time points and any doubt about sphericity, apply the corrections described below regardless of the Mauchly test outcome.</p>
</section><section id="varepsilon-corrections" class="level3" data-number="6.2.4"><h3 data-number="6.2.4" class="anchored" data-anchor-id="varepsilon-corrections">
<span class="header-section-number">6.2.4</span> <span class="math inline">\(\varepsilon\)</span> Corrections</h3>
<p>When sphericity is violated, or when you cannot confidently rule out a violation, the appropriate response is to adjust the degrees of freedom of the F test using an <strong>epsilon (<span class="math inline">\(\varepsilon\)</span>) correction</strong>. The correction factor <span class="math inline">\(\varepsilon\)</span> (<span class="math inline">\(0 &lt; \varepsilon \leq 1\)</span>) measures the degree of departure from sphericity: <span class="math inline">\(\varepsilon = 1\)</span> means perfect sphericity; smaller values indicate greater violation.</p>
<p>The corrected degrees of freedom are:</p>
<p><span class="math display">\[df_1^* = \varepsilon(k-1) \qquad df_2^* = \varepsilon(k-1)(n-1)\]</span></p>
<p>Two estimators of <span class="math inline">\(\varepsilon\)</span> are in common use.</p>
<p><strong>Greenhouse-Geisser (<span class="math inline">\(\hat{\varepsilon}_{GG}\)</span>):</strong> a conservative estimator that can be very low when sphericity is badly violated. It tends to overcorrect with small samples, making the test too conservative.</p>
<p><strong>Huynh-Feldt (<span class="math inline">\(\tilde{\varepsilon}_{HF}\)</span>):</strong> a less conservative estimator that performs better in small to moderate samples. It is capped at 1: if the estimate exceeds 1, it is set to 1.</p>
<p>The conventional guidance is:</p>
<ul>
<li>If <span class="math inline">\(\hat{\varepsilon}_{GG} &gt; 0.75\)</span>: use Huynh-Feldt.</li>
<li>If <span class="math inline">\(\hat{\varepsilon}_{GG} \leq 0.75\)</span>: use Greenhouse-Geisser.</li>
<li>If <span class="math inline">\(\hat{\varepsilon}_{GG}\)</span> is very low (&lt; 0.5): consider a multivariate approach (MANOVA) or a linear mixed model instead.</li>
</ul>
<p>Both corrections are produced automatically by <code><a href="https://rdrr.io/pkg/car/man/Anova.html">car::Anova()</a></code> with the <code>multivariate = FALSE</code> option, as shown in the example below.</p>
</section></section><section id="one-way-and-two-way-repeated-measures-in-r" class="level2" data-number="6.3"><h2 data-number="6.3" class="anchored" data-anchor-id="one-way-and-two-way-repeated-measures-in-r">
<span class="header-section-number">6.3</span> One-Way and Two-Way Repeated Measures in R</h2>
<section id="one-way-repeated-measures" class="level3" data-number="6.3.1"><h3 data-number="6.3.1" class="anchored" data-anchor-id="one-way-repeated-measures">
<span class="header-section-number">6.3.1</span> One-Way Repeated Measures</h3>
<p>The simplest case: one within-subject factor (e.g.&nbsp;time) and no between-subject factor. In base R, the <code>Error()</code> term in <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> specifies the within-subject structure:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Long format required</span></span>
<span><span class="co"># subject: factor identifying each individual</span></span>
<span><span class="co"># time:    within-subject factor</span></span>
<span><span class="co"># y:       response variable</span></span>
<span></span>
<span><span class="va">fit_rm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">time</span> <span class="op">+</span> <span class="fu">Error</span><span class="op">(</span><span class="va">subject</span><span class="op">/</span><span class="va">time</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">df_long</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_rm</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For Mauchly’s test and epsilon corrections, the <code>car</code> package approach is more complete:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/bprice2652/car_repo">car</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Reshape to wide format for car::Anova</span></span>
<span><span class="co"># Each row is one subject; columns are time points</span></span>
<span><span class="va">fit_mlm</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">t1</span>, <span class="va">t2</span>, <span class="va">t3</span>, <span class="va">t4</span><span class="op">)</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">df_wide</span><span class="op">)</span></span>
<span><span class="va">idata</span>    <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>time <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">4</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">rm_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span><span class="op">(</span><span class="va">fit_mlm</span>,</span>
<span>                  idata   <span class="op">=</span> <span class="va">idata</span>,</span>
<span>                  idesign <span class="op">=</span> <span class="op">~</span> <span class="va">time</span>,</span>
<span>                  type    <span class="op">=</span> <span class="st">"III"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Full output including Mauchly's test and epsilon corrections</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">rm_model</span>, multivariate <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="two-way-repeated-measures-mixed-design" class="level3" data-number="6.3.2"><h3 data-number="6.3.2" class="anchored" data-anchor-id="two-way-repeated-measures-mixed-design">
<span class="header-section-number">6.3.2</span> Two-Way Repeated Measures (Mixed Design)</h3>
<p>The most common design in clinical biology: one between-subjects factor (group) and one within-subjects factor (time):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># group: between-subjects factor (different patients in each group)</span></span>
<span><span class="co"># time: within-subjects factor (all patients measured at each time)</span></span>
<span><span class="co"># subject: factor identifying each individual</span></span>
<span></span>
<span><span class="va">fit_mixed</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">group</span> <span class="op">*</span> <span class="va">time</span> <span class="op">+</span> <span class="fu">Error</span><span class="op">(</span><span class="va">subject</span><span class="op">/</span><span class="va">time</span><span class="op">)</span>,</span>
<span>                 data <span class="op">=</span> <span class="va">df_long</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_mixed</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For the <code>car</code> approach with epsilon corrections in a mixed design:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/bprice2652/car_repo">car</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit_mlm2</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">t1</span>, <span class="va">t2</span>, <span class="va">t3</span>, <span class="va">t4</span><span class="op">)</span> <span class="op">~</span> <span class="va">group</span>, data <span class="op">=</span> <span class="va">df_wide</span><span class="op">)</span></span>
<span><span class="va">idata</span>     <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>time <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">4</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">rm_model2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span><span class="op">(</span><span class="va">fit_mlm2</span>,</span>
<span>                   idata   <span class="op">=</span> <span class="va">idata</span>,</span>
<span>                   idesign <span class="op">=</span> <span class="op">~</span> <span class="va">time</span>,</span>
<span>                   type    <span class="op">=</span> <span class="st">"III"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">rm_model2</span>, multivariate <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section></section><section id="example-longitudinal-measurements-in-clinical-biology" class="level2" data-number="6.4"><h2 data-number="6.4" class="anchored" data-anchor-id="example-longitudinal-measurements-in-clinical-biology">
<span class="header-section-number">6.4</span> Example: Longitudinal Measurements in Clinical Biology</h2>
<section id="the-study" class="level3" data-number="6.4.1"><h3 data-number="6.4.1" class="anchored" data-anchor-id="the-study">
<span class="header-section-number">6.4.1</span> The Study</h3>
<p>A clinical trial follows 40 patients recovering from cardiac surgery. Twenty patients are randomly assigned to a standard rehabilitation programme (<code>group</code> level <code>Control</code>) and twenty to an intensive cardiac rehabilitation programme (<code>group</code> level <code>Intervention</code>) (<a href="#sec-cardiac-recovery" class="quarto-xref"><span class="quarto-unresolved-ref">sec-cardiac-recovery</span></a>). Resting heart rate (<code>hr</code>, beats per minute) is measured at four time points (<code>time</code>): baseline (week 0), week 4, week 8, and week 12. The primary question is whether the two groups differ in their trajectory of heart rate reduction over the 12-week period that is, whether there is a group-by-time interaction.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">cardiac_recovery</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;     subject             group    time          hr              id       
#&gt;  1      :  4   Control     :80   0 :40   Min.   :58.80   Min.   : 1.00  
#&gt;  2      :  4   Intervention:80   4 :40   1st Qu.:71.66   1st Qu.:10.75  
#&gt;  3      :  4                     8 :40   Median :77.09   Median :20.50  
#&gt;  4      :  4                     12:40   Mean   :76.32   Mean   :20.50  
#&gt;  5      :  4                             3rd Qu.:80.38   3rd Qu.:30.25  
#&gt;  6      :  4                             Max.   :93.61   Max.   :40.00  
#&gt;  (Other):136</code></pre>
</div>
</div>
</section><section id="visualising-the-data" class="level3" data-number="6.4.2"><h3 data-number="6.4.2" class="anchored" data-anchor-id="visualising-the-data">
<span class="header-section-number">6.4.2</span> Visualising the Data</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Group means per time point</span></span>
<span><span class="va">summ</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aggregate.html">aggregate</a></span><span class="op">(</span><span class="va">hr</span> <span class="op">~</span> <span class="va">group</span> <span class="op">+</span> <span class="va">time</span>, data <span class="op">=</span> <span class="va">cardiac_recovery</span>, FUN <span class="op">=</span> <span class="va">mean</span><span class="op">)</span></span>
<span><span class="va">summ</span><span class="op">$</span><span class="va">time_num</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="va">summ</span><span class="op">$</span><span class="va">time</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">cardiac_recovery</span><span class="op">$</span><span class="va">time_num</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="va">cardiac_recovery</span><span class="op">$</span><span class="va">time</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Individual trajectories</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">cardiac_recovery</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">time_num</span>, y <span class="op">=</span> <span class="va">hr</span>, group <span class="op">=</span> <span class="va">subject</span>, colour <span class="op">=</span> <span class="va">group</span><span class="op">)</span>, alpha <span class="op">=</span> <span class="fl">0.2</span>, linewidth <span class="op">=</span> <span class="fl">0.4</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Group mean trajectories</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">summ</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">time_num</span>, y <span class="op">=</span> <span class="va">hr</span>, colour <span class="op">=</span> <span class="va">group</span>, group <span class="op">=</span> <span class="va">group</span><span class="op">)</span>, linewidth <span class="op">=</span> <span class="fl">1.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">summ</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">time_num</span>, y <span class="op">=</span> <span class="va">hr</span>, colour <span class="op">=</span> <span class="va">group</span><span class="op">)</span>, size <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#2E86AB"</span>, <span class="st">"#E84855"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">4</span>, <span class="fl">8</span>, <span class="fl">12</span><span class="op">)</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"Week "</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">4</span>, <span class="fl">8</span>, <span class="fl">12</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="cn">NULL</span>, y <span class="op">=</span> <span class="st">"Resting heart rate (bpm)"</span>, colour <span class="op">=</span> <span class="st">"Group"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"inside"</span>, legend.position.inside <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.85</span>, <span class="fl">0.85</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-rm-plot" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-rm-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03d-repeated-measures_files/figure-html/fig-rm-plot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rm-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: Mean resting heart rate trajectories for control and intervention groups across four time points. Thin lines show individual patient trajectories; thick lines connect group means. The intervention group shows a steeper and more sustained decline in heart rate from week 4 onward, suggesting a group-by-time interaction. The parallel trajectories at baseline confirm that the two groups were comparable at the start of the trial.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="checking-sphericity" class="level3" data-number="6.4.3"><h3 data-number="6.4.3" class="anchored" data-anchor-id="checking-sphericity">
<span class="header-section-number">6.4.3</span> Checking Sphericity</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/bprice2652/car_repo">car</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># car::Anova requires wide format with group as a between-subjects predictor</span></span>
<span><span class="va">fit_mlm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">t1</span>, <span class="va">t2</span>, <span class="va">t3</span>, <span class="va">t4</span><span class="op">)</span> <span class="op">~</span> <span class="va">group</span>, data <span class="op">=</span> <span class="va">cardiac_recovery_wide</span><span class="op">)</span></span>
<span><span class="va">idata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>time <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"t1"</span>, <span class="st">"t2"</span>, <span class="st">"t3"</span>, <span class="st">"t4"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">rm_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span><span class="op">(</span><span class="va">fit_mlm</span>, idata <span class="op">=</span> <span class="va">idata</span>, idesign <span class="op">=</span> <span class="op">~</span> <span class="va">time</span>, type <span class="op">=</span> <span class="st">"III"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Full output: Mauchly's test + epsilon corrections + F tests</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">rm_model</span>, multivariate <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt; Univariate Type III Repeated-Measures ANOVA Assuming Sphericity
#&gt; 
#&gt;             Sum Sq num Df Error SS den Df    F value    Pr(&gt;F)    
#&gt; (Intercept) 495174      1   1757.9     38 10704.0589 &lt; 2.2e-16 ***
#&gt; group          883      1   1757.9     38    19.0945 9.292e-05 ***
#&gt; time           172      3   1027.7    114     6.3681  0.000498 ***
#&gt; group:time     599      3   1027.7    114    22.1398 2.280e-11 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; 
#&gt; Mauchly Tests for Sphericity
#&gt; 
#&gt;            Test statistic p-value
#&gt; time              0.67608 0.01343
#&gt; group:time        0.67608 0.01343
#&gt; 
#&gt; 
#&gt; Greenhouse-Geisser and Huynh-Feldt Corrections
#&gt;  for Departure from Sphericity
#&gt; 
#&gt;             GG eps Pr(&gt;F[GG])    
#&gt; time       0.80607   0.001348 ** 
#&gt; group:time 0.80607  1.377e-09 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt;              HF eps   Pr(&gt;F[HF])
#&gt; time       0.864768 9.960634e-04
#&gt; group:time 0.864768 3.972709e-10</code></pre>
</div>
</div>
<p>Mauchly’s test is significant (<span class="math inline">\(W = 0.676\)</span>, <span class="math inline">\(p = 0.013\)</span>), indicating that the sphericity assumption is violated. The variances of the pairwise differences between time points are not equal across all combinations, which means the standard F test degrees of freedom are inflated and uncorrected p-values cannot be trusted.</p>
<p>The Greenhouse-Geisser estimate is <span class="math inline">\(\hat{\varepsilon}_{GG} = 0.806\)</span>. Since this exceeds the 0.75 threshold, the Huynh-Feldt correction is preferred over the more conservative Greenhouse-Geisser. The Huynh-Feldt estimate is <span class="math inline">\(\tilde{\varepsilon}_{HF} = 0.865\)</span>, reasonably close to 1, indicating that the departure from sphericity is moderate rather than severe. We therefore use the Huynh-Feldt corrected p-values for all within-subject tests.</p>
<p>The corrected ANOVA table tells a clear story. The group-by-time interaction is highly significant (<span class="math inline">\(F_{2.59, 98.6} = 22.14\)</span>, <span class="math inline">\(p = 3.97 \times 10^{-10}\)</span>, using Huynh-Feldt corrected degrees of freedom), confirming that the two rehabilitation programmes produce different heart rate trajectories over the 12-week period. This is the primary finding of the study. The main effect of time is also significant (<span class="math inline">\(F_{2.59, 98.6} = 6.37\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>), indicating that heart rate declines over the course of rehabilitation when averaged across both groups. The main effect of group is significant as well (<span class="math inline">\(F_{1, 38} = 19.09\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>), though as noted earlier this averages over a trajectory that differs between groups and should not be interpreted in isolation from the interaction.</p>
<p>Two things are worth noting for students reading this output for the first time. First, the uncorrected p-values (assuming sphericity) and the corrected p-values tell the same qualitative story here: all three effects remain highly significant after correction. This is because the violation is moderate (<span class="math inline">\(\tilde{\varepsilon}_{HF} = 0.865\)</span>) rather than severe. With a more serious violation, the correction can shift a borderline result from significant to non-significant, which is precisely why it must not be skipped. Second, the degrees of freedom in the corrected tests are no longer whole numbers, they are <span class="math inline">\(\hat{\varepsilon} \times df_{\text{uncorrected}}\)</span>. This is not a typographical error; it is the mathematical consequence of the epsilon adjustment and is entirely normal in repeated measures output.</p>
</section><section id="fitting-the-model-and-interpreting-results" class="level3" data-number="6.4.4"><h3 data-number="6.4.4" class="anchored" data-anchor-id="fitting-the-model-and-interpreting-results">
<span class="header-section-number">6.4.4</span> Fitting the Model and Interpreting Results</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Base R aov() approach for the ANOVA table</span></span>
<span><span class="va">fit_rm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">hr</span> <span class="op">~</span> <span class="va">group</span> <span class="op">*</span> <span class="va">time</span> <span class="op">+</span> <span class="fu">Error</span><span class="op">(</span><span class="va">subject</span><span class="op">/</span><span class="va">time</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">cardiac_recovery</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_rm</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt; Error: subject
#&gt;           Df Sum Sq Mean Sq F value   Pr(&gt;F)    
#&gt; group      1  883.3   883.3   19.09 9.29e-05 ***
#&gt; Residuals 38 1757.9    46.3                     
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; Error: subject:time
#&gt;             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
#&gt; time         3 1811.6   603.9   66.98  &lt; 2e-16 ***
#&gt; group:time   3  598.8   199.6   22.14 2.28e-11 ***
#&gt; Residuals  114 1027.7     9.0                     
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The output is split into two error strata, which is the defining structural feature of repeated measures ANOVA output in R and the first thing students need to learn to read correctly.</p>
<p>The <strong><code>Error: subject</code> stratum</strong> captures the between-subjects variation i.e.&nbsp;differences among individuals that persist across all time points. It contains the test for the between-subjects factor <code>group</code>. The intervention group differs significantly from the control group in its overall mean heart rate (<span class="math inline">\(F_{1,38} = 19.09\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>), but as discussed above, this average difference collapsed across all four time points is not the primary question. The residual mean square in this stratum (46.3 bpm²) estimates the stable between-patient variance: the variation in baseline heart rate that exists among individuals regardless of which programme they followed.</p>
<p>The <strong><code>Error: subject:time</code> stratum</strong> captures the within-subjects variation i.e.&nbsp;how each individual’s heart rate changes across time points. It contains the tests for the within-subjects factor <code>time</code> and the <code>group:time</code> interaction. The residual mean square here (9.0 bpm²) is dramatically smaller than the between-subjects residual (46.3 bpm²), illustrating concretely the power advantage of repeated measures designs: the stable individual differences that would inflate the error term in a between-subjects design have been partitioned out, leaving a much smaller noise floor against which the within-subjects effects are tested.</p>
<p>The main effect of time is highly significant (<span class="math inline">\(F_{3,114} = 66.98\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>), confirming that heart rate declines substantially over the 12-week rehabilitation period when averaged across both groups. This is not surprising, indeed rehabilitation of any kind is expected to improve cardiovascular fitness, but it is a necessary finding that validates the study’s measurement protocol.</p>
<p>Most importantly, the group-by-time interaction is highly significant (<span class="math inline">\(F_{3,114} = 22.14\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>). This is the central result: the trajectory of heart rate change over 12 weeks differs between the two rehabilitation programmes. The intensive programme produces a steeper and more sustained decline in resting heart rate than the standard programme, and this difference cannot be attributed to chance. Note that these are the uncorrected degrees of freedom, since Mauchly’s test was significant, the Huynh-Feldt corrected p-values from <code><a href="https://rdrr.io/pkg/car/man/Anova.html">car::Anova()</a></code> should be reported, which remain highly significant (<span class="math inline">\(p = 3.97 \times 10^{-10}\)</span>) and lead to the same conclusion.</p>
<p>It is also worth noting the ratio of the two residual mean squares. The between-subjects residual (46.3 bpm²) is more than five times larger than the within-subjects residual (9.0 bpm²). This tells us that individuals differ substantially from one another in their baseline heart rate, but that within any given individual the measurement-to-measurement variation is much smaller. This is exactly the pattern that makes repeated measures designs efficient: by tracking individuals over time rather than comparing independent groups, we are testing the treatment effect against within-person variability rather than between-person variability, gaining statistical sensitivity as a direct consequence.</p>
</section><section id="effect-sizes-and-reporting" class="level3" data-number="6.4.5"><h3 data-number="6.4.5" class="anchored" data-anchor-id="effect-sizes-and-reporting">
<span class="header-section-number">6.4.5</span> Effect Sizes and Reporting</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://easystats.github.io/effectsize/">effectsize</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://easystats.github.io/effectsize/reference/eta_squared.html">eta_squared</a></span><span class="op">(</span><span class="va">fit_rm</span>, partial <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # Effect Size for ANOVA (Type I)
#&gt; 
#&gt; Group        |  Parameter | Eta2 (partial) |       95% CI
#&gt; ---------------------------------------------------------
#&gt; subject      |      group |           0.33 | [0.14, 1.00]
#&gt; subject:time |       time |           0.64 | [0.55, 1.00]
#&gt; subject:time | group:time |           0.37 | [0.25, 1.00]
#&gt; 
#&gt; - One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<p>The partial <span class="math inline">\(\eta^2\)</span> values reveal the relative importance of each effect in the model. Time explains the largest share of within-subject variance (partial <span class="math inline">\(\eta^2 = 0.64\)</span>, 95% CI <span class="math inline">\([0.55, 1.00]\)</span>), indicating that 64% of the within-subject variation in heart rate is accounted for by the progression across the 12 weeks which is a large effect by any standard, reflecting the genuine and consistent improvement in cardiovascular fitness that rehabilitation produces regardless of programme type.</p>
<p>The group-by-time interaction has a partial <span class="math inline">\(\eta^2 = 0.37\)</span> (95% CI <span class="math inline">\([0.25, 1.00]\)</span>), a large effect indicating that 37% of the within-subject variance not explained by time alone is attributable to the differential trajectory of the two groups. This is the scientifically meaningful result: not only does heart rate improve over time, but it improves substantially more, and more rapidly, in the intensive rehabilitation group than in the control group.</p>
<p>The between-subjects effect of group has a partial <span class="math inline">\(\eta^2 = 0.33\)</span> (95% CI <span class="math inline">\([0.14, 1.00]\)</span>), indicating that 33% of the stable between-patient variance is explained by group membership. This reflects the sustained overall difference in heart rate between the two groups when averaged across all time points.</p>
<p>A note on the confidence intervals: all upper bounds are fixed at 1.00, which is expected for one-sided confidence intervals on <span class="math inline">\(\eta^2\)</span> as the parameter is bounded above by 1 by definition. The lower bounds are the more informative values, confirming that even at the conservative end of the interval, all three effects are meaningfully large.</p>
<p>The complete report of this analysis reads:</p>
<blockquote class="blockquote">
<p>A two-way mixed repeated measures ANOVA examined the effect of rehabilitation programme (between-subjects: control vs intervention, <span class="math inline">\(n = 20\)</span> per group) and time (within-subjects: weeks 0, 4, 8, 12) on resting heart rate. Mauchly’s test indicated a significant violation of sphericity (<span class="math inline">\(W = 0.676\)</span>, <span class="math inline">\(p = 0.013\)</span>); Huynh-Feldt corrected degrees of freedom were therefore applied to all within-subjects tests (<span class="math inline">\(\tilde{\varepsilon}_{HF} = 0.865\)</span>). A highly significant group-by-time interaction was found (<span class="math inline">\(F_{2.59, 98.6} = 22.14\)</span>, <span class="math inline">\(p = 3.97 \times 10^{-10}\)</span>, partial <span class="math inline">\(\eta^2 = 0.37\)</span>), indicating that the intensive rehabilitation programme produced a steeper decline in resting heart rate over the 12-week period than the standard programme. A significant main effect of time confirmed that heart rate declined across the study period in both groups (<span class="math inline">\(F_{2.59, 98.6} = 6.37\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>, partial <span class="math inline">\(\eta^2 = 0.64\)</span>). The main effect of group was also significant (<span class="math inline">\(F_{1, 38} = 19.09\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>, partial <span class="math inline">\(\eta^2 = 0.33\)</span>), reflecting the overall lower mean heart rate in the intervention group across all time points. These results support the conclusion that intensive cardiac rehabilitation produces clinically meaningful improvements in resting heart rate beyond those achieved by standard care alone.</p>
</blockquote>
</section><section id="a-note-on-missing-data" class="level3" data-number="6.4.6"><h3 data-number="6.4.6" class="anchored" data-anchor-id="a-note-on-missing-data">
<span class="header-section-number">6.4.6</span> A Note on Missing Data</h3>
<p>Repeated measures ANOVA as implemented in <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> and <code><a href="https://rdrr.io/pkg/car/man/Anova.html">car::Anova()</a></code> requires complete data: every subject must have a measurement at every time point. If any observations are missing, the subject is excluded entirely from the analysis. In a 12-week clinical trial, dropout is almost inevitable: patients move, recover, or withdraw consent.</p>
<p>When missing data are present, the appropriate tool is a <strong>linear mixed-effects model</strong> (Chapter 9), which can handle incomplete longitudinal data under the assumption that missingness is random (the missing-at-random assumption). The mixed model fitted to complete data will give identical results to repeated measures ANOVA in the balanced case, confirming that repeated measures ANOVA is simply a special case of the linear mixed model, a theme that runs throughout Part III of this book.</p>


</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ebedthan\.github\.io\/maov\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./03c-two-way.html" class="pagination-link" aria-label="Two-Way ANOVA and Factorial Designs">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Two-Way ANOVA and Factorial Designs</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./03e-split-plot-nested.html" class="pagination-link" aria-label="Split-Plot and Nested Designs">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Split-Plot and Nested Designs</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Modern Analysis of Variance by Anicet Ebou.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Ebedthan/maov/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li><li><a href="https://github.com/Ebedthan/maov/edit/main/03d-repeated-measures.qmd" class="toc-action"><i class="bi empty"></i>Edit this page</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>