<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Anicet Ebou">
<title>7&nbsp; Split-Plot and Nested Designs – Modern Analysis of Variance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04-modern-framework.html" rel="next">
<link href="./03d-repeated-measures.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="site_libs/quarto-diagram/mermaid.min.js"></script><script src="site_libs/quarto-diagram/mermaid-init.js"></script><link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03-classical-anova.html">Classical ANOVA Models</a></li><li class="breadcrumb-item"><a href="./03e-split-plot-nested.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Split-Plot and Nested Designs</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Modern Analysis of Variance</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Ebedthan/maov/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./02-foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02a-what-is-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What is ANOVA, Really ?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02b-assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Assumptions</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./03-classical-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Classical ANOVA Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03a-one-way.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">One-Way ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03b-multiple-comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Multiple Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03c-two-way.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Two-Way ANOVA and Factorial Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03d-repeated-measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Repeated Measures ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03e-split-plot-nested.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Split-Plot and Nested Designs</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./04-modern-framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Modern Framework</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04a-anova-as-lm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA as a Linear Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04b-mixed-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Mixed-Effects Models: Beyond Classical ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04c-when-assumptions-fail.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">When Assumptions Fail, What to Do ?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04d-glmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Generalised Linear Mixed Models</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./05-good-practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Good Practice and Reproductibility</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05a-experimental-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Experimental Design Principles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05b-reporting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Reporting ANOVA Results</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05c-reproducible-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Reproducible Analysis</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-a-math.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">The Maths of the Book</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-b-packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Datasets and R Packages</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-c-decision-tree.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Decision Trees for Model Selection</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#hierarchy-in-biological-data-why-it-cannot-be-ignored" id="toc-hierarchy-in-biological-data-why-it-cannot-be-ignored" class="nav-link active" data-scroll-target="#hierarchy-in-biological-data-why-it-cannot-be-ignored"><span class="header-section-number">7.1</span> Hierarchy in Biological Data: Why It Cannot Be Ignored</a>
  <ul class="collapse">
<li><a href="#everything-is-nested-in-something" id="toc-everything-is-nested-in-something" class="nav-link" data-scroll-target="#everything-is-nested-in-something"><span class="header-section-number">7.1.1</span> Everything Is Nested in Something</a></li>
  <li><a href="#what-goes-wrong-when-you-ignore-the-hierarchy" id="toc-what-goes-wrong-when-you-ignore-the-hierarchy" class="nav-link" data-scroll-target="#what-goes-wrong-when-you-ignore-the-hierarchy"><span class="header-section-number">7.1.2</span> What Goes Wrong When You Ignore the Hierarchy</a></li>
  <li><a href="#visualising-the-hierarchy" id="toc-visualising-the-hierarchy" class="nav-link" data-scroll-target="#visualising-the-hierarchy"><span class="header-section-number">7.1.3</span> Visualising the Hierarchy</a></li>
  <li><a href="#the-golden-rule-of-hierarchical-analysis" id="toc-the-golden-rule-of-hierarchical-analysis" class="nav-link" data-scroll-target="#the-golden-rule-of-hierarchical-analysis"><span class="header-section-number">7.1.4</span> The Golden Rule of Hierarchical Analysis</a></li>
  </ul>
</li>
  <li>
<a href="#sec-pseudoreplication2" id="toc-sec-pseudoreplication2" class="nav-link" data-scroll-target="#sec-pseudoreplication2"><span class="header-section-number">7.2</span> Pseudoreplication: The Silent Epidemic in Biology</a>
  <ul class="collapse">
<li><a href="#a-pervasive-problem" id="toc-a-pervasive-problem" class="nav-link" data-scroll-target="#a-pervasive-problem"><span class="header-section-number">7.2.1</span> A Pervasive Problem</a></li>
  <li><a href="#how-to-avoid-it" id="toc-how-to-avoid-it" class="nav-link" data-scroll-target="#how-to-avoid-it"><span class="header-section-number">7.2.2</span> How to Avoid It</a></li>
  </ul>
</li>
  <li>
<a href="#split-plot-design-structure-and-correct-error-terms" id="toc-split-plot-design-structure-and-correct-error-terms" class="nav-link" data-scroll-target="#split-plot-design-structure-and-correct-error-terms"><span class="header-section-number">7.3</span> Split-Plot Design: Structure and Correct Error Terms</a>
  <ul class="collapse">
<li><a href="#when-does-a-split-plot-design-arise" id="toc-when-does-a-split-plot-design-arise" class="nav-link" data-scroll-target="#when-does-a-split-plot-design-arise"><span class="header-section-number">7.3.1</span> When Does a Split-Plot Design Arise?</a></li>
  <li><a href="#structure-of-the-split-plot-design" id="toc-structure-of-the-split-plot-design" class="nav-link" data-scroll-target="#structure-of-the-split-plot-design"><span class="header-section-number">7.3.2</span> Structure of the Split-Plot Design</a></li>
  <li><a href="#the-split-plot-model" id="toc-the-split-plot-model" class="nav-link" data-scroll-target="#the-split-plot-model"><span class="header-section-number">7.3.3</span> The Split-Plot Model</a></li>
  </ul>
</li>
  <li>
<a href="#nested-anova-subsampling-vs-true-replication" id="toc-nested-anova-subsampling-vs-true-replication" class="nav-link" data-scroll-target="#nested-anova-subsampling-vs-true-replication"><span class="header-section-number">7.4</span> Nested ANOVA: Subsampling vs True Replication</a>
  <ul class="collapse">
<li><a href="#the-nested-structure" id="toc-the-nested-structure" class="nav-link" data-scroll-target="#the-nested-structure"><span class="header-section-number">7.4.1</span> The Nested Structure</a></li>
  <li><a href="#subsampling-vs-true-replication" id="toc-subsampling-vs-true-replication" class="nav-link" data-scroll-target="#subsampling-vs-true-replication"><span class="header-section-number">7.4.2</span> Subsampling vs True Replication</a></li>
  </ul>
</li>
  <li>
<a href="#example-1-grazing-effects-on-plant-diversity" id="toc-example-1-grazing-effects-on-plant-diversity" class="nav-link" data-scroll-target="#example-1-grazing-effects-on-plant-diversity"><span class="header-section-number">7.5</span> Example 1: Grazing Effects on Plant Diversity</a>
  <ul class="collapse">
<li><a href="#the-study" id="toc-the-study" class="nav-link" data-scroll-target="#the-study"><span class="header-section-number">7.5.1</span> The Study</a></li>
  <li><a href="#correct-analysis-paddock-as-the-error-term" id="toc-correct-analysis-paddock-as-the-error-term" class="nav-link" data-scroll-target="#correct-analysis-paddock-as-the-error-term"><span class="header-section-number">7.5.2</span> Correct Analysis: Paddock as the Error Term</a></li>
  <li><a href="#what-happens-if-you-ignore-the-nesting" id="toc-what-happens-if-you-ignore-the-nesting" class="nav-link" data-scroll-target="#what-happens-if-you-ignore-the-nesting"><span class="header-section-number">7.5.3</span> What Happens if You Ignore the Nesting</a></li>
  </ul>
</li>
  <li>
<a href="#example-2-irrigation-and-fertiliser-in-a-split-plot-design" id="toc-example-2-irrigation-and-fertiliser-in-a-split-plot-design" class="nav-link" data-scroll-target="#example-2-irrigation-and-fertiliser-in-a-split-plot-design"><span class="header-section-number">7.6</span> Example 2: Irrigation and Fertiliser in a Split-Plot Design</a>
  <ul class="collapse">
<li><a href="#the-study-1" id="toc-the-study-1" class="nav-link" data-scroll-target="#the-study-1"><span class="header-section-number">7.6.1</span> The Study</a></li>
  <li><a href="#fitting-the-split-plot-model" id="toc-fitting-the-split-plot-model" class="nav-link" data-scroll-target="#fitting-the-split-plot-model"><span class="header-section-number">7.6.2</span> Fitting the Split-Plot Model</a></li>
  <li><a href="#visualising-the-results" id="toc-visualising-the-results" class="nav-link" data-scroll-target="#visualising-the-results"><span class="header-section-number">7.6.3</span> Visualising the Results</a></li>
  <li><a href="#why-the-split-plot-analysis-matters" id="toc-why-the-split-plot-analysis-matters" class="nav-link" data-scroll-target="#why-the-split-plot-analysis-matters"><span class="header-section-number">7.6.4</span> Why the Split-Plot Analysis Matters</a></li>
  </ul>
</li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/Ebedthan/maov/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li><li><a href="https://github.com/Ebedthan/maov/edit/main/03e-split-plot-nested.qmd" class="toc-action"><i class="bi empty"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03-classical-anova.html">Classical ANOVA Models</a></li><li class="breadcrumb-item"><a href="./03e-split-plot-nested.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Split-Plot and Nested Designs</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-chap7" class="quarto-section-identifier"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Split-Plot and Nested Designs</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>Every ANOVA design considered so far has shared a common simplifying assumption: that the experimental units receiving different treatments are all of the same type, at the same level of organisation, and subject to the same sources of variation. A plant is a plant, a patient is a patient, a plot is a plot.</p>
<p>Biological reality is rarely so flat. Ecosystems are organised in layers: individual organisms live within plots, plots within fields, fields within regions. Clinical trials recruit patients from hospitals, hospitals from healthcare systems. Agricultural experiments apply whole-farm treatments to fields and within-field treatments to plots. In all of these cases, the experimental units exist at multiple levels of a hierarchy, and treatments are applied, and therefore replicated, at different levels of that hierarchy.</p>
<p>Ignoring this hierarchical structure leads directly to the pseudoreplication problem introduced in Chapter 2. Accounting for it correctly requires designs and analyses that explicitly represent the nested structure of the data. This chapter introduces the two most important such designs in biological research: the split-plot and the nested ANOVA.</p>
<section id="hierarchy-in-biological-data-why-it-cannot-be-ignored" class="level2" data-number="7.1"><h2 data-number="7.1" class="anchored" data-anchor-id="hierarchy-in-biological-data-why-it-cannot-be-ignored">
<span class="header-section-number">7.1</span> Hierarchy in Biological Data: Why It Cannot Be Ignored</h2>
<section id="everything-is-nested-in-something" class="level3" data-number="7.1.1"><h3 data-number="7.1.1" class="anchored" data-anchor-id="everything-is-nested-in-something">
<span class="header-section-number">7.1.1</span> Everything Is Nested in Something</h3>
<p>Before introducing any new design, it is worth pausing to build a clear intuition for what hierarchical structure means and why it demands special treatment.</p>
<p>Consider a simple example. A researcher wants to study the effect of two soil treatments (amended vs unamended) and two plant varieties (A vs B) on crop yield. She has access to four large fields. Two fields receive the soil amendment; two do not. Within each field, she establishes four plots: two planted with Variety A and two with Variety B. She measures yield from five plants within each plot.</p>
<p>The data have three levels of organisation:</p>
<p><span class="math display">\[\text{Field} \supset \text{Plot} \supset \text{Plant}\]</span></p>
<p>This is a hierarchy. Fields are nested within soil treatment. Plots are nested within fields. Plants are nested within plots. Each level has its own sources of variation: fields differ from each other in ways that have nothing to do with soil treatment (drainage, history, microclimate); plots within a field differ from each other in ways that have nothing to do with variety (position, local soil variation); plants within a plot differ from each other due to individual biological variation.</p>
<p>The critical point is that <strong>the treatment is applied and replicated at the field level, not the plot level and not the plant level.</strong> The soil amendment was not randomly assigned to individual plants: <em>it was assigned to whole fields</em>. The field is therefore the unit of replication for the soil treatment comparison, and there are only two replicates per treatment (<span class="math inline">\(n = 2\)</span> fields per treatment), not <span class="math inline">\(2 \times 4 \times 5 = 40\)</span>.</p>
</section><section id="what-goes-wrong-when-you-ignore-the-hierarchy" class="level3" data-number="7.1.2"><h3 data-number="7.1.2" class="anchored" data-anchor-id="what-goes-wrong-when-you-ignore-the-hierarchy">
<span class="header-section-number">7.1.2</span> What Goes Wrong When You Ignore the Hierarchy</h3>
<p>If the researcher analyses this experiment by running a standard ANOVA on all <span class="math inline">\(4 \times 4 \times 5 = 80\)</span> plant measurements, treating each plant as an independent observation, she is pseudoreplicating at two levels simultaneously. The within-field and within-plot correlation structures are ignored, and the error term used to test the soil treatment effect is the plant-level residual, which is far too small, because it does not account for the field-to-field variation that is the appropriate noise against which the treatment should be judged.</p>
<p>The simulation below demonstrates the inflation of the false positive rate that results:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://future.futureverse.org">future</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/futureverse/furrr">furrr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://purrr.tidyverse.org/">purrr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://future.futureverse.org/reference/plan.html">plan</a></span><span class="op">(</span><span class="va">multisession</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">42</span><span class="op">)</span></span>
<span><span class="va">n_sim</span> <span class="op">&lt;-</span> <span class="fl">5000</span></span>
<span><span class="va">alpha</span> <span class="op">&lt;-</span> <span class="fl">0.05</span></span>
<span><span class="va">n_fields</span> <span class="op">&lt;-</span> <span class="fl">4</span>      <span class="co"># 2 per treatment</span></span>
<span><span class="va">n_plots</span> <span class="op">&lt;-</span> <span class="fl">4</span>      <span class="co"># per field</span></span>
<span><span class="va">n_plants</span> <span class="op">&lt;-</span> <span class="fl">5</span>      <span class="co"># per plot</span></span>
<span><span class="va">field_sd</span> <span class="op">&lt;-</span> <span class="fl">3</span>      <span class="co"># field-to-field variation</span></span>
<span><span class="va">plot_sd</span> <span class="op">&lt;-</span> <span class="fl">2</span>      <span class="co"># plot-to-plot variation within field</span></span>
<span><span class="va">plant_sd</span> <span class="op">&lt;-</span> <span class="fl">1</span>      <span class="co"># plant-to-plant variation within plot</span></span>
<span></span>
<span><span class="va">results</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://furrr.futureverse.org/reference/future_map.html">future_map_dfr</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="va">n_sim</span><span class="op">)</span>, <span class="kw">function</span><span class="op">(</span><span class="va">i</span><span class="op">)</span> <span class="op">{</span></span>
<span>  </span>
<span>  <span class="va">treatment</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Control"</span>, <span class="st">"Amended"</span><span class="op">)</span>, each <span class="op">=</span> <span class="va">n_fields</span> <span class="op">/</span> <span class="fl">2</span><span class="op">)</span></span>
<span>  <span class="va">field_effect</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n_fields</span>, <span class="fl">0</span>, <span class="va">field_sd</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/do.call.html">do.call</a></span><span class="op">(</span><span class="va">rbind</span>, <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="va">n_fields</span><span class="op">)</span>, <span class="kw">function</span><span class="op">(</span><span class="va">f</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/do.call.html">do.call</a></span><span class="op">(</span><span class="va">rbind</span>, <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="va">n_plots</span><span class="op">)</span>, <span class="kw">function</span><span class="op">(</span><span class="va">p</span><span class="op">)</span> <span class="op">{</span></span>
<span>      <span class="va">plot_effect</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">0</span>, <span class="va">plot_sd</span><span class="op">)</span></span>
<span>      <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>        yield <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n_plants</span>, mean <span class="op">=</span> <span class="fl">50</span> <span class="op">+</span> <span class="va">field_effect</span><span class="op">[</span><span class="va">f</span><span class="op">]</span> <span class="op">+</span> <span class="va">plot_effect</span>, sd <span class="op">=</span> <span class="va">plant_sd</span><span class="op">)</span>,</span>
<span>        treatment <span class="op">=</span> <span class="va">treatment</span><span class="op">[</span><span class="va">f</span><span class="op">]</span>,</span>
<span>        field <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">f</span><span class="op">)</span>,</span>
<span>        plot <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">f</span>, <span class="va">p</span>, sep <span class="op">=</span> <span class="st">"_"</span><span class="op">)</span><span class="op">)</span></span>
<span>      <span class="op">)</span></span>
<span>    <span class="op">}</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="op">}</span><span class="op">)</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="co"># Wrong: treat all plants as independent</span></span>
<span>  <span class="va">p_wrong</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">yield</span> <span class="op">~</span> <span class="va">treatment</span>, data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span>  <span class="op">)</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">[[</span><span class="st">"Pr(&gt;F)"</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span></span>
<span>  </span>
<span>  <span class="co"># Correct: use field means as the unit of analysis</span></span>
<span>  <span class="va">field_means</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aggregate.html">aggregate</a></span><span class="op">(</span><span class="va">yield</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="va">field</span>,</span>
<span>                           data <span class="op">=</span> <span class="va">df</span>, FUN <span class="op">=</span> <span class="va">mean</span><span class="op">)</span></span>
<span>  <span class="va">p_correct</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">yield</span> <span class="op">~</span> <span class="va">treatment</span>, data <span class="op">=</span> <span class="va">field_means</span><span class="op">)</span></span>
<span>  <span class="op">)</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">[[</span><span class="st">"Pr(&gt;F)"</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span></span>
<span>  </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>p_wrong <span class="op">=</span> <span class="va">p_wrong</span>, p_correct <span class="op">=</span> <span class="va">p_correct</span><span class="op">)</span></span>
<span>  </span>
<span><span class="op">}</span>, .options <span class="op">=</span> <span class="fu"><a href="https://furrr.futureverse.org/reference/furrr_options.html">furrr_options</a></span><span class="op">(</span>seed <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://future.futureverse.org/reference/plan.html">plan</a></span><span class="op">(</span><span class="va">sequential</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># View the simulated data</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">results</span>, n <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        p_wrong p_correct
1  1.713975e-02 0.4803663
2  1.914645e-05 0.3266718
3  9.265631e-01 0.9875177
4  7.418683e-09 0.2185384
5  7.697033e-05 0.4926903
6  8.143981e-01 0.9355019
7  2.013291e-01 0.8170871
8  1.935473e-01 0.8389504
9  4.284297e-20 0.1088934
10 4.178010e-01 0.8922692</code></pre>
</div>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span></span>
<span>  <span class="st">"False positive rate ignoring hierarchy:"</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">results</span><span class="op">$</span><span class="va">p_wrong</span>   <span class="op">&lt;</span> <span class="va">alpha</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span>,</span>
<span>  <span class="st">"\nFalse positive rate correct analysis:"</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">results</span><span class="op">$</span><span class="va">p_correct</span> <span class="op">&lt;</span> <span class="va">alpha</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">"\n"</span></span>
<span>  <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>False positive rate ignoring hierarchy: 0.681 
False positive rate correct analysis: 0.05 </code></pre>
</div>
</div>
<p>The false positive rate from the naive analysis is far above 5% (0.681), while the correct analysis, using field means as the unit of analysis for the field-level treatment, stays at the nominal level. This is the pseudoreplication problem from Chapter 2, now seen in a hierarchical context.</p>
</section><section id="visualising-the-hierarchy" class="level3" data-number="7.1.3"><h3 data-number="7.1.3" class="anchored" data-anchor-id="visualising-the-hierarchy">
<span class="header-section-number">7.1.3</span> Visualising the Hierarchy</h3>
<p>It helps to draw the structure of a hierarchical experiment explicitly before deciding how to analyse it. For the field-plot-plant example:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-hierarchy-diagram" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-hierarchy-diagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-hierarchy-diagram">flowchart TD
    subgraph L1["Level 1: Experiment"]
        A[Experiment]
    end

    subgraph L2["Level 2: Field\ntreatment unit"]
        B[Control\nField 1 and 2]
        C[Amended\nField 3 and 4]
    end

    subgraph L3["\n\n\nLevel 3: Plot\nvariety unit"]
        D[Plot 1\nVariety A]
        E[Plot 2\nVariety B]
        F[Plot 3\nVariety A]
        G[Plot 4\nVariety B]
    end

    subgraph L4["\n\n\n\nLevel 4: Plant - observation"]
        H[Plants\nn obs]
        I[Plants\nn obs]
        J[Plants\nn obs]
        K[Plants\nn obs]
    end

    A --&gt; B
    A --&gt; C
    B --&gt; D
    B --&gt; E
    C --&gt; F
    C --&gt; G
    D --&gt; H
    E --&gt; I
    F --&gt; J
    G --&gt; K

    style A fill:#555555,color:#ffffff
    style B fill:#2E86AB,color:#ffffff
    style C fill:#E84855,color:#ffffff
    style D fill:#2E86AB,color:#ffffff
    style E fill:#2E86AB,color:#ffffff
    style F fill:#E84855,color:#ffffff
    style G fill:#E84855,color:#ffffff
    style H fill:#aaaaaa,color:#ffffff
    style I fill:#aaaaaa,color:#ffffff
    style J fill:#aaaaaa,color:#ffffff
    style K fill:#aaaaaa,color:#ffffff
    style L1 fill:#f8f8f8,stroke:#cccccc,color:#555555
    style L2 fill:#f8f8f8,stroke:#cccccc,color:#555555
    style L3 fill:#f8f8f8,stroke:#cccccc,color:#555555
    style L4 fill:#f8f8f8,stroke:#cccccc,color:#555555
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hierarchy-diagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.1: Hierarchical structure of the field experiment. Soil treatment is applied at the field level and replicated across fields. Variety is applied at the plot level within each field. Plants are the observational unit at the bottom of the hierarchy.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="the-golden-rule-of-hierarchical-analysis" class="level3" data-number="7.1.4"><h3 data-number="7.1.4" class="anchored" data-anchor-id="the-golden-rule-of-hierarchical-analysis">
<span class="header-section-number">7.1.4</span> The Golden Rule of Hierarchical Analysis</h3>
<p>The rule that prevents most hierarchical analysis errors can be stated simply:</p>
<blockquote class="blockquote">
<p><strong>The error term used to test a treatment effect must come from the same level of the hierarchy at which that treatment was applied and randomised.</strong></p>
</blockquote>
<p>If soil amendment was randomised across fields, the field-to-field variation is the correct error term for testing the amendment effect. If variety was randomised across plots within fields, the plot-to-plot variation within fields is the correct error term for testing the variety effect. Using plant-level variation to test a field-level treatment is like using a ruler calibrated in millimetres to measure a distance that varies in kilometres, the instrument is simply measuring the wrong thing.</p>
<p>This rule is the conceptual foundation of both split-plot and nested ANOVA designs, which formalise it into a statistical framework.</p>
</section></section><section id="sec-pseudoreplication2" class="level2" data-number="7.2"><h2 data-number="7.2" class="anchored" data-anchor-id="sec-pseudoreplication2">
<span class="header-section-number">7.2</span> Pseudoreplication: The Silent Epidemic in Biology</h2>
<section id="a-pervasive-problem" class="level3" data-number="7.2.1"><h3 data-number="7.2.1" class="anchored" data-anchor-id="a-pervasive-problem">
<span class="header-section-number">7.2.1</span> A Pervasive Problem</h3>
<p>In their landmark 1984 paper, Hurlbert <span class="citation" data-cites="hurlbert1984">(<a href="references.html#ref-hurlbert1984" role="doc-biblioref">1984</a>)</span> documented that pseudoreplication, the treatment of non-independent observations as independent replicates, was present in a substantial fraction of published ecological field experiments. Subsequent reviews have found similar rates across ecology, agriculture, and biomedical research. The problem has not gone away.</p>
<p>Pseudoreplication takes several distinct forms in practice, and being able to recognise each is an essential skill.</p>
<p><strong>Simple pseudoreplication</strong> occurs when multiple measurements are taken from a single experimental unit and treated as independent replicates. Six measurements of soil nitrogen from the same plot do not give you six independent replicates, they give you six estimates of the nitrogen level in one plot. The plot is still <span class="math inline">\(n = 1\)</span>.</p>
<p><strong>Sacrificial pseudoreplication</strong> occurs when the analysis is conducted at the wrong level of the hierarchy, as in the field example above. The name reflects the fact that the correct, but lower-powered, analysis is sacrificed in favour of an inflated, incorrect one.</p>
<p><strong>Temporal pseudoreplication</strong> occurs when the same unit is measured repeatedly over time and the measurements are treated as independent. This is the repeated measures problem from Chapter 6 seen in a field ecology context: a plot measured in spring, summer, and autumn provides three measurements of the same plot, not three independent plots.</p>
</section><section id="how-to-avoid-it" class="level3" data-number="7.2.2"><h3 data-number="7.2.2" class="anchored" data-anchor-id="how-to-avoid-it">
<span class="header-section-number">7.2.2</span> How to Avoid It</h3>
<p>The antidote to pseudoreplication is to identify the experimental unit, the smallest unit that was independently assigned to a treatment, before the analysis begins, and to ensure that the unit of analysis matches the unit of replication. When subsampling within units is necessary (for precision, or because the response must be measured at a finer scale than the treatment was applied), the subsamples should be averaged to the level of the experimental unit before analysis, or the hierarchical structure should be modelled explicitly.</p>
</section></section><section id="split-plot-design-structure-and-correct-error-terms" class="level2" data-number="7.3"><h2 data-number="7.3" class="anchored" data-anchor-id="split-plot-design-structure-and-correct-error-terms">
<span class="header-section-number">7.3</span> Split-Plot Design: Structure and Correct Error Terms</h2>
<section id="when-does-a-split-plot-design-arise" class="level3" data-number="7.3.1"><h3 data-number="7.3.1" class="anchored" data-anchor-id="when-does-a-split-plot-design-arise">
<span class="header-section-number">7.3.1</span> When Does a Split-Plot Design Arise?</h3>
<p>A split-plot design arises naturally when two factors must be tested but one is much more difficult or expensive to change than the other. The classic agricultural example: irrigation regime (irrigated vs rainfed) must be applied to whole large fields because irrigation infrastructure cannot be changed plot by plot, while fertiliser type can be applied to much smaller individual plots within each field.</p>
<p>The experiment therefore applies the hard-to-change factor (<strong>whole-plot factor</strong>) to large units (<strong>whole plots</strong>), then subdivides each whole plot into smaller units (<strong>sub-plots</strong>) and applies the easy-to-change factor (<strong>sub-plot factor</strong>) to those.</p>
<p>This structure is not merely a practical compromise, it is a deliberate design choice that must be reflected in the analysis. The two factors are tested against different error terms, because they were randomised at different levels of the hierarchy.</p>
</section><section id="structure-of-the-split-plot-design" class="level3" data-number="7.3.2"><h3 data-number="7.3.2" class="anchored" data-anchor-id="structure-of-the-split-plot-design">
<span class="header-section-number">7.3.2</span> Structure of the Split-Plot Design</h3>
<p>With <span class="math inline">\(a\)</span> levels of the whole-plot factor <span class="math inline">\(A\)</span>, <span class="math inline">\(b\)</span> levels of the sub-plot factor <span class="math inline">\(B\)</span>, and <span class="math inline">\(r\)</span> whole-plot replicates per level of <span class="math inline">\(A\)</span>:</p>
<ul>
<li>There are <span class="math inline">\(a \times r\)</span> whole plots in total.</li>
<li>Each whole plot is divided into <span class="math inline">\(b\)</span> sub-plots.</li>
<li>Total observations: <span class="math inline">\(a \times r \times b\)</span>.</li>
</ul>
<p>The two error terms are:</p>
<ul>
<li>
<strong>Whole-plot error (<span class="math inline">\(MS_{WP}\)</span>):</strong> the variation among whole plots within the same level of <span class="math inline">\(A\)</span>. This is the correct error term for testing the main effect of <span class="math inline">\(A\)</span>.</li>
<li>
<strong>Sub-plot error (<span class="math inline">\(MS_{SP}\)</span>):</strong> the variation among sub-plots within the same whole plot. This is the correct error term for testing the main effect of <span class="math inline">\(B\)</span> and the <span class="math inline">\(A \times B\)</span> interaction.</li>
</ul>
<p>The sub-plot error is typically smaller than the whole-plot error, which is why the sub-plot factor and the interaction are tested with more power than the whole-plot factor, a direct consequence of the design structure.</p>
</section><section id="the-split-plot-model" class="level3" data-number="7.3.3"><h3 data-number="7.3.3" class="anchored" data-anchor-id="the-split-plot-model">
<span class="header-section-number">7.3.3</span> The Split-Plot Model</h3>
<p><span class="math display">\[y_{ijk} = \mu + \alpha_i + \delta_{ij} + \beta_k +
            (\alpha\beta)_{ik} + \varepsilon_{ijk}\]</span></p>
<p>where <span class="math inline">\(\alpha_i\)</span> is the whole-plot treatment effect, <span class="math inline">\(\delta_{ij}\)</span> is the whole-plot error (variation among whole plots within treatment <span class="math inline">\(i\)</span>, the error term for <span class="math inline">\(A\)</span>), <span class="math inline">\(\beta_k\)</span> is the sub-plot treatment effect, <span class="math inline">\((\alpha\beta)_{ik}\)</span> is the interaction, and <span class="math inline">\(\varepsilon_{ijk}\)</span> is the sub-plot error (the error term for <span class="math inline">\(B\)</span> and <span class="math inline">\(A \times B\)</span>).</p>
<p>In R, the two error terms are specified explicitly using the <code>Error()</code> term in <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># whole.plot: the unit receiving the whole-plot treatment</span></span>
<span><span class="co"># A: whole-plot factor</span></span>
<span><span class="co"># B: sub-plot factor</span></span>
<span></span>
<span><span class="va">fit_sp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">A</span> <span class="op">*</span> <span class="va">B</span> <span class="op">+</span> <span class="fu">Error</span><span class="op">(</span><span class="va">whole.plot</span><span class="op">/</span><span class="va">B</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_sp</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section></section><section id="nested-anova-subsampling-vs-true-replication" class="level2" data-number="7.4"><h2 data-number="7.4" class="anchored" data-anchor-id="nested-anova-subsampling-vs-true-replication">
<span class="header-section-number">7.4</span> Nested ANOVA: Subsampling vs True Replication</h2>
<section id="the-nested-structure" class="level3" data-number="7.4.1"><h3 data-number="7.4.1" class="anchored" data-anchor-id="the-nested-structure">
<span class="header-section-number">7.4.1</span> The Nested Structure</h3>
<p>A nested design arises when the levels of one factor exist entirely within the levels of another, and the levels of the inner factor are not the same across levels of the outer factor. Fields contain plots, but the plots in Field 1 are different from the plots in Field 2 as they are nested within their respective fields, not crossed with them.</p>
<p>This is distinct from a factorial design, where every level of every factor is combined with every level of every other factor. In a factorial design, Variety A appears in both the irrigated and rainfed fields. In a nested design, the plots in Field 1 are unique to Field 1.</p>
<p>The nested ANOVA model for two levels of nesting:</p>
<p><span class="math display">\[y_{ijk} = \mu + \alpha_i + \beta_{j(i)} + \varepsilon_{ijk}\]</span></p>
<p>where <span class="math inline">\(\alpha_i\)</span> is the effect of the outer factor <span class="math inline">\(A\)</span> at level <span class="math inline">\(i\)</span>, <span class="math inline">\(\beta_{j(i)}\)</span> is the effect of the inner factor <span class="math inline">\(B\)</span> at level <span class="math inline">\(j\)</span> nested within level <span class="math inline">\(i\)</span> of <span class="math inline">\(A\)</span> (denoted <span class="math inline">\(j(i)\)</span>), and <span class="math inline">\(\varepsilon_{ijk}\)</span> is the residual.</p>
<p>In R:</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># B is nested within A</span></span>
<span><span class="va">fit_nested</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">A</span> <span class="op">+</span> <span class="va">B</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="va">A</span>, data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span><span class="co"># Equivalently:</span></span>
<span><span class="va">fit_nested</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">A</span><span class="op">/</span><span class="va">B</span>, data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_nested</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="subsampling-vs-true-replication" class="level3" data-number="7.4.2"><h3 data-number="7.4.2" class="anchored" data-anchor-id="subsampling-vs-true-replication">
<span class="header-section-number">7.4.2</span> Subsampling vs True Replication</h3>
<p>The most important practical distinction in nested designs is between <strong>true replication</strong> and <strong>subsampling</strong>. True replicates are independent experimental units that each received a treatment independently. Subsamples are multiple measurements taken from the same experimental unit.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 37%">
<col style="width: 37%">
</colgroup>
<thead><tr class="header">
<th></th>
<th>True replicates</th>
<th>Subsamples</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Definition</td>
<td>Independently treated units</td>
<td>Multiple measures of one unit</td>
</tr>
<tr class="even">
<td>Example</td>
<td>Four separately irrigated fields</td>
<td>Five soil cores from one field</td>
</tr>
<tr class="odd">
<td>Contribution to <span class="math inline">\(n\)</span>
</td>
<td>Each counts as one replicate</td>
<td>Together count as one replicate</td>
</tr>
<tr class="even">
<td>Error term</td>
<td>Between-unit residual</td>
<td>Within-unit residual</td>
</tr>
</tbody>
</table>
<p>Treating subsamples as true replicates is the most common form of sacrificial pseudoreplication. The nested ANOVA correctly partitions the variation into between-unit and within-unit components and uses the appropriate error term for each.</p>
</section></section><section id="example-1-grazing-effects-on-plant-diversity" class="level2" data-number="7.5"><h2 data-number="7.5" class="anchored" data-anchor-id="example-1-grazing-effects-on-plant-diversity">
<span class="header-section-number">7.5</span> Example 1: Grazing Effects on Plant Diversity</h2>
<section id="the-study" class="level3" data-number="7.5.1"><h3 data-number="7.5.1" class="anchored" data-anchor-id="the-study">
<span class="header-section-number">7.5.1</span> The Study</h3>
<p>An ecologist is investigating the effect of grazing intensity (ungrazed, light grazing, heavy grazing) on plant species richness in a grassland (<a href="appendix-b-packages.html#sec-grazing" class="quarto-xref"><span>Section B.1.5</span></a>). Six large paddocks are available, two assigned to each grazing treatment. Within each paddock, four quadrats are established and plant species richness is counted in each. Three random soil cores are taken from each quadrat for soil nutrient analysis, but species richness is the response of interest.</p>
<p>The structure is:</p>
<p><span class="math display">\[\text{Grazing treatment} \supset \text{Paddock} \supset \text{Quadrat}\]</span></p>
<p>Grazing treatment is the fixed factor of interest. Paddock is nested within grazing treatment and is the unit of replication for the treatment comparison. Quadrat is nested within paddock and provides subsamples within the true replicates.</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Show the simulated data</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">grazing</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    richness         treatment paddock
 Min.   : 3.000   Ungrazed:8   U1:4   
 1st Qu.: 6.750   Light   :8   U2:4   
 Median :10.500   Heavy   :8   L1:4   
 Mean   : 9.792                L2:4   
 3rd Qu.:13.250                H1:4   
 Max.   :15.000                H2:4   </code></pre>
</div>
</div>
</section><section id="correct-analysis-paddock-as-the-error-term" class="level3" data-number="7.5.2"><h3 data-number="7.5.2" class="anchored" data-anchor-id="correct-analysis-paddock-as-the-error-term">
<span class="header-section-number">7.5.2</span> Correct Analysis: Paddock as the Error Term</h3>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Nested ANOVA: paddock nested within treatment</span></span>
<span><span class="va">fit_eco</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">richness</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="fu">Error</span><span class="op">(</span><span class="va">paddock</span><span class="op">/</span><span class="va">treatment</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">grazing</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_eco</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Error: paddock
          Df Sum Sq Mean Sq F value Pr(&gt;F)  
treatment  2 303.58  151.79   23.81 0.0144 *
Residuals  3  19.13    6.38                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Error: Within
          Df Sum Sq Mean Sq F value Pr(&gt;F)
Residuals 18  35.25   1.958               </code></pre>
</div>
</div>
<p>The output is split into two strata, each telling a different part of the story.</p>
<p>The <strong><code>Error: paddock</code> stratum</strong> is where the treatment test lives. Grazing treatment has a significant effect on plant species richness (<span class="math inline">\(F_{2,3} = 23.81\)</span>, <span class="math inline">\(p = 0.014\)</span>). The residual mean square in this stratum (6.38) estimates the paddock-to-paddock variation within treatments i.e.&nbsp;the genuine noise against which the treatment effect is judged, since paddocks are the units that were independently assigned to grazing treatments. This is the correct error term.</p>
<p>The <strong><code>Error: Within</code> stratum</strong> captures the quadrat-to-quadrat variation within paddocks, with a residual mean square of 1.96. Notice that this is substantially smaller than the paddock-level residual (6.38) meaning paddocks differ from each other more than quadrats within the same paddock differ from each other. This is the typical pattern in nested designs, and it is precisely why using quadrat-level variation to test the treatment effect would be wrong: the within-paddock noise floor is too low, and testing against it would make the treatment appear far more significant than the actual replication warrants.</p>
<p>With only two paddocks per treatment, the degrees of freedom for the treatment test are low (<span class="math inline">\(df_{\text{treatment}} = 2\)</span>, <span class="math inline">\(df_{\text{error}} = 3\)</span>). This correctly reflects the limited replication at the treatment level. No matter how many quadrats are sampled within each paddock, the experiment has only six independent units at the treatment level, and the analysis honestly acknowledges this. The significant result (<span class="math inline">\(p = 0.014\)</span>) is therefore a genuine finding achieved with sparse replication, not an artefact of inflated degrees of freedom.</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Visualise</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">paddock_means</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aggregate.html">aggregate</a></span><span class="op">(</span><span class="va">richness</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="va">paddock</span>, data <span class="op">=</span> <span class="va">grazing</span>, FUN <span class="op">=</span> <span class="va">mean</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">grazing</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">treatment</span>, y <span class="op">=</span> <span class="va">richness</span>, colour <span class="op">=</span> <span class="va">treatment</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.15</span>, alpha <span class="op">=</span> <span class="fl">0.4</span>, size <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">paddock_means</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">richness</span>, group <span class="op">=</span> <span class="va">paddock</span><span class="op">)</span>, size <span class="op">=</span> <span class="fl">4</span>, shape <span class="op">=</span> <span class="fl">18</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/stat_summary.html">stat_summary</a></span><span class="op">(</span>fun <span class="op">=</span> <span class="va">mean</span>, geom <span class="op">=</span> <span class="st">"crossbar"</span>, width <span class="op">=</span> <span class="fl">0.4</span>, colour <span class="op">=</span> <span class="st">"grey30"</span>, linewidth <span class="op">=</span> <span class="fl">0.8</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#2E86AB"</span>, <span class="st">"#F6AE2D"</span>, <span class="st">"#E84855"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Grazing treatment"</span>, y <span class="op">=</span> <span class="st">"Species richness"</span>, colour <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03e-split-plot-nested_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The analysis uses paddock as the correct error term for testing the grazing treatment effect. With only two paddocks per treatment, the degrees of freedom for the treatment test are low (<span class="math inline">\(df = 2\)</span> for the treatment, <span class="math inline">\(df = 3\)</span> for the whole-plot error), correctly reflecting the fact that the experiment has limited replication at the treatment level, regardless of how many quadrats were sampled within each paddock.</p>
</section><section id="what-happens-if-you-ignore-the-nesting" class="level3" data-number="7.5.3"><h3 data-number="7.5.3" class="anchored" data-anchor-id="what-happens-if-you-ignore-the-nesting">
<span class="header-section-number">7.5.3</span> What Happens if You Ignore the Nesting</h3>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Wrong: treat all quadrats as independent</span></span>
<span><span class="va">fit_eco_wrong</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">richness</span> <span class="op">~</span> <span class="va">treatment</span>, data <span class="op">=</span> <span class="va">grazing</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_eco_wrong</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value   Pr(&gt;F)    
treatment    2 303.58  151.79   58.62 2.55e-09 ***
Residuals   21  54.38    2.59                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span></span>
<span>  <span class="st">"\nCorrect df for treatment: 2, error df: 3\nWrong df for treatment: 2, error df:"</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/df.residual.html">df.residual</a></span><span class="op">(</span><span class="va">fit_eco_wrong</span><span class="op">)</span>, <span class="st">"\n"</span></span>
<span>  <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Correct df for treatment: 2, error df: 3
Wrong df for treatment: 2, error df: 21 </code></pre>
</div>
</div>
<p>The naive analysis has <span class="math inline">\(df_{\text{error}} = 21\)</span> instead of 3, artificially inflating the power of the test by treating quadrat-level variation as if it were independent replication of the treatment.</p>
</section></section><section id="example-2-irrigation-and-fertiliser-in-a-split-plot-design" class="level2" data-number="7.6"><h2 data-number="7.6" class="anchored" data-anchor-id="example-2-irrigation-and-fertiliser-in-a-split-plot-design">
<span class="header-section-number">7.6</span> Example 2: Irrigation and Fertiliser in a Split-Plot Design</h2>
<section id="the-study-1" class="level3" data-number="7.6.1"><h3 data-number="7.6.1" class="anchored" data-anchor-id="the-study-1">
<span class="header-section-number">7.6.1</span> The Study</h3>
<p>An agronomist is testing two irrigation regimes (rainfed vs irrigated) and three fertiliser types (none, nitrogen, phosphorus) on wheat yield (<a href="appendix-b-packages.html#sec-irrig" class="quarto-xref"><span>Section B.1.6</span></a>). Irrigation is applied to whole fields (it cannot be changed within a field) while fertiliser can be applied to individual plots within each field. Six fields are available, three assigned to each irrigation treatment. Each field is divided into three plots, one for each fertiliser type.</p>
<p>This is a split-plot design:</p>
<ul>
<li>
<strong>Whole-plot factor:</strong> irrigation (2 levels), replicated across 6 fields (3 per treatment).</li>
<li>
<strong>Sub-plot factor:</strong> fertiliser (3 levels), applied to plots within each field.</li>
<li>
<strong>Total observations:</strong> <span class="math inline">\(6 \times 3 = 18\)</span> plots.</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">irrig</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     yield           irrigation      fertiliser field 
 Min.   :31.40   Rainfed  :9    None      :6    R1:3  
 1st Qu.:36.62   Irrigated:9    Nitrogen  :6    R2:3  
 Median :43.43                  Phosphorus:6    R3:3  
 Mean   :42.98                                  I1:3  
 3rd Qu.:48.91                                  I2:3  
 Max.   :53.43                                  I3:3  </code></pre>
</div>
</div>
</section><section id="fitting-the-split-plot-model" class="level3" data-number="7.6.2"><h3 data-number="7.6.2" class="anchored" data-anchor-id="fitting-the-split-plot-model">
<span class="header-section-number">7.6.2</span> Fitting the Split-Plot Model</h3>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Correct split-plot analysis</span></span>
<span><span class="co"># field is the whole-plot unit; fertiliser is the sub-plot factor</span></span>
<span><span class="va">fit_sp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">yield</span> <span class="op">~</span> <span class="va">irrigation</span> <span class="op">*</span> <span class="va">fertiliser</span> <span class="op">+</span> <span class="fu">Error</span><span class="op">(</span><span class="va">field</span><span class="op">/</span><span class="va">fertiliser</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">irrig</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_sp</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Error: field
           Df Sum Sq Mean Sq F value Pr(&gt;F)
irrigation  1  105.6  105.58   3.647  0.129
Residuals   4  115.8   28.95               

Error: field:fertiliser
                      Df Sum Sq Mean Sq F value   Pr(&gt;F)    
fertiliser             2  532.6  266.29  89.801 3.31e-06 ***
irrigation:fertiliser  2   26.6   13.28   4.479   0.0495 *  
Residuals              8   23.7    2.97                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The output separates into two error strata, each testing a different set of effects against the appropriate level of variation.</p>
<p>The <strong><code>Error: field</code> stratum</strong> tests the whole-plot factor, irrigation, against the field-to-field variation within irrigation treatments (<span class="math inline">\(MS_{\text{field}} = 28.95\)</span>). The effect of irrigation is not significant (<span class="math inline">\(F_{1,4} = 3.65\)</span>, <span class="math inline">\(p = 0.129\)</span>). This result should be interpreted carefully: the non-significance does not mean irrigation has no effect on yield (the interaction below suggests it does) but rather that the main effect of irrigation, averaged across all three fertiliser types, cannot be distinguished from field-to-field background variation with only three fields per irrigation treatment. This is the honest cost of having limited whole-plot replication. The wide confidence interval around the irrigation effect, not the <span class="math inline">\(p\)</span>-value alone, reflects the true uncertainty here.</p>
<p>The <strong><code>Error: field:fertiliser</code> stratum</strong> tests the sub-plot factor and the interaction, both against the plot-to-plot variation within fields (<span class="math inline">\(MS_{\text{subplot}} = 2.97\)</span>). This residual is nearly ten times smaller than the whole-plot residual (28.95), which is the typical pattern in split-plot designs and explains why sub-plot effects are tested with considerably more power than whole-plot effects.</p>
<p>The main effect of fertiliser is highly significant (<span class="math inline">\(F_{2,8} = 89.80\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>), confirming that fertiliser type has a strong effect on yield regardless of irrigation regime. More interestingly, the irrigation-by-fertiliser interaction is significant (<span class="math inline">\(F_{2,8} = 4.48\)</span>, <span class="math inline">\(p = 0.049\)</span>), indicating that the yield advantage of different fertiliser types is not the same under rainfed and irrigated conditions. Nitrogen fertiliser, in particular, produces a larger absolute yield gain under irrigation than under rainfed conditions which is a biologically sensible result, since nitrogen uptake is enhanced by water availability.</p>
<p>This pattern of results is instructive for two reasons. First, it illustrates why the split-plot design is worth the added analytical complexity: had this been run as a simple two-way factorial with independent plots for all combinations, the irrigation effect and the interaction would have been tested against the same error term, concealing the different precision available for whole-plot and sub-plot comparisons. Second, it demonstrates a common outcome in agricultural split-plot experiments: the whole-plot factor (here irrigation, which is expensive to manipulate and therefore sparsely replicated) is underpowered relative to the sub-plot factor (fertiliser, which is cheap to vary and therefore well replicated). Recognising this asymmetry at the design stage, and planning accordingly, is one of the practical skills that distinguishes experienced from novice experimenters.</p>
</section><section id="visualising-the-results" class="level3" data-number="7.6.3"><h3 data-number="7.6.3" class="anchored" data-anchor-id="visualising-the-results">
<span class="header-section-number">7.6.3</span> Visualising the Results</h3>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">summ_agr</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aggregate.html">aggregate</a></span><span class="op">(</span><span class="va">yield</span> <span class="op">~</span> <span class="va">irrigation</span> <span class="op">+</span> <span class="va">fertiliser</span>, data <span class="op">=</span> <span class="va">irrig</span>, FUN <span class="op">=</span> <span class="va">mean</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">irrig</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">fertiliser</span>, y <span class="op">=</span> <span class="va">yield</span>, colour <span class="op">=</span> <span class="va">irrigation</span>, group <span class="op">=</span> <span class="va">irrigation</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.08</span>, alpha <span class="op">=</span> <span class="fl">0.5</span>, size <span class="op">=</span> <span class="fl">2.5</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>colour <span class="op">=</span> <span class="va">irrigation</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">summ_agr</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">yield</span><span class="op">)</span>, linewidth <span class="op">=</span> <span class="fl">1.2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">summ_agr</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">yield</span><span class="op">)</span>, size <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#E84855"</span>, <span class="st">"#2E86AB"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Fertiliser"</span>, y <span class="op">=</span> <span class="st">"Yield (g/plot)"</span>, colour <span class="op">=</span> <span class="st">"Irrigation"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"inside"</span>, legend.position.inside <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.15</span>, <span class="fl">0.85</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-agriculture-plot" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-agriculture-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03e-split-plot-nested_files/figure-html/fig-agriculture-plot-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-agriculture-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.2: Mean wheat yield by irrigation regime and fertiliser type in a split-plot design. Points show individual plot yields. Lines connect the means of each irrigation group across fertiliser types. The larger spread of the rainfed points reflects the greater whole-plot variability in unirrigated fields.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="why-the-split-plot-analysis-matters" class="level3" data-number="7.6.4"><h3 data-number="7.6.4" class="anchored" data-anchor-id="why-the-split-plot-analysis-matters">
<span class="header-section-number">7.6.4</span> Why the Split-Plot Analysis Matters</h3>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Correct split-plot analysis vs naive ANOVA</span></span>
<span></span>
<span><span class="co"># Correct</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"=== Correct split-plot analysis ===\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>=== Correct split-plot analysis ===</code></pre>
</div>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_sp</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Error: field
           Df Sum Sq Mean Sq F value Pr(&gt;F)
irrigation  1  105.6  105.58   3.647  0.129
Residuals   4  115.8   28.95               

Error: field:fertiliser
                      Df Sum Sq Mean Sq F value   Pr(&gt;F)    
fertiliser             2  532.6  266.29  89.801 3.31e-06 ***
irrigation:fertiliser  2   26.6   13.28   4.479   0.0495 *  
Residuals              8   23.7    2.97                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Wrong: treat all plots as independent — ignores field structure</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"\n=== Naive ANOVA (ignoring field structure) ===\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=== Naive ANOVA (ignoring field structure) ===</code></pre>
</div>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">yield</span> <span class="op">~</span> <span class="va">irrigation</span> <span class="op">*</span> <span class="va">fertiliser</span>, data <span class="op">=</span> <span class="va">irrig</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      Df Sum Sq Mean Sq F value   Pr(&gt;F)    
irrigation             1  105.6  105.58   9.080   0.0108 *  
fertiliser             2  532.6  266.29  22.902 8.01e-05 ***
irrigation:fertiliser  2   26.6   13.28   1.142   0.3515    
Residuals             12  139.5   11.63                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Comparing the two analyses reveals precisely what goes wrong when the split-plot structure is ignored, and the contrast need all our attention.</p>
<p>The most consequential difference concerns the irrigation effect. In the correct split-plot analysis, irrigation is non-significant (<span class="math inline">\(F_{1,4} = 3.65\)</span>, <span class="math inline">\(p = 0.129\)</span>), tested against the whole-plot residual (<span class="math inline">\(MS = 28.95\)</span>) which is the field-to-field variation that is the genuine source of uncertainty for a treatment applied at the field level. In the naive analysis, irrigation appears significant (<span class="math inline">\(F_{1,12} = 9.08\)</span>, <span class="math inline">\(p = 0.011\)</span>), tested against the pooled residual (<span class="math inline">\(MS = 11.63\)</span>) which combines whole-plot and sub-plot variation indiscriminately. The naive analysis has produced a false positive: it declares irrigation significant not because the evidence supports this conclusion, but because it used an error term that is far too small for a field-level treatment. The residual degrees of freedom jump from 4 to 12, not because more information is available, but because sub-plot variation has been illegitimately pressed into service as a stand-in for whole-plot variation.</p>
<p>The interaction tells an equally instructive story, but in the opposite direction. In the correct analysis the irrigation-by-fertiliser interaction is significant (<span class="math inline">\(F_{2,8} = 4.48\)</span>, <span class="math inline">\(p = 0.049\)</span>), tested against the sub-plot residual (<span class="math inline">\(MS = 2.97\)</span>) which is the appropriate error term for an effect at the plot level. In the naive analysis the same interaction is non-significant (<span class="math inline">\(F_{2,12} = 1.14\)</span>, <span class="math inline">\(p = 0.352\)</span>), because the pooled residual inflates the error term relative to the true sub-plot noise. Here the naive analysis produces a false negative: a real interaction that the correct analysis detects is hidden when the error terms are conflated.</p>
<p>The fertiliser main effect is significant in both analyses and reaches a similar F value (<span class="math inline">\(F_{2,8} = 89.80\)</span> vs <span class="math inline">\(F_{2,12} = 22.90\)</span>), though the naive analysis underestimates the precision available for sub-plot comparisons by using a larger pooled residual. This consistency for the sub-plot factor is not grounds for complacency: the simultaneous false positive for irrigation and false negative for the interaction show that the naive analysis gives the right answer for the right factor for the wrong reasons.</p>
<p>The lesson is general: in a split-plot design, using a single pooled error term simultaneously makes whole-plot tests too liberal and sub-plot tests too conservative. <em>The only correct solution is to use the two separate error terms that reflect the two levels at which randomisation actually occurred.</em></p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-hurlbert1984" class="csl-entry" role="listitem">
Hurlbert, Stuart H. 1984. <span>“Pseudoreplication and the <span>Design</span> of <span>Ecological Field Experiments</span>.”</span> <em>Ecological Monographs</em> 54 (2): 187–211. <a href="https://doi.org/10.2307/1942661">https://doi.org/10.2307/1942661</a>.
</div>
</div>
</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ebedthan\.github\.io\/maov\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./03d-repeated-measures.html" class="pagination-link" aria-label="Repeated Measures ANOVA">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Repeated Measures ANOVA</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04-modern-framework.html" class="pagination-link" aria-label="The Modern Framework">
        <span class="nav-page-text">The Modern Framework</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Modern Analysis of Variance by Anicet Ebou.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Ebedthan/maov/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li><li><a href="https://github.com/Ebedthan/maov/edit/main/03e-split-plot-nested.qmd" class="toc-action"><i class="bi empty"></i>Edit this page</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>