<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Anicet Ebou">
<title>12&nbsp; Experimental Design Principles – Modern Analysis of Variance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05b-reporting.html" rel="next">
<link href="./05-good-practice.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-good-practice.html">Good Practice and Reproductibility</a></li><li class="breadcrumb-item"><a href="./05a-experimental-design.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Experimental Design Principles</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Modern Analysis of Variance</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Ebedthan/maov/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./02-foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02a-what-is-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What is ANOVA, Really ?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02b-assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Assumptions</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./03-classical-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Classical ANOVA Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03a-one-way.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">One-Way ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03b-multiple-comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Multiple Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03c-two-way.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Two-Way ANOVA and Factorial Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03d-repeated-measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Repeated Measures ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03e-split-plot-nested.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Split-Plot and Nested Designs</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./04-modern-framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Modern Framework</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04a-anova-as-lm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA as a Linear Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04b-mixed-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Mixed-Effects Models: Beyond Classical ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04c-when-assumptions-fail.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">When Assumptions Fail, What to Do ?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04d-glmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Generalised Linear Mixed Models</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./05-good-practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Good Practice and Reproductibility</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05a-experimental-design.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Experimental Design Principles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05b-reporting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Reporting ANOVA Results</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05c-reproducible-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Reproducible Analysis with R</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-a-math.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">The Maths of the Book</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-b-packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Datasets and R Packages</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-c-decision-tree.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Decision Trees for Model Selection</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#randomisation-replication-and-blocking-the-triad" id="toc-randomisation-replication-and-blocking-the-triad" class="nav-link active" data-scroll-target="#randomisation-replication-and-blocking-the-triad"><span class="header-section-number">12.1</span> Randomisation, Replication, and Blocking: The Triad</a>
  <ul class="collapse">
<li><a href="#randomisation" id="toc-randomisation" class="nav-link" data-scroll-target="#randomisation"><span class="header-section-number">12.1.1</span> Randomisation</a></li>
  <li><a href="#replication" id="toc-replication" class="nav-link" data-scroll-target="#replication"><span class="header-section-number">12.1.2</span> Replication</a></li>
  <li><a href="#blocking" id="toc-blocking" class="nav-link" data-scroll-target="#blocking"><span class="header-section-number">12.1.3</span> Blocking</a></li>
  <li><a href="#a-concrete-example-a-field-with-a-fertility-gradient" id="toc-a-concrete-example-a-field-with-a-fertility-gradient" class="nav-link" data-scroll-target="#a-concrete-example-a-field-with-a-fertility-gradient"><span class="header-section-number">12.1.4</span> A Concrete Example: A Field With a Fertility Gradient</a></li>
  <li><a href="#the-treatment-error-formula" id="toc-the-treatment-error-formula" class="nav-link" data-scroll-target="#the-treatment-error-formula"><span class="header-section-number">12.1.5</span> The Treatment Error Formula</a></li>
  <li><a href="#simulating-the-field-experiment" id="toc-simulating-the-field-experiment" class="nav-link" data-scroll-target="#simulating-the-field-experiment"><span class="header-section-number">12.1.6</span> Simulating the Field Experiment</a></li>
  <li><a href="#computing-the-treatment-error-with-and-without-blocking" id="toc-computing-the-treatment-error-with-and-without-blocking" class="nav-link" data-scroll-target="#computing-the-treatment-error-with-and-without-blocking"><span class="header-section-number">12.1.7</span> Computing the Treatment Error: With and Without Blocking</a></li>
  <li><a href="#reading-the-numbers" id="toc-reading-the-numbers" class="nav-link" data-scroll-target="#reading-the-numbers"><span class="header-section-number">12.1.8</span> Reading the Numbers</a></li>
  <li><a href="#when-to-block" id="toc-when-to-block" class="nav-link" data-scroll-target="#when-to-block"><span class="header-section-number">12.1.9</span> When to Block</a></li>
  </ul>
</li>
  <li>
<a href="#designing-for-the-anova-you-want-to-run" id="toc-designing-for-the-anova-you-want-to-run" class="nav-link" data-scroll-target="#designing-for-the-anova-you-want-to-run"><span class="header-section-number">12.2</span> Designing for the ANOVA You Want to Run</a>
  <ul class="collapse">
<li><a href="#start-with-the-analysis" id="toc-start-with-the-analysis" class="nav-link" data-scroll-target="#start-with-the-analysis"><span class="header-section-number">12.2.1</span> Start With the Analysis</a></li>
  <li><a href="#match-the-unit-of-analysis-to-the-unit-of-randomisation" id="toc-match-the-unit-of-analysis-to-the-unit-of-randomisation" class="nav-link" data-scroll-target="#match-the-unit-of-analysis-to-the-unit-of-randomisation"><span class="header-section-number">12.2.2</span> Match the Unit of Analysis to the Unit of Randomisation</a></li>
  <li><a href="#anticipate-the-covariance-structure" id="toc-anticipate-the-covariance-structure" class="nav-link" data-scroll-target="#anticipate-the-covariance-structure"><span class="header-section-number">12.2.3</span> Anticipate the Covariance Structure</a></li>
  </ul>
</li>
  <li>
<a href="#common-design-mistakes-in-biology-and-how-to-avoid-them" id="toc-common-design-mistakes-in-biology-and-how-to-avoid-them" class="nav-link" data-scroll-target="#common-design-mistakes-in-biology-and-how-to-avoid-them"><span class="header-section-number">12.3</span> Common Design Mistakes in Biology and How to Avoid Them</a>
  <ul class="collapse">
<li><a href="#mistake-1-pseudoreplication" id="toc-mistake-1-pseudoreplication" class="nav-link" data-scroll-target="#mistake-1-pseudoreplication"><span class="header-section-number">12.3.1</span> Mistake 1: Pseudoreplication</a></li>
  <li><a href="#mistake-2-confounding-treatment-with-a-nuisance-variable" id="toc-mistake-2-confounding-treatment-with-a-nuisance-variable" class="nav-link" data-scroll-target="#mistake-2-confounding-treatment-with-a-nuisance-variable"><span class="header-section-number">12.3.2</span> Mistake 2: Confounding Treatment With a Nuisance Variable</a></li>
  <li><a href="#mistake-3-insufficient-replication-at-the-right-level" id="toc-mistake-3-insufficient-replication-at-the-right-level" class="nav-link" data-scroll-target="#mistake-3-insufficient-replication-at-the-right-level"><span class="header-section-number">12.3.3</span> Mistake 3: Insufficient Replication at the Right Level</a></li>
  <li><a href="#mistake-4-unbalanced-designs-by-negligence" id="toc-mistake-4-unbalanced-designs-by-negligence" class="nav-link" data-scroll-target="#mistake-4-unbalanced-designs-by-negligence"><span class="header-section-number">12.3.4</span> Mistake 4: Unbalanced Designs by Negligence</a></li>
  <li><a href="#mistake-5-measuring-the-wrong-response-variable" id="toc-mistake-5-measuring-the-wrong-response-variable" class="nav-link" data-scroll-target="#mistake-5-measuring-the-wrong-response-variable"><span class="header-section-number">12.3.5</span> Mistake 5: Measuring the Wrong Response Variable</a></li>
  <li><a href="#mistake-6-ignoring-the-temporal-structure" id="toc-mistake-6-ignoring-the-temporal-structure" class="nav-link" data-scroll-target="#mistake-6-ignoring-the-temporal-structure"><span class="header-section-number">12.3.6</span> Mistake 6: Ignoring the Temporal Structure</a></li>
  </ul>
</li>
  <li>
<a href="#sec-sample-size-power" id="toc-sec-sample-size-power" class="nav-link" data-scroll-target="#sec-sample-size-power"><span class="header-section-number">12.4</span> Sample Size and Power Before the Experiment, Not After</a>
  <ul class="collapse">
<li><a href="#power-analysis-is-a-professional-obligation" id="toc-power-analysis-is-a-professional-obligation" class="nav-link" data-scroll-target="#power-analysis-is-a-professional-obligation"><span class="header-section-number">12.4.1</span> Power Analysis Is a Professional Obligation</a></li>
  <li><a href="#power-for-common-designs" id="toc-power-for-common-designs" class="nav-link" data-scroll-target="#power-for-common-designs"><span class="header-section-number">12.4.2</span> Power for Common Designs</a></li>
  <li><a href="#simulation-based-power-for-mixed-models" id="toc-simulation-based-power-for-mixed-models" class="nav-link" data-scroll-target="#simulation-based-power-for-mixed-models"><span class="header-section-number">12.4.3</span> Simulation-Based Power for Mixed Models</a></li>
  <li><a href="#the-workflow" id="toc-the-workflow" class="nav-link" data-scroll-target="#the-workflow"><span class="header-section-number">12.4.4</span> The Workflow</a></li>
  <li><a href="#example-power-for-a-mixed-model-clinical-trial" id="toc-example-power-for-a-mixed-model-clinical-trial" class="nav-link" data-scroll-target="#example-power-for-a-mixed-model-clinical-trial"><span class="header-section-number">12.4.5</span> Example: Power for a Mixed Model Clinical Trial</a></li>
  <li><a href="#reading-the-output" id="toc-reading-the-output" class="nav-link" data-scroll-target="#reading-the-output"><span class="header-section-number">12.4.6</span> Reading the Output</a></li>
  <li><a href="#a-note-on-method-t-vs-method-kr-in-powersim" id="toc-a-note-on-method-t-vs-method-kr-in-powersim" class="nav-link" data-scroll-target="#a-note-on-method-t-vs-method-kr-in-powersim"><span class="header-section-number">12.4.7</span> A Note on <code>method = "t"</code> vs <code>method = "kr"</code> in <code>powerSim</code></a></li>
  <li><a href="#the-key-advantage-over-analytical-power-formulas" id="toc-the-key-advantage-over-analytical-power-formulas" class="nav-link" data-scroll-target="#the-key-advantage-over-analytical-power-formulas"><span class="header-section-number">12.4.8</span> The Key Advantage Over Analytical Power Formulas</a></li>
  <li><a href="#practical-recommendations-for-using-simr" id="toc-practical-recommendations-for-using-simr" class="nav-link" data-scroll-target="#practical-recommendations-for-using-simr"><span class="header-section-number">12.4.9</span> Practical Recommendations for Using <code>simr</code></a></li>
  <li><a href="#reporting-the-power-analysis" id="toc-reporting-the-power-analysis" class="nav-link" data-scroll-target="#reporting-the-power-analysis"><span class="header-section-number">12.4.10</span> Reporting the Power Analysis</a></li>
  <li><a href="#what-must-be-included" id="toc-what-must-be-included" class="nav-link" data-scroll-target="#what-must-be-included"><span class="header-section-number">12.4.11</span> What Must Be Included</a></li>
  <li><a href="#a-common-mistake-reporting-post-hoc-power" id="toc-a-common-mistake-reporting-post-hoc-power" class="nav-link" data-scroll-target="#a-common-mistake-reporting-post-hoc-power"><span class="header-section-number">12.4.12</span> A Common Mistake: Reporting Post Hoc Power</a></li>
  <li><a href="#specifying-the-effect-size-honestly" id="toc-specifying-the-effect-size-honestly" class="nav-link" data-scroll-target="#specifying-the-effect-size-honestly"><span class="header-section-number">12.4.13</span> Specifying the Effect Size Honestly</a></li>
  <li><a href="#the-multiple-testing-problem-in-design" id="toc-the-multiple-testing-problem-in-design" class="nav-link" data-scroll-target="#the-multiple-testing-problem-in-design"><span class="header-section-number">12.4.14</span> The Multiple Testing Problem in Design</a></li>
  <li><a href="#a-design-checklist" id="toc-a-design-checklist" class="nav-link" data-scroll-target="#a-design-checklist"><span class="header-section-number">12.4.15</span> A Design Checklist</a></li>
  </ul>
</li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/Ebedthan/maov/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li><li><a href="https://github.com/Ebedthan/maov/edit/main/05a-experimental-design.qmd" class="toc-action"><i class="bi empty"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-good-practice.html">Good Practice and Reproductibility</a></li><li class="breadcrumb-item"><a href="./05a-experimental-design.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Experimental Design Principles</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-chap12" class="quarto-section-identifier"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Experimental Design Principles</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>Statistical analysis does not begin when you open R. It begins when you decide how to collect your data. <strong>The most sophisticated model cannot rescue an experiment that was poorly designed, it can only make the best of what was given to it, and sometimes not even that</strong>. Fisher understood this at Rothamsted a century ago, and the insight has not aged: the validity of any statistical inference depends on decisions made at the design stage, long before the first observation is recorded.</p>
<p>This chapter returns to first principles. It covers the three foundational concepts that underpin every valid experiment: <strong>randomisation, replication, and blocking</strong>. It shows how to design an experiment with the intended analysis in mind, rather than discovering after data collection that the design and the analysis are mismatched.</p>
<p>It also catalogues the most common design mistakes in biological research and explains why they are mistakes. And it makes the case for prospective power analysis as a <em>professional obligation</em>, not an optional refinement.</p>
<section id="randomisation-replication-and-blocking-the-triad" class="level2" data-number="12.1"><h2 data-number="12.1" class="anchored" data-anchor-id="randomisation-replication-and-blocking-the-triad">
<span class="header-section-number">12.1</span> Randomisation, Replication, and Blocking: The Triad</h2>
<section id="randomisation" class="level3" data-number="12.1.1"><h3 data-number="12.1.1" class="anchored" data-anchor-id="randomisation">
<span class="header-section-number">12.1.1</span> Randomisation</h3>
<p><strong>Randomisation</strong> is the act of assigning experimental units to treatments by a chance mechanism, drawing lots, using a random number generator, or any process that gives every unit an equal probability of receiving any treatment. It is the single most important principle in experimental design, and its importance cannot be overstated.</p>
<p>The reason randomisation matters is subtle but fundamental. Randomisation does not make the treatment groups identical at baseline, with small samples, they may differ considerably by chance. <strong>What randomisation guarantees is that any differences between groups at baseline are due to chance alone, not to any systematic bias in how treatments were assigned.</strong> This means that if we observe a difference in outcomes between groups, we can attribute it to the treatment rather than to a pre-existing difference between the groups.</p>
<p><strong>Without randomisation, confounding is inevitable.</strong> Suppose you assign your healthiest plants to the nitrogen treatment (see the example from chapter <a href="02a-what-is-anova.html" class="quarto-xref"><span>1</span></a>) because they “look like they can handle it.” Any difference in yield between the nitrogen and control groups now reflects both the effect of nitrogen and the pre-existing difference in plant health. These two effects cannot be separated, and <em>the analysis is worthless regardless of how sophisticated the statistics are.</em></p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Randomisation demo in R</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">42</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Proper randomisation: every plant has equal probability</span></span>
<span><span class="co"># of receiving any treatment</span></span>
<span><span class="va">n_plants</span> <span class="op">&lt;-</span> <span class="fl">24</span></span>
<span><span class="va">treatments</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Control"</span>, <span class="st">"Nitrogen"</span>, <span class="st">"Phosphorus"</span><span class="op">)</span>, each <span class="op">=</span> <span class="va">n_plants</span> <span class="op">/</span> <span class="fl">3</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Randomly permute treatment assignments</span></span>
<span><span class="va">random_assignment</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="va">treatments</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Randomised treatment assignments:\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>#&gt; Randomised treatment assignments:</code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">random_assignment</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>#&gt;  [1] "Phosphorus" "Control"    "Control"    "Nitrogen"   "Control"   
#&gt;  [6] "Phosphorus" "Phosphorus" "Nitrogen"   "Control"    "Control"   
#&gt; [11] "Phosphorus" "Nitrogen"   "Phosphorus" "Nitrogen"   "Phosphorus"
#&gt; [16] "Control"    "Phosphorus" "Control"    "Phosphorus" "Control"   
#&gt; [21] "Nitrogen"   "Nitrogen"   "Nitrogen"   "Nitrogen"</code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Simple function to generate a randomised block design</span></span>
<span><span class="va">randomise_blocks</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">n_blocks</span>, <span class="va">treatments</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/do.call.html">do.call</a></span><span class="op">(</span><span class="va">rbind</span>, <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="va">n_blocks</span><span class="op">)</span>, <span class="kw">function</span><span class="op">(</span><span class="va">b</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>      block <span class="op">=</span> <span class="va">b</span>,</span>
<span>      treatment <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="va">treatments</span><span class="op">)</span>,</span>
<span>      unit <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_along</a></span><span class="op">(</span><span class="va">treatments</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span>
<span>  <span class="op">}</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="co"># 4 blocks, 3 treatments per block</span></span>
<span><span class="va">design_df</span> <span class="op">&lt;-</span> <span class="fu">randomise_blocks</span><span class="op">(</span><span class="fl">4</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Control"</span>, <span class="st">"Nitrogen"</span>, <span class="st">"Phosphorus"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">design_df</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>#&gt;    block  treatment unit
#&gt; 1      1    Control    1
#&gt; 2      1   Nitrogen    2
#&gt; 3      1 Phosphorus    3
#&gt; 4      2 Phosphorus    1
#&gt; 5      2   Nitrogen    2
#&gt; 6      2    Control    3
#&gt; 7      3   Nitrogen    1
#&gt; 8      3 Phosphorus    2
#&gt; 9      3    Control    3
#&gt; 10     4 Phosphorus    1
#&gt; 11     4    Control    2
#&gt; 12     4   Nitrogen    3</code></pre>
</div>
</div>
</section><section id="replication" class="level3" data-number="12.1.2"><h3 data-number="12.1.2" class="anchored" data-anchor-id="replication">
<span class="header-section-number">12.1.2</span> Replication</h3>
<p><strong>Replication</strong> means applying each treatment to multiple <em>independent</em> experimental units. Without replication, <em>you cannot estimate the within-treatment variation</em> that forms the denominator of the <span class="math inline">\(F\)</span> ratio, and without that denominator, no inference is possible.</p>
<p>The key word is <strong>independent</strong>. Replication does not mean measuring the same unit multiple times (that is pseudoreplication, see section <a href="02b-assumptions.html#sec-pseudoreplication" class="quarto-xref"><span>2.1.3</span></a>). It means having genuinely separate units, separate plants, separate animals, separate plots, each of which received the treatment independently and contributes an independent piece of information about the treatment effect.</p>
<p>How many replicates are needed? The answer depends on the expected effect size, the within-treatment variability, and the desired power, which is exactly what power analysis quantifies (Section <a href="03a-one-way.html#sec-power-analysis" class="quarto-xref"><span>3.4</span></a> and Section <a href="#sec-sample-size-power" class="quarto-xref"><span>12.4</span></a>). As a rough guide for planning purposes, fewer than 3 replicates per treatment makes any statistical test nearly powerless, 5-8 is adequate for moderate effects, and 10-20 may be needed for small effects or highly variable responses.</p>
</section><section id="blocking" class="level3" data-number="12.1.3"><h3 data-number="12.1.3" class="anchored" data-anchor-id="blocking">
<span class="header-section-number">12.1.3</span> Blocking</h3>
<p><strong>Blocking</strong> is the act of grouping experimental units into homogeneous sets, blocks, before assigning treatments, so that each block contains one unit from each treatment. The purpose is to remove a known source of nuisance variation from the error term, increasing the precision of treatment comparisons.</p>
</section><section id="a-concrete-example-a-field-with-a-fertility-gradient" class="level3" data-number="12.1.4"><h3 data-number="12.1.4" class="anchored" data-anchor-id="a-concrete-example-a-field-with-a-fertility-gradient">
<span class="header-section-number">12.1.4</span> A Concrete Example: A Field With a Fertility Gradient</h3>
<p>Imagine a rectangular field divided into three horizontal strips running east to west. The soil fertility increases from south to north, perhaps because of natural drainage patterns, organic matter accumulation, or historical land use. This gradient will affect crop yield regardless of which fertiliser is applied.</p>
<p>We divide the field into three blocks, South, Middle, and North, each containing three plots. Within each block, we randomly assign one plot to each fertiliser treatment: Control, Nitrogen, and Phosphorus.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="img/fig2.png" class="img-fluid figure-img"></p>
<figcaption>A randomised complete block design in a field with a north-south fertility gradient. The field is divided into three blocks (South, Middle, North) corresponding to low, medium, and high soil fertility. Within each block, the three treatments are randomly assigned to plots. The gradient affects all plots equally within a block, so block-to-block differences can be separated from treatment differences.</figcaption></figure>
</div>
<p>The key feature of this design is that every treatment appears exactly once in every block. Whatever the fertility level of the North block, all three treatments experience it equally, so the block effect cannot be confused with the treatment effect.</p>
</section><section id="the-treatment-error-formula" class="level3" data-number="12.1.5"><h3 data-number="12.1.5" class="anchored" data-anchor-id="the-treatment-error-formula">
<span class="header-section-number">12.1.5</span> The Treatment Error Formula</h3>
<p>Before seeing the benefit of blocking in numbers, recall what the treatment error term actually is. In a one-way ANOVA without blocking, the error mean square is:</p>
<p><span class="math display">\[MS_{\text{error}} = \frac{SS_{\text{error}}}{df_{\text{error}}}
= \frac{\sum_{j=1}^k \sum_{i=1}^{n_j} (y_{ij} - \bar{y}_j)^2}
       {N - k}\]</span></p>
<p>This pools all sources of uncontrolled variation, including the fertility gradient, into a single noise estimate. The F ratio for treatment is:</p>
<p><span class="math display">\[F = \frac{MS_{\text{treatment}}}{MS_{\text{error}}}\]</span></p>
<p>A large <span class="math inline">\(MS_{\text{error}}\)</span> makes this ratio smaller and the test less powerful. Blocking removes the block variation from the numerator of <span class="math inline">\(MS_{\text{error}}\)</span>, leaving a smaller, cleaner noise estimate:</p>
<p><span class="math display">\[MS_{\text{error (blocked)}} =
\frac{SS_{\text{total}} - SS_{\text{treatment}} - SS_{\text{block}}}
     {(k-1)(b-1)}\]</span></p>
<p>where <span class="math inline">\(b\)</span> is the number of blocks. The block sum of squares <span class="math inline">\(SS_{\text{block}}\)</span> is extracted from the error, shrinking <span class="math inline">\(MS_{\text{error}}\)</span> and therefore increasing the F ratio for the treatment comparison.</p>
</section><section id="simulating-the-field-experiment" class="level3" data-number="12.1.6"><h3 data-number="12.1.6" class="anchored" data-anchor-id="simulating-the-field-experiment">
<span class="header-section-number">12.1.6</span> Simulating the Field Experiment</h3>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># The field data, yields assigned to reflect:</span></span>
<span><span class="co"># 1. A real treatment effect (Nitrogen &gt; Phosphorus &gt; Control)</span></span>
<span><span class="co"># 2. A strong north-south fertility gradient</span></span>
<span><span class="co"># 3. Small residual plot-to-plot noise</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">42</span><span class="op">)</span></span>
<span></span>
<span><span class="va">df_field</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  block <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"South"</span>, <span class="st">"Middle"</span>, <span class="st">"North"</span><span class="op">)</span>, each <span class="op">=</span> <span class="fl">3</span><span class="op">)</span>,</span>
<span>  levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"South"</span>, <span class="st">"Middle"</span>, <span class="st">"North"</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  treatment <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>    <span class="st">"Control"</span>,    <span class="st">"Nitrogen"</span>,   <span class="st">"Phosphorus"</span>,  <span class="co"># South block</span></span>
<span>    <span class="st">"Nitrogen"</span>,   <span class="st">"Phosphorus"</span>, <span class="st">"Control"</span>,     <span class="co"># Middle block</span></span>
<span>    <span class="st">"Phosphorus"</span>, <span class="st">"Control"</span>,    <span class="st">"Nitrogen"</span>     <span class="co"># North block</span></span>
<span>  <span class="op">)</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Control"</span>, <span class="st">"Nitrogen"</span>, <span class="st">"Phosphorus"</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  </span>
<span>  <span class="co"># Block fertility gradient: South = low, North = high</span></span>
<span>  <span class="co"># adds 0, 8, 16 units to yields within each block</span></span>
<span>  block_effect <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">8</span>, <span class="fl">16</span><span class="op">)</span>, each <span class="op">=</span> <span class="fl">3</span><span class="op">)</span>,</span>
<span>  </span>
<span>  <span class="co"># True treatment effects: Control = 0, N = 6, P = 3</span></span>
<span>  treatment_effect <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">6</span>, <span class="fl">3</span>,   <span class="co"># South</span></span>
<span>                       <span class="fl">6</span>, <span class="fl">3</span>, <span class="fl">0</span>,   <span class="co"># Middle</span></span>
<span>                       <span class="fl">3</span>, <span class="fl">0</span>, <span class="fl">6</span><span class="op">)</span>   <span class="co"># North</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Observed yield = grand mean + block effect + treatment effect + noise</span></span>
<span><span class="va">df_field</span><span class="op">$</span><span class="va">yield</span> <span class="op">&lt;-</span> <span class="fl">20</span> <span class="op">+</span></span>
<span>  <span class="va">df_field</span><span class="op">$</span><span class="va">block_effect</span> <span class="op">+</span></span>
<span>  <span class="va">df_field</span><span class="op">$</span><span class="va">treatment_effect</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">9</span>, <span class="fl">0</span>, <span class="fl">1.2</span><span class="op">)</span>, <span class="fl">1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The observed yields are:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">df_field</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"block"</span>, <span class="st">"treatment"</span>, <span class="st">"yield"</span><span class="op">)</span><span class="op">]</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;    block  treatment yield
#&gt; 1  South    Control  21.6
#&gt; 2  South   Nitrogen  25.3
#&gt; 3  South Phosphorus  23.4
#&gt; 4 Middle   Nitrogen  34.8
#&gt; 5 Middle Phosphorus  31.5
#&gt; 6 Middle    Control  27.9
#&gt; 7  North Phosphorus  40.8
#&gt; 8  North    Control  35.9
#&gt; 9  North   Nitrogen  44.4</code></pre>
</div>
</div>
</section><section id="computing-the-treatment-error-with-and-without-blocking" class="level3" data-number="12.1.7"><h3 data-number="12.1.7" class="anchored" data-anchor-id="computing-the-treatment-error-with-and-without-blocking">
<span class="header-section-number">12.1.7</span> Computing the Treatment Error: With and Without Blocking</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Analysis WITHOUT blocking</span></span>
<span><span class="co"># All variation not explained by treatment goes into the error</span></span>
<span><span class="va">fit_no_block</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">yield</span> <span class="op">~</span> <span class="va">treatment</span>, data <span class="op">=</span> <span class="va">df_field</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ss_treat_nb</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_no_block</span><span class="op">)</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="st">"treatment"</span>, <span class="st">"Sum Sq"</span><span class="op">]</span></span>
<span><span class="va">ss_error_nb</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_no_block</span><span class="op">)</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="st">"Residuals"</span>, <span class="st">"Sum Sq"</span><span class="op">]</span></span>
<span><span class="va">df_error_nb</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_no_block</span><span class="op">)</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="st">"Residuals"</span>, <span class="st">"Df"</span><span class="op">]</span></span>
<span><span class="va">ms_error_nb</span> <span class="op">&lt;-</span> <span class="va">ss_error_nb</span> <span class="op">/</span> <span class="va">df_error_nb</span></span>
<span><span class="va">f_nb</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_no_block</span><span class="op">)</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="st">"treatment"</span>, <span class="st">"F value"</span><span class="op">]</span></span>
<span><span class="va">p_nb</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_no_block</span><span class="op">)</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="st">"treatment"</span>, <span class="st">"Pr(&gt;F)"</span><span class="op">]</span></span>
<span></span>
<span><span class="co"># Analysis WITH blocking </span></span>
<span><span class="co"># Block variation is extracted from the error</span></span>
<span><span class="va">fit_blocked</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">yield</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="va">block</span>, data <span class="op">=</span> <span class="va">df_field</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ss_treat_b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_blocked</span><span class="op">)</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="st">"treatment"</span>, <span class="st">"Sum Sq"</span><span class="op">]</span></span>
<span><span class="va">ss_block</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_blocked</span><span class="op">)</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="st">"block"</span>, <span class="st">"Sum Sq"</span><span class="op">]</span></span>
<span><span class="va">ss_error_b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_blocked</span><span class="op">)</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="st">"Residuals"</span>, <span class="st">"Sum Sq"</span><span class="op">]</span></span>
<span><span class="va">df_error_b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_blocked</span><span class="op">)</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="st">"Residuals"</span>, <span class="st">"Df"</span><span class="op">]</span></span>
<span><span class="va">ms_error_b</span> <span class="op">&lt;-</span> <span class="va">ss_error_b</span> <span class="op">/</span> <span class="va">df_error_b</span></span>
<span><span class="va">f_b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_blocked</span><span class="op">)</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="st">"treatment"</span>, <span class="st">"F value"</span><span class="op">]</span></span>
<span><span class="va">p_b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_blocked</span><span class="op">)</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="st">"treatment"</span>, <span class="st">"Pr(&gt;F)"</span><span class="op">]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span></span>
<span>  <span class="st">"=== WITHOUT blocking ===\nSS treatment: "</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">ss_treat_nb</span>, <span class="fl">2</span><span class="op">)</span>, </span>
<span>  <span class="st">"\nSS error:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">ss_error_nb</span>, <span class="fl">2</span><span class="op">)</span>,</span>
<span>  <span class="st">"(includes block gradient)\ndf error:"</span>,</span>
<span>  <span class="va">df_error_nb</span>, <span class="st">"\nMS error:"</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">ms_error_nb</span>, <span class="fl">2</span><span class="op">)</span>, <span class="st">"\nF value:"</span>, </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">f_nb</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">"\np-value:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">p_nb</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">"\n\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>#&gt; === WITHOUT blocking ===
#&gt; SS treatment:  60.93 
#&gt; SS error: 436.75 (includes block gradient)
#&gt; df error: 6 
#&gt; MS error: 72.79 
#&gt; F value: 0.418 
#&gt; p-value: 0.676</code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span></span>
<span>  <span class="st">"=== WITH blocking ===\nSS treatment: "</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">ss_treat_b</span>, <span class="fl">2</span><span class="op">)</span>,</span>
<span>  <span class="st">"\nSS block:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">ss_block</span>, <span class="fl">2</span><span class="op">)</span>,</span>
<span>  <span class="st">"(extracted from error)\nSS error:"</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">ss_error_b</span>, <span class="fl">2</span><span class="op">)</span>,</span>
<span>  <span class="st">"(block gradient removed)\ndf error:"</span>,</span>
<span>  <span class="va">df_error_b</span>, <span class="st">"\nMS error:"</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">ms_error_b</span>, <span class="fl">2</span><span class="op">)</span>,</span>
<span>  <span class="st">"\nF value:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">f_b</span>, <span class="fl">3</span><span class="op">)</span>,</span>
<span>  <span class="st">"\np-value:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">p_b</span>,  <span class="fl">3</span><span class="op">)</span>, <span class="st">"\n\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>#&gt; === WITH blocking ===
#&gt; SS treatment:  60.93 
#&gt; SS block: 430.61 (extracted from error)
#&gt; SS error: 6.15 (block gradient removed)
#&gt; df error: 4 
#&gt; MS error: 1.54 
#&gt; F value: 19.824 
#&gt; p-value: 0.008</code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span></span>
<span>  <span class="st">"=== Summary ===\nMS error reduced from"</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">ms_error_nb</span>, <span class="fl">2</span><span class="op">)</span>, <span class="st">"to"</span>, </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">ms_error_b</span>, <span class="fl">2</span><span class="op">)</span>, </span>
<span>  <span class="st">"by blocking\nF value increased from"</span>, </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">f_nb</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">"to"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">f_b</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>#&gt; === Summary ===
#&gt; MS error reduced from 72.79 to 1.54 by blocking
#&gt; F value increased from 0.418 to 19.824</code></pre>
</div>
</div>
<p>The two analyses use identical data, the same nine yield observations from the same nine plots. The only difference is whether the block structure is accounted for in the model.</p>
<p>Without blocking, the <span class="math inline">\(SS_{\text{error}}\)</span> includes both the genuine residual plot noise and the large fertility gradient running from south to north. This inflates <span class="math inline">\(MS_{\text{error}}\)</span>, shrinks the F ratio, and makes the treatment differences harder to detect.</p>
<p>With blocking, the <span class="math inline">\(SS_{\text{block}}\)</span> is extracted from what would otherwise be the error. The <span class="math inline">\(SS_{\text{error}}\)</span> now contains only the genuine residual noise that is the small, uncontrollable plot-to-plot differences that remain after removing both the treatment effect and the block gradient. The <span class="math inline">\(MS_{\text{error}}\)</span> drops substantially, the F ratio rises, and the p-value falls. This happens not because the data have changed, but because the analysis is now asking the right question: do treatments differ after accounting for the known gradient?</p>
<p>This is the mechanical benefit of blocking stated precisely: it moves known variation out of the error term, leaving a cleaner and smaller noise estimate against which the treatment effect is judged.</p>
</section><section id="reading-the-numbers" class="level3" data-number="12.1.8"><h3 data-number="12.1.8" class="anchored" data-anchor-id="reading-the-numbers">
<span class="header-section-number">12.1.8</span> Reading the Numbers</h3>
<p>The two analyses use identical data, the same nine yield observations from the same nine plots. The only difference is whether the block structure is accounted for in the model, and the consequences are dramatic.</p>
<p><strong>Without blocking</strong>, <span class="math inline">\(SS_{\text{error}} = 436.75\)</span> against a <span class="math inline">\(SS_{\text{treatment}} = 60.93\)</span>. The error sum of squares is more than seven times larger than the treatment sum of squares because it contains the entire north-south fertility gradient, 430 units worth of variation that has nothing to do with fertiliser but is lumped into the noise. The resulting <span class="math inline">\(MS_{\text{error}} = 72.79\)</span> overwhelms the treatment signal, producing <span class="math inline">\(F_{2,6} = 0.418\)</span> and <span class="math inline">\(p = 0.676\)</span>. A researcher using this analysis would conclude that fertiliser has no detectable effect which would be a false negative caused entirely by a preventable design flaw.</p>
<p><strong>With blocking</strong>, the picture reverses completely. <span class="math inline">\(SS_{\text{block}} = 430.61\)</span> is extracted from the error and placed in its own term, this is the fertility gradient, accounted for and set aside. What remains in <span class="math inline">\(SS_{\text{error}}\)</span> is only <span class="math inline">\(6.15\)</span>: the genuine plot-to-plot residual noise after removing both the treatment effect and the gradient. <span class="math inline">\(MS_{\text{error}}\)</span> drops from 72.79 to 1.54, a 47-fold reduction, and the <span class="math inline">\(F\)</span> ratio climbs from 0.418 to <span class="math inline">\(F_{2,4} = 19.82\)</span>, with <span class="math inline">\(p = 0.008\)</span>.</p>
<p>The <span class="math inline">\(SS_{\text{treatment}}\)</span> is identical in both analyses, 60.93 in both cases. The treatment effect in the data has not changed. What changed is the denominator of the F ratio: by removing the gradient from the error term, the analysis can finally hear the treatment signal above the noise.</p>
<p>Two additional details are worth noting. First, the blocked analysis has fewer error degrees of freedom (<span class="math inline">\(df = 4\)</span> instead of <span class="math inline">\(df = 6\)</span>) because two degrees of freedom were spent estimating the block effects. Despite this loss, the test is far more powerful which is a direct consequence of the enormous reduction in <span class="math inline">\(MS_{\text{error}}\)</span>. Second, this example is not contrived: a fertility gradient with <span class="math inline">\(SS_{\text{block}} = 430\)</span> versus a residual of <span class="math inline">\(SS_{\text{error}} = 6\)</span> is entirely realistic in agricultural and ecological field experiments. Gradients of this magnitude are common, which is precisely why blocking has been standard practice in field experimentation since Fisher’s time at Rothamsted.</p>
<p>The practical lesson is unambiguous: <strong>if you know a gradient exists, block on it before you randomise.</strong> Failing to do so does not just reduce power, as these numbers show, it can make a real and substantial treatment effect completely invisible.</p>
</section><section id="when-to-block" class="level3" data-number="12.1.9"><h3 data-number="12.1.9" class="anchored" data-anchor-id="when-to-block">
<span class="header-section-number">12.1.9</span> When to Block</h3>
<p>Block when there is a known, measurable source of variation that will affect the response but is not the treatment of interest. Common blocking factors in biology include:</p>
<ul>
<li>
<strong>Spatial position</strong>: location in a greenhouse, field, or laboratory bench.</li>
<li>
<strong>Temporal batches</strong>: animals processed on different days, assays run in different batches, samples collected in different seasons.</li>
<li>
<strong>Individual characteristics</strong>: litters in animal experiments, maternal plants in seed studies, patients recruited from different centres.</li>
</ul>
<p>Do not block on variables that are themselves affected by the treatment as this introduces bias. And do not block on a variable that is unrelated to the response: adding an irrelevant block factor costs degrees of freedom from the error term and can actually reduce power.</p>
</section></section><section id="designing-for-the-anova-you-want-to-run" class="level2" data-number="12.2"><h2 data-number="12.2" class="anchored" data-anchor-id="designing-for-the-anova-you-want-to-run">
<span class="header-section-number">12.2</span> Designing for the ANOVA You Want to Run</h2>
<section id="start-with-the-analysis" class="level3" data-number="12.2.1"><h3 data-number="12.2.1" class="anchored" data-anchor-id="start-with-the-analysis">
<span class="header-section-number">12.2.1</span> Start With the Analysis</h3>
<p>The most common design error in biology is designing an experiment without thinking about how it will be analysed. The design and the analysis are not separate activities, they are two sides of the same coin. Every feature of the design has a direct counterpart in the statistical model, and mismatches between design and analysis are the primary source of invalid inference.</p>
<p>The practical discipline is to write the analysis plan, including the model formula (in R), before collecting any data:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Write your intended model formula before data collection</span></span>
<span><span class="co"># One-way ANOVA</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">response</span> <span class="op">~</span> <span class="va">treatment</span>, data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Randomised complete block design</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">response</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="va">block</span>, data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Two-way factorial</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">response</span> <span class="op">~</span> <span class="va">factorA</span> <span class="op">*</span> <span class="va">factorB</span>, data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Split-plot</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">response</span> <span class="op">~</span> <span class="va">whole_plot_factor</span> <span class="op">*</span> <span class="va">subplot_factor</span> <span class="op">+</span></span>
<span>      <span class="fu">Error</span><span class="op">(</span><span class="va">whole_plot_unit</span> <span class="op">/</span> <span class="va">subplot_factor</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Repeated measures</span></span>
<span><span class="fu">lmerTest</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lmerTest/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">response</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">*</span> <span class="va">time</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">subject</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Nested design</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">response</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="fu">Error</span><span class="op">(</span><span class="va">block</span> <span class="op">/</span> <span class="va">subplot</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Writing the formula in advance forces you to identify the experimental unit, the error term, and the random effects structure before the data are collected. If you cannot write the formula, the design is not yet fully specified.</p>
</section><section id="match-the-unit-of-analysis-to-the-unit-of-randomisation" class="level3" data-number="12.2.2"><h3 data-number="12.2.2" class="anchored" data-anchor-id="match-the-unit-of-analysis-to-the-unit-of-randomisation">
<span class="header-section-number">12.2.2</span> Match the Unit of Analysis to the Unit of Randomisation</h3>
<p>The experimental unit, the entity that received the treatment independently, must be the unit of analysis. This principle, stated simply, prevents most cases of pseudoreplication.</p>
<p>A decision tree for identifying the experimental unit:</p>
<ul>
<li>What was randomly assigned to receive the treatment?</li>
<li>Could two observations have received different treatments? If no, they are from the same experimental unit.</li>
<li>Is the treatment applied to groups of individuals, or to individuals separately?</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Example 1: Correct, individual plants randomised to treatment</span></span>
<span><span class="co"># Experimental unit = plant, n = 20 per treatment</span></span>
<span><span class="va">df_correct</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  yield <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">60</span>, mean <span class="op">=</span> <span class="fl">20</span>, sd <span class="op">=</span> <span class="fl">3</span><span class="op">)</span>,</span>
<span>  treatment <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"C"</span><span class="op">)</span>, each <span class="op">=</span> <span class="fl">20</span><span class="op">)</span>,</span>
<span>  plant <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">60</span></span>
<span><span class="op">)</span></span>
<span><span class="co"># Correct analysis: plant is the unit</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">yield</span> <span class="op">~</span> <span class="va">treatment</span>, data <span class="op">=</span> <span class="va">df_correct</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;             Df Sum Sq Mean Sq F value Pr(&gt;F)
#&gt; treatment    2   28.2   14.12   1.234  0.299
#&gt; Residuals   57  652.1   11.44</code></pre>
</div>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Example 2: Wrong, treatment applied to cages,</span></span>
<span><span class="co"># multiple animals measured per cage</span></span>
<span><span class="co"># Experimental unit = cage (n = 4 per treatment),</span></span>
<span><span class="co"># not animal (n = 20 per treatment)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">42</span><span class="op">)</span></span>
<span><span class="va">cage_effect</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">12</span>, <span class="fl">0</span>, <span class="fl">2</span><span class="op">)</span>   <span class="co"># 4 cages per treatment</span></span>
<span><span class="va">df_pseudo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  weight <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">12</span>, <span class="kw">function</span><span class="op">(</span><span class="va">c</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">5</span>, mean <span class="op">=</span> <span class="fl">20</span> <span class="op">+</span> <span class="va">cage_effect</span><span class="op">[</span><span class="va">c</span><span class="op">]</span>, sd <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span></span>
<span>  <span class="op">}</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  treatment <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"C"</span><span class="op">)</span>, each <span class="op">=</span> <span class="fl">4</span><span class="op">)</span>, each <span class="op">=</span> <span class="fl">5</span><span class="op">)</span>,</span>
<span>  cage <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">12</span>, each <span class="op">=</span> <span class="fl">5</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Wrong: treats animals as independent</span></span>
<span><span class="va">wrong_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">weight</span> <span class="op">~</span> <span class="va">treatment</span>, data <span class="op">=</span> <span class="va">df_pseudo</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Wrong analysis df (error):"</span>,</span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">wrong_fit</span><span class="op">)</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="st">"Residuals"</span>, <span class="st">"Df"</span><span class="op">]</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Wrong analysis df (error): 57</code></pre>
</div>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Correct: uses cage means</span></span>
<span><span class="va">cage_means</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aggregate.html">aggregate</a></span><span class="op">(</span><span class="va">weight</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="va">cage</span>,</span>
<span>                        data <span class="op">=</span> <span class="va">df_pseudo</span>, FUN <span class="op">=</span> <span class="va">mean</span><span class="op">)</span></span>
<span><span class="va">correct_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">weight</span> <span class="op">~</span> <span class="va">treatment</span>, data <span class="op">=</span> <span class="va">cage_means</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Correct analysis df (error):"</span>,</span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">correct_fit</span><span class="op">)</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="st">"Residuals"</span>, <span class="st">"Df"</span><span class="op">]</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Correct analysis df (error): 9</code></pre>
</div>
</div>
</section><section id="anticipate-the-covariance-structure" class="level3" data-number="12.2.3"><h3 data-number="12.2.3" class="anchored" data-anchor-id="anticipate-the-covariance-structure">
<span class="header-section-number">12.2.3</span> Anticipate the Covariance Structure</h3>
<p>If the design involves repeated measurements, nested units, or crossed random effects, specify the covariance structure before data collection and verify that the intended model is identifiable given the planned sample sizes. A three-level nested model requires sufficient replication at every level, and “sufficient” means at least 3-4 units per level for variance components to be estimated at all, and ideally 10-15 for reliable estimation.</p>
</section></section><section id="common-design-mistakes-in-biology-and-how-to-avoid-them" class="level2" data-number="12.3"><h2 data-number="12.3" class="anchored" data-anchor-id="common-design-mistakes-in-biology-and-how-to-avoid-them">
<span class="header-section-number">12.3</span> Common Design Mistakes in Biology and How to Avoid Them</h2>
<section id="mistake-1-pseudoreplication" class="level3" data-number="12.3.1"><h3 data-number="12.3.1" class="anchored" data-anchor-id="mistake-1-pseudoreplication">
<span class="header-section-number">12.3.1</span> Mistake 1: Pseudoreplication</h3>
<p>Already covered in depth in sections <a href="02b-assumptions.html#sec-pseudoreplication" class="quarto-xref"><span>2.1.3</span></a> and <a href="03e-split-plot-nested.html#sec-pseudoreplication2" class="quarto-xref"><span>7.2</span></a>, but worth restating as a design principle: <strong>never confuse the unit of measurement with the unit of replication.</strong> The most reliable protection is to draw the hierarchy explicitly before data collection (fields contain plots contain plants) and verify that the treatment is randomised at the level you intend to analyse.</p>
</section><section id="mistake-2-confounding-treatment-with-a-nuisance-variable" class="level3" data-number="12.3.2"><h3 data-number="12.3.2" class="anchored" data-anchor-id="mistake-2-confounding-treatment-with-a-nuisance-variable">
<span class="header-section-number">12.3.2</span> Mistake 2: Confounding Treatment With a Nuisance Variable</h3>
<p>Confounding occurs when a nuisance variable is systematically associated with the treatment, making it impossible to separate their effects. The classic example: all control pots placed on the north bench and all nitrogen pots placed on the south bench. Any observed difference in yield now conflates the treatment effect with the bench position effect.</p>
<p>The remedy is randomisation, but randomisation must be applied at the right level and genuinely implemented:</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Confounded design</span></span>
<span><span class="va">df_confounded</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  yield <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">10</span>, mean <span class="op">=</span> <span class="fl">18</span>, sd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span>,  <span class="co"># Control, shaded</span></span>
<span>                <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">10</span>, mean <span class="op">=</span> <span class="fl">24</span>, sd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span><span class="op">)</span>,  <span class="co"># Nitrogen, sunny</span></span>
<span>  treatment <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Control"</span>, <span class="st">"Nitrogen"</span><span class="op">)</span>, each <span class="op">=</span> <span class="fl">10</span><span class="op">)</span>,</span>
<span>  position <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Shaded"</span>, <span class="st">"Sunny"</span><span class="op">)</span>, each <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Randomised design</span></span>
<span><span class="va">df_randomised</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  yield <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">10</span>, mean <span class="op">=</span> <span class="fl">20</span>, sd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span>,  <span class="co"># Control, mixed</span></span>
<span>                <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">10</span>, mean <span class="op">=</span> <span class="fl">24</span>, sd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span><span class="op">)</span>,  <span class="co"># Nitrogen, mixed</span></span>
<span>  treatment <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Control"</span>, <span class="st">"Nitrogen"</span><span class="op">)</span>, each <span class="op">=</span> <span class="fl">10</span><span class="op">)</span>,</span>
<span>  position <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Shaded"</span>, <span class="st">"Sunny"</span><span class="op">)</span>, <span class="fl">10</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">p1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">df_confounded</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">treatment</span>, y <span class="op">=</span> <span class="va">yield</span>, colour <span class="op">=</span> <span class="va">position</span>, shape <span class="op">=</span> <span class="va">position</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.1</span>, size <span class="op">=</span> <span class="fl">3</span>, alpha <span class="op">=</span> <span class="fl">0.8</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#2E86AB"</span>, <span class="st">"#F6AE2D"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Confounded design"</span>,</span>
<span>       subtitle <span class="op">=</span> <span class="st">"Treatment perfectly correlated with position"</span>,</span>
<span>       x <span class="op">=</span> <span class="cn">NULL</span>, y <span class="op">=</span> <span class="st">"Yield"</span>,</span>
<span>       colour <span class="op">=</span> <span class="st">"Position"</span>, shape <span class="op">=</span> <span class="st">"Position"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">df_randomised</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">treatment</span>, y <span class="op">=</span> <span class="va">yield</span>,</span>
<span>                 colour <span class="op">=</span> <span class="va">position</span>, shape <span class="op">=</span> <span class="va">position</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.1</span>, size <span class="op">=</span> <span class="fl">3</span>, alpha <span class="op">=</span> <span class="fl">0.8</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#2E86AB"</span>, <span class="st">"#F6AE2D"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Randomised design"</span>,</span>
<span>       subtitle <span class="op">=</span> <span class="st">"Both positions represented in both treatments"</span>,</span>
<span>       x <span class="op">=</span> <span class="cn">NULL</span>, y <span class="op">=</span> <span class="st">"Yield"</span>,</span>
<span>       colour <span class="op">=</span> <span class="st">"Position"</span>, shape <span class="op">=</span> <span class="st">"Position"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p1</span> <span class="op">+</span> <span class="va">p2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div id="fig-confounding-demo" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-confounding-demo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05a-experimental-design_files/figure-html/fig-confounding-demo-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-confounding-demo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.1: Confounding illustrated. Left: a confounded design where all Control plants are on the shaded side of the greenhouse and all Nitrogen plants are on the sunny side. Any observed difference conflates treatment with light availability. Right: a properly randomised design where both treatments are represented on both sides, eliminating the confound.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="mistake-3-insufficient-replication-at-the-right-level" class="level3" data-number="12.3.3"><h3 data-number="12.3.3" class="anchored" data-anchor-id="mistake-3-insufficient-replication-at-the-right-level">
<span class="header-section-number">12.3.3</span> Mistake 3: Insufficient Replication at the Right Level</h3>
<p>Researchers sometimes add subsamples to increase apparent sample size without adding true replication. Five soil cores per plot does not give you five replicates: it gives you one plot measured five times. The number that matters for the treatment comparison is the number of independently treated plots, not the number of measurements per plot.</p>
<p>The consequence is not merely conservative, it is incorrect. As Sections <a href="02b-assumptions.html#sec-pseudoreplication" class="quarto-xref"><span>2.1.3</span></a> and <a href="03e-split-plot-nested.html#sec-pseudoreplication2" class="quarto-xref"><span>7.2</span></a> demonstrated, treating subsamples as replicates can inflate the false positive rate to 25% or higher.</p>
<p>A practical check: if you removed four of your five subsamples per plot, would you lose replication for the treatment comparison? If no (if the treatment comparison is still based on the same number of plots) the subsamples are providing precision within plots, not replication for treatments.</p>
</section><section id="mistake-4-unbalanced-designs-by-negligence" class="level3" data-number="12.3.4"><h3 data-number="12.3.4" class="anchored" data-anchor-id="mistake-4-unbalanced-designs-by-negligence">
<span class="header-section-number">12.3.4</span> Mistake 4: Unbalanced Designs by Negligence</h3>
<p>Some imbalance is inevitable, animals die, samples are lost, patients drop out. But imbalance that arises from avoidable causes, not randomising properly, not accounting for expected dropout or not over-recruiting to compensate, creates unnecessary analytical complications (Section <a href="03c-two-way.html#sec-unbalanced" class="quarto-xref"><span>5.4</span></a>) and reduces power.</p>
<p>The practical remedy is simple: <strong>over-recruit by 10-20% per cell</strong> when dropout or loss is anticipated, and document the expected attrition rate in the analysis plan. If dropout is systematic rather than random, sicker patients are more likely to drop out, the resulting missing data problem cannot be solved by over-recruiting and requires explicit handling in the analysis.</p>
</section><section id="mistake-5-measuring-the-wrong-response-variable" class="level3" data-number="12.3.5"><h3 data-number="12.3.5" class="anchored" data-anchor-id="mistake-5-measuring-the-wrong-response-variable">
<span class="header-section-number">12.3.5</span> Mistake 5: Measuring the Wrong Response Variable</h3>
<p>Choosing a response variable that is insensitive to the treatment, or that is measured too imprecisely, undermines the experiment regardless of how well it is designed. Two principles apply.</p>
<p><strong>Measure as close to the biological process of interest as possible.</strong> If you want to know whether a drug reduces inflammation, measure the inflammatory marker directly, not a distal outcome that may be affected by many other factors.</p>
<p><strong>Use the most precise measurement available within practical constraints.</strong> A continuous measurement (tumour volume in mm³) is almost always more informative than a binary one (tumour present/absent), and requires a smaller sample size to achieve the same power.</p>
</section><section id="mistake-6-ignoring-the-temporal-structure" class="level3" data-number="12.3.6"><h3 data-number="12.3.6" class="anchored" data-anchor-id="mistake-6-ignoring-the-temporal-structure">
<span class="header-section-number">12.3.6</span> Mistake 6: Ignoring the Temporal Structure</h3>
<p>In longitudinal studies, the order of measurements matters. Pre-treatment baseline measurements are not the same as post-treatment measurements, and treating all time points as exchangeable, as if the order were arbitrary, discards information and can introduce bias.</p>
<p>The correct approach is to use the baseline measurement as a covariate (ANCOVA) or to model time explicitly as a within-subject factor (repeated measures ANOVA or mixed model). Either approach extracts more information from the data than ignoring the temporal structure.</p>
</section></section><section id="sec-sample-size-power" class="level2" data-number="12.4"><h2 data-number="12.4" class="anchored" data-anchor-id="sec-sample-size-power">
<span class="header-section-number">12.4</span> Sample Size and Power Before the Experiment, Not After</h2>
<section id="power-analysis-is-a-professional-obligation" class="level3" data-number="12.4.1"><h3 data-number="12.4.1" class="anchored" data-anchor-id="power-analysis-is-a-professional-obligation">
<span class="header-section-number">12.4.1</span> Power Analysis Is a Professional Obligation</h3>
<p>Power analysis was introduced in Section 3.4 in the context of one-way ANOVA. Here we revisit it as a design principle that applies to every experiment in this book, not just one-way ANOVA.</p>
<p>Running an underpowered experiment is not merely a missed opportunity, it is a waste of resources, animal lives, or patient time, and it produces results that cannot be trusted. A non-significant result from an underpowered study tells you almost nothing: the effect might be absent, or it might be real but too small for the study to detect. These two conclusions are not the same, and conflating them has contributed significantly to the replication crisis in biological research.</p>
<p>Power analysis before the experiment forces you to commit to:</p>
<ol type="1">
<li>A specific effect size of scientific interest.</li>
<li>A sample size that gives adequate power to detect it.</li>
<li>A significance threshold you will use for the analysis.</li>
</ol>
<p>All three must be specified before data collection. Adjusting them after seeing the data, stopping early because the result is significant, or continuing because it is not, invalidates the analysis.</p>
</section><section id="power-for-common-designs" class="level3" data-number="12.4.2"><h3 data-number="12.4.2" class="anchored" data-anchor-id="power-for-common-designs">
<span class="header-section-number">12.4.2</span> Power for Common Designs</h3>
<p>The <code>pwr</code> package handles power analysis for standard ANOVA designs. For mixed models and GLMMs, simulation-based power analysis is the most flexible approach.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/heliosdrm/pwr">pwr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># One-way ANOVA: medium effect, 80% power, 3 groups</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.anova.test.html">pwr.anova.test</a></span><span class="op">(</span>k <span class="op">=</span> <span class="fl">3</span>, f <span class="op">=</span> <span class="fl">0.25</span>, sig.level <span class="op">=</span> <span class="fl">0.05</span>, power <span class="op">=</span> <span class="fl">0.80</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt;      Balanced one-way analysis of variance power calculation 
#&gt; 
#&gt;               k = 3
#&gt;               n = 52.3966
#&gt;               f = 0.25
#&gt;       sig.level = 0.05
#&gt;           power = 0.8
#&gt; 
#&gt; NOTE: n is number in each group</code></pre>
</div>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Two-way ANOVA: using simulation for more complex designs</span></span>
<span><span class="co"># How many subjects per cell for a 2x3 factorial</span></span>
<span><span class="co"># to detect a medium interaction effect?</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.anova.test.html">pwr.anova.test</a></span><span class="op">(</span>k <span class="op">=</span> <span class="fl">6</span>,    <span class="co"># 2x3 = 6 cells treated as one-way</span></span>
<span>               f <span class="op">=</span> <span class="fl">0.25</span>,</span>
<span>               sig.level <span class="op">=</span> <span class="fl">0.05</span>,</span>
<span>               power <span class="op">=</span> <span class="fl">0.80</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt;      Balanced one-way analysis of variance power calculation 
#&gt; 
#&gt;               k = 6
#&gt;               n = 35.14095
#&gt;               f = 0.25
#&gt;       sig.level = 0.05
#&gt;           power = 0.8
#&gt; 
#&gt; NOTE: n is number in each group</code></pre>
</div>
</div>
</section><section id="simulation-based-power-for-mixed-models" class="level3" data-number="12.4.3"><h3 data-number="12.4.3" class="anchored" data-anchor-id="simulation-based-power-for-mixed-models">
<span class="header-section-number">12.4.3</span> Simulation-Based Power for Mixed Models</h3>
<p>For mixed models where analytical power formulas are unavailable, the <code>simr</code> package <span class="citation" data-cites="Green2016">(<a href="references.html#ref-Green2016" role="doc-biblioref">Green and MacLeod 2016</a>)</span> provides a principled and flexible simulation-based approach. Rather than requiring you to derive a power formula, <code>simr</code> works directly with a fitted <code>lmer</code> or <code>glmer</code> object: it simulates new response values from the model, refits the model to each simulated dataset, and counts how often the effect of interest reaches significance. This means the power calculation automatically accounts for the random effects structure, the covariance components, and the degrees of freedom approximation, all of which analytical formulas would need to assume away.</p>
</section><section id="the-workflow" class="level3" data-number="12.4.4"><h3 data-number="12.4.4" class="anchored" data-anchor-id="the-workflow">
<span class="header-section-number">12.4.4</span> The Workflow</h3>
<p>The <code>simr</code> workflow has three steps:</p>
<ol type="1">
<li>Fit a model with the structure you intend to use, either to pilot data or to a simulated dataset with plausible parameter values.</li>
<li>Set the fixed effect of interest to the minimum biologically meaningful effect size.</li>
<li>Call <code><a href="https://rdrr.io/pkg/simr/man/powerSim.html">powerSim()</a></code> to estimate power at the current sample size, or <code><a href="https://rdrr.io/pkg/simr/man/powerCurve.html">powerCurve()</a></code> to trace power across a range of sample sizes.</li>
</ol></section><section id="example-power-for-a-mixed-model-clinical-trial" class="level3" data-number="12.4.5"><h3 data-number="12.4.5" class="anchored" data-anchor-id="example-power-for-a-mixed-model-clinical-trial">
<span class="header-section-number">12.4.5</span> Example: Power for a Mixed Model Clinical Trial</h3>
<p>We return to the cardiac rehabilitation trial from Chapter <a href="04b-mixed-effects.html" class="quarto-xref"><span>9</span></a> (<a href="appendix-b-packages.html#sec-physio" class="quarto-xref"><span>Section B.1.7</span></a>): patients nested within hospitals, treatment as a fixed effect, random intercept for hospital. We want to know how many patients per hospital are needed to detect a treatment effect of 5 recovery points with 80% power.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># install.packages("simr") if needed</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/pitakakariki/simr">simr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/lme4/lme4/">lme4</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Fit the intended model</span></span>
<span><span class="va">fit_pilot</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span></span>
<span>  <span class="va">recovery</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">hospital</span><span class="op">)</span>,</span>
<span>  data <span class="op">=</span> <span class="va">physio</span>,</span>
<span>  REML <span class="op">=</span> <span class="cn">TRUE</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Step 2: Set the treatment effect to the minimum</span></span>
<span><span class="co"># biologically meaningful difference; here, 5 recovery points</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/nlme/man/fixed.effects.html">fixef</a></span><span class="op">(</span><span class="va">fit_pilot</span><span class="op">)</span><span class="op">[</span><span class="st">"treatmentTreatment"</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fl">5</span></span>
<span></span>
<span><span class="co"># Step 3a: Estimate power at the current sample size</span></span>
<span><span class="co"># Power curve across patients per hospital</span></span>
<span><span class="va">power_current</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/simr/man/powerSim.html">powerSim</a></span><span class="op">(</span><span class="va">fit_pilot</span>, test <span class="op">=</span> <span class="fu">fixed</span><span class="op">(</span><span class="st">"treatmentTreatment"</span>, method <span class="op">=</span> <span class="st">"t"</span><span class="op">)</span>, progress <span class="op">=</span> <span class="cn">FALSE</span>, nsim <span class="op">=</span> <span class="fl">100</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">power_current</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Power for predictor 'treatmentTreatment', (95% confidence interval):
#&gt;       96.00% (90.07, 98.90)
#&gt; 
#&gt; Test: t-test with Satterthwaite degrees of freedom (package lmerTest)
#&gt;       Effect size for treatmentTreatment is 5.0
#&gt; 
#&gt; Based on 100 simulations, (0 errors, 0 warnings, 0 messages)
#&gt; 
#&gt; Time elapsed: 0 h 0 m 10 s</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Step 3b: Trace power across a range of patient numbers</span></span>
<span><span class="co"># by extending the dataset using extend()</span></span>
<span></span>
<span><span class="co"># Extend within hospitals: vary number of patients per hospital</span></span>
<span><span class="va">fit_extended_within</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/simr/man/extend.html">extend</a></span><span class="op">(</span></span>
<span>  <span class="va">fit_pilot</span>,</span>
<span>  within <span class="op">=</span> <span class="st">"hospital"</span>,</span>
<span>  n      <span class="op">=</span> <span class="fl">30</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Power curve across patients per hospital</span></span>
<span><span class="va">power_curve</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/simr/man/powerCurve.html">powerCurve</a></span><span class="op">(</span></span>
<span>  <span class="va">fit_extended_within</span>,</span>
<span>  test   <span class="op">=</span> <span class="fu">fixed</span><span class="op">(</span><span class="st">"treatmentTreatment"</span>, method <span class="op">=</span> <span class="st">"t"</span><span class="op">)</span>,</span>
<span>  within <span class="op">=</span> <span class="st">"hospital"</span>,</span>
<span>  breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">8</span>, <span class="fl">10</span>, <span class="fl">15</span>, <span class="fl">20</span>, <span class="fl">25</span>, <span class="fl">30</span><span class="op">)</span>,</span>
<span>  nsim   <span class="op">=</span> <span class="fl">100</span>,</span>
<span>  progress <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">power_curve</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Power for predictor 'treatmentTreatment', (95% confidence interval),
#&gt; by number of observations within hospital:
#&gt;       5: 77.00% (67.51, 84.83) - 75 rows
#&gt;       8: 92.00% (84.84, 96.48) - 120 rows
#&gt;      10: 95.00% (88.72, 98.36) - 150 rows
#&gt;      15: 100.0% (96.38, 100.0) - 225 rows
#&gt;      20: 100.0% (96.38, 100.0) - 300 rows
#&gt;      25: 100.0% (96.38, 100.0) - 361 rows
#&gt;      30: 100.0% (96.38, 100.0) - 386 rows
#&gt; 
#&gt; (0 errors, 0 warnings, 1 message)
#&gt; 
#&gt; Time elapsed: 0 h 0 m 49 s</code></pre>
</div>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">power_curve</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-simr-power-curve" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-simr-power-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05a-experimental-design_files/figure-html/fig-simr-power-curve-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simr-power-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.2: Simulation-based power curve for the cardiac rehabilitation mixed model, varying the number of patients per hospital. The dashed red line marks 80% power. With a treatment effect of 5 recovery points, hospital-level SD of 3, and residual SD of 8, approximately 8 patients per hospital are needed to achieve 80% power when 10 hospitals are available. Shaded bands show 95% confidence intervals around the power estimates based on 100 simulations.
</figcaption></figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Extend along hospitals: vary number of hospitals</span></span>
<span><span class="va">fit_extended_along</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/simr/man/extend.html">extend</a></span><span class="op">(</span></span>
<span>  <span class="va">fit_pilot</span>,</span>
<span>  along <span class="op">=</span> <span class="st">"hospital"</span>,</span>
<span>  n <span class="op">=</span> <span class="fl">20</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Power curve across number of hospitals</span></span>
<span><span class="va">power_curve_hospitals</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/simr/man/powerCurve.html">powerCurve</a></span><span class="op">(</span></span>
<span>  <span class="va">fit_extended_along</span>,</span>
<span>  test   <span class="op">=</span> <span class="fu">fixed</span><span class="op">(</span><span class="st">"treatmentTreatment"</span>, method <span class="op">=</span> <span class="st">"t"</span><span class="op">)</span>,</span>
<span>  along  <span class="op">=</span> <span class="st">"hospital"</span>,</span>
<span>  breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">6</span>, <span class="fl">8</span>, <span class="fl">10</span>, <span class="fl">15</span>, <span class="fl">20</span><span class="op">)</span>,</span>
<span>  nsim   <span class="op">=</span> <span class="fl">100</span>,</span>
<span>  progress <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">power_curve_hospitals</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Power for predictor 'treatmentTreatment', (95% confidence interval),
#&gt; by number of levels in hospital:
#&gt;       5: 59.00% (48.71, 68.74) - 52 rows
#&gt;       6: 66.00% (55.85, 75.18) - 60 rows
#&gt;       8: 79.00% (69.71, 86.51) - 81 rows
#&gt;      10: 87.00% (78.80, 92.89) - 97 rows
#&gt;      15: 96.00% (90.07, 98.90) - 148 rows
#&gt;      20: 99.00% (94.55, 99.97) - 200 rows
#&gt; 
#&gt; (0 errors, 0 warnings, 6 messages)
#&gt; 
#&gt; Time elapsed: 0 h 0 m 42 s</code></pre>
</div>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">power_curve_hospitals</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-simr-power-hospitals" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-simr-power-hospitals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05a-experimental-design_files/figure-html/fig-simr-power-hospitals-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simr-power-hospitals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.3: Simulation-based power curve for the cardiac rehabilitation mixed model, varying the number of hospitals. The dashed red line marks 80% power. Approximately 8-10 hospitals are needed to achieve 80% power with 10 patients per hospital and a treatment effect of 5 recovery points. Shaded bands show 95% confidence intervals around the power estimates based on 100 simulations.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="reading-the-output" class="level3" data-number="12.4.6"><h3 data-number="12.4.6" class="anchored" data-anchor-id="reading-the-output">
<span class="header-section-number">12.4.6</span> Reading the Output</h3>
<p>The two power curves tell a clear and instructive story about how replication at different levels of the hierarchy contributes to power.</p>
<p><strong>Varying the number of hospitals</strong> (the higher-level unit): power climbs from 59% with 5 hospitals to 79% with 8 hospitals, crossing the 80% threshold between 8 and 10 hospitals. At 10 hospitals the power reaches 87% (95% CI: <span class="math inline">\([79, 93]\)</span>), and at 15 hospitals it is 96%. To achieve 80% power for a treatment effect of 5 recovery points with 10 patients per hospital, the study needs approximately <strong>8-10 hospitals</strong>.</p>
<p><strong>Varying the number of patients per hospital</strong> (the lower-level unit): power is already 77% at 5 patients per hospital and reaches 92% at 8 patients, crossing the 80% threshold between 5 and 8 patients. At 10 patients per hospital it reaches 95%, and at 15 patients it is essentially 100%.</p>
<p>At first glance, adding patients per hospital appears more efficient than adding hospitals, 8 patients per hospital gives 92% power, while 8 hospitals with 10 patients each gives only 79%. But this comparison is misleading, because the two curves are asking different questions with different total sample sizes. At 8 hospitals with 10 patients each, the total sample is 80 patients. At 10 hospitals with 8 patients each, the total is also 80 patients. The within-hospital curve reaches higher power at the same total <span class="math inline">\(N\)</span> because adding patients within hospitals reduces the residual variance more efficiently when the hospital-level variance is already accounted for as a random effect.</p>
<p>The deeper point is that <strong>both dimensions of replication matter, but for different reasons.</strong> The number of hospitals determines the degrees of freedom for the treatment test, treatment is tested against between-hospital variation, and more hospitals means more information about that variation. The number of patients per hospital determines the precision of each hospital’s mean estimate. For this particular variance structure (hospital SD = 3, residual SD = 8), the residual variation is larger than the hospital-level variation, so adding patients within hospitals is the more efficient investment per additional observation. In a study where hospital-level variation dominated, the opposite would be true.</p>
</section><section id="a-note-on-method-t-vs-method-kr-in-powersim" class="level3" data-number="12.4.7"><h3 data-number="12.4.7" class="anchored" data-anchor-id="a-note-on-method-t-vs-method-kr-in-powersim">
<span class="header-section-number">12.4.7</span> A Note on <code>method = "t"</code> vs <code>method = "kr"</code> in <code>powerSim</code>
</h3>
<p>Students familiar with Chapter <a href="04b-mixed-effects.html" class="quarto-xref"><span>9</span></a> will notice that we used <code>method = "t"</code> (Satterthwaite approximation) in the <code>powerSim</code> call rather than <code>method = "kr"</code> (Kenward-Roger), which was recommended for small numbers of groups in Chapter <a href="04b-mixed-effects.html" class="quarto-xref"><span>9</span></a>. The reason is practical rather than principled.</p>
<p><code>simr</code> works by repeatedly simulating new response data from the fitted model, refitting the model to each simulated dataset, and extracting a test result. The Kenward-Roger method via <code>pbkrtest</code> involves a more complex internal model comparison that can conflict with the way <code>simr</code> handles model refitting, specifically, it attempts to drop terms from the model in a way that fails when <code>simr</code> has modified the model structure for simulation purposes. This produces the “scope is not a subset of term labels” error.</p>
<p>The Satterthwaite method (<code>method = "t"</code>) works directly on the summary output of the refitted model and does not attempt any internal model comparison, making it compatible with <code>simr</code>’s simulation loop.</p>
<p><strong>For power analysis purposes, the difference between Satterthwaite and Kenward-Roger is small and does not materially affect the sample size recommendation</strong>. Both methods give conservative tests relative to the naive z-test, and for the sample sizes relevant to power analysis where you are asking whether a study is large enough, the distinction is negligible. The Kenward-Roger correction matters most when reporting the final analysis of a completed study with a small number of groups; at that stage, use <code>anova(fit, ddf = "Kenward-Roger")</code> as recommended in Chapter <a href="04b-mixed-effects.html" class="quarto-xref"><span>9</span></a>. For the prospective power calculation, Satterthwaite is an entirely acceptable and stable choice.</p>
</section><section id="the-key-advantage-over-analytical-power-formulas" class="level3" data-number="12.4.8"><h3 data-number="12.4.8" class="anchored" data-anchor-id="the-key-advantage-over-analytical-power-formulas">
<span class="header-section-number">12.4.8</span> The Key Advantage Over Analytical Power Formulas</h3>
<p>The <code>simr</code> approach has three advantages that matter for complex designs:</p>
<ol type="1">
<li><p><strong>It respects the actual model structure.</strong> The power calculation uses the estimated variance components, the hospital-level variance and the residual variance, from the fitted model directly, rather than requiring you to specify them separately as inputs to a formula. If your pilot data suggest that hospital-level variation is large, the power estimate will reflect this automatically.</p></li>
<li><p><strong>It can test any effect in any model.</strong> <code><a href="https://rdrr.io/pkg/simr/man/powerSim.html">powerSim()</a></code> works for any fixed effect in any model that <code>lme4</code> can fit, crossed random effects, random slopes, interaction terms, and GLMMs via <code>glmer</code>. There is no analytical formula for the power of an interaction term in a three-level nested GLMM; <code>simr</code> handles it without modification.</p></li>
<li><p><strong>It separates two design decisions.</strong> <code><a href="https://rdrr.io/pkg/simr/man/extend.html">extend()</a></code> can vary the number of higher-level units (hospitals) or the number of lower-level units (patients per hospital) independently, allowing you to ask which dimension of replication is more valuable for a given budget. In hierarchical designs, adding higher-level units (more hospitals) almost always increases power more efficiently than adding lower-level units (more patients per hospital), because the treatment is tested against between-hospital variation, not between-patient variation. <code><a href="https://rdrr.io/pkg/simr/man/powerCurve.html">powerCurve()</a></code> with both <code>along</code> and <code>within</code> makes this trade-off visible.</p></li>
</ol></section><section id="practical-recommendations-for-using-simr" class="level3" data-number="12.4.9"><h3 data-number="12.4.9" class="anchored" data-anchor-id="practical-recommendations-for-using-simr">
<span class="header-section-number">12.4.9</span> Practical Recommendations for Using <code>simr</code>
</h3>
<p>Use <code>nsim = 100</code> during exploration to find the approximate sample size quickly, then rerun with <code>nsim = 500</code> or <code>nsim = 1000</code> for the final estimate reported in a grant application or pre-registration. The confidence interval on the power estimate narrows as <span class="math inline">\(1/\sqrt{n_{\text{sim}}}\)</span>, so quadrupling the simulations halves the uncertainty.</p>
<p>Always check that the model used for power analysis matches the model you intend to fit, the same random effects structure, the same link function for GLMMs, and the same degrees of freedom method. A power analysis conducted for a Satterthwaite model but reported as a Kenward-Roger analysis will give slightly different results.</p>
</section><section id="reporting-the-power-analysis" class="level3" data-number="12.4.10"><h3 data-number="12.4.10" class="anchored" data-anchor-id="reporting-the-power-analysis">
<span class="header-section-number">12.4.10</span> Reporting the Power Analysis</h3>
<p>Power analyses should be reported in the Methods section of a paper, before the Results, under a dedicated subsection. The report must contain enough information for a reader to verify the calculation and assess whether the study was adequately powered. Here is a template based on the results above:</p>
<blockquote class="blockquote">
<p><strong>Sample size and power.</strong> Sample size was determined using simulation-based power analysis conducted with the <code>simr</code> package version x.x.x <span class="citation" data-cites="Green2016">(<a href="references.html#ref-Green2016" role="doc-biblioref">Green and MacLeod 2016</a>)</span> in R version x.x.x (R Core Team, 2026). The intended analysis was a linear mixed-effects model with treatment (control vs intervention) as a fixed effect and a random intercept for hospital, fitted using <code>lme4</code> <span class="citation" data-cites="Bates2015">(<a href="references.html#ref-Bates2015" role="doc-biblioref">Bates et al. 2015</a>)</span>. Power was estimated for a minimum clinically meaningful treatment effect of 5 recovery points, based on a between-hospital standard deviation of 3 points and a residual standard deviation of 8 points derived from a preliminary survey of the literature. The Satterthwaite t-test was used for all power simulations. Power was estimated across a range of sample sizes using 100 simulations per design point; final estimates were confirmed with 500 simulations.</p>
<p>Power analysis indicated that 10 hospitals with 10 patients per hospital (total <span class="math inline">\(N = 100\)</span>) would provide 87% power (95% simulation CI: <span class="math inline">\([79, 93]\)</span>%) to detect a treatment effect of 5 recovery points at <span class="math inline">\(\alpha = 0.05\)</span>. To allow for an anticipated dropout rate of 10%, we planned to recruit 12 patients per hospital, giving a target total of <span class="math inline">\(N = 120\)</span> patients across 10 hospitals.</p>
</blockquote>
</section><section id="what-must-be-included" class="level3" data-number="12.4.11"><h3 data-number="12.4.11" class="anchored" data-anchor-id="what-must-be-included">
<span class="header-section-number">12.4.11</span> What Must Be Included</h3>
<p>Every power analysis report must contain the following elements. Missing any of them makes the analysis unverifiable:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header">
<th>Element</th>
<th>Example</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Software and version</td>
<td>
<code>simr</code> version 1.0.7, R 4.4.0</td>
</tr>
<tr class="even">
<td>Intended statistical model</td>
<td>Linear mixed model with random intercept for hospital</td>
</tr>
<tr class="odd">
<td>Effect size and its justification</td>
<td>5 recovery points; minimum clinically meaningful difference</td>
</tr>
<tr class="even">
<td>Variance components</td>
<td>Between-hospital SD = 3, residual SD = 8</td>
</tr>
<tr class="odd">
<td>Significance threshold</td>
<td><span class="math inline">\(\alpha = 0.05\)</span></td>
</tr>
<tr class="even">
<td>Target power</td>
<td>80% (or 90% for clinical confirmatory trials)</td>
</tr>
<tr class="odd">
<td>Number of simulations</td>
<td>100 exploratory, 500 confirmatory</td>
</tr>
<tr class="even">
<td>Final sample size chosen</td>
<td>10 hospitals <span class="math inline">\(\times\)</span> 12 patients = 120</td>
</tr>
<tr class="odd">
<td>Attrition adjustment</td>
<td>10% over-recruitment</td>
</tr>
</tbody>
</table></section><section id="a-common-mistake-reporting-post-hoc-power" class="level3" data-number="12.4.12"><h3 data-number="12.4.12" class="anchored" data-anchor-id="a-common-mistake-reporting-post-hoc-power">
<span class="header-section-number">12.4.12</span> A Common Mistake: Reporting Post Hoc Power</h3>
<p>A frequent error in published papers is to report power <em>after</em> the analysis, computing the power the study had to detect the observed effect. This is called <strong>post hoc power</strong> or <strong>observed power</strong>, and it is uninformative. When a result is significant, the post hoc power will always be high; when it is non-significant, the post hoc power will always be low. The calculation adds nothing to what the p-value already tells you and should not be reported.</p>
<p>If a study yields a non-significant result and you want to assess whether a meaningful effect might have been missed, the correct tool is a <strong>confidence interval around the effect size</strong>, not a post hoc power calculation. A wide confidence interval that includes both zero and a clinically meaningful effect tells you directly that the study was underpowered for the question of interest, and it does so honestly, without the circular logic of post hoc power.</p>
</section><section id="specifying-the-effect-size-honestly" class="level3" data-number="12.4.13"><h3 data-number="12.4.13" class="anchored" data-anchor-id="specifying-the-effect-size-honestly">
<span class="header-section-number">12.4.13</span> Specifying the Effect Size Honestly</h3>
<p>The hardest part of power analysis is specifying the effect size. Three approaches are available, in order of preference:</p>
<p><strong>From prior literature.</strong> Previous studies with the same response variable and similar treatments provide effect size estimates. Apply conservatism, published effect sizes are inflated by publication bias. Use the lower bound of a confidence interval around the published effect rather than the point estimate.</p>
<p><strong>From a pilot study.</strong> A small preliminary experiment provides an estimate of the within-group variance (the denominator of the effect size) grounded in your specific biological system. With fewer than 10 units per group, the variance estimate will be imprecise, but it is more honest than a guess.</p>
<p><strong>From the minimum biologically meaningful effect.</strong> Ask: what is the smallest difference that would be scientifically or practically important? A drug that reduces tumour size by 1mm may be statistically detectable but clinically irrelevant. Power the study to detect the smallest effect that would change a decision or conclusion, not the smallest effect that exists.</p>
<p>Using Cohen’s conventional benchmarks (small = 0.2, medium = 0.5, large = 0.8 for Cohen’s d) as a substitute for genuine subject matter knowledge is the least defensible approach. Conventions calibrated on social psychology experiments from the 1960s have no particular relevance to the effect sizes typical in your biological system.</p>
</section><section id="the-multiple-testing-problem-in-design" class="level3" data-number="12.4.14"><h3 data-number="12.4.14" class="anchored" data-anchor-id="the-multiple-testing-problem-in-design">
<span class="header-section-number">12.4.14</span> The Multiple Testing Problem in Design</h3>
<p>If your experiment involves multiple primary outcomes or multiple pairwise comparisons, the power analysis must account for the multiple testing correction that will be applied at the analysis stage. Adjusting p-values downward (via Bonferroni, Holm, or Tukey) reduces the effective alpha for each test and therefore reduces power. The sample size calculation must use the corrected alpha, not the nominal 0.05.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/heliosdrm/pwr">pwr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Power for one-way ANOVA with 4 groups (6 pairwise comparisons)</span></span>
<span><span class="co"># Using Bonferroni-corrected alpha for pairwise tests</span></span>
<span><span class="va">alpha_corrected</span> <span class="op">&lt;-</span> <span class="fl">0.05</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/Special.html">choose</a></span><span class="op">(</span><span class="fl">4</span>, <span class="fl">2</span><span class="op">)</span>   <span class="co"># 0.05 / 6</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Bonferroni-corrected alpha:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">alpha_corrected</span>, <span class="fl">4</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Bonferroni-corrected alpha: 0.0083</code></pre>
</div>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Sample size needed per group with correction</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.t.test.html">pwr.t.test</a></span><span class="op">(</span>d <span class="op">=</span> <span class="fl">0.5</span>,</span>
<span>           sig.level <span class="op">=</span> <span class="va">alpha_corrected</span>,</span>
<span>           power <span class="op">=</span> <span class="fl">0.80</span>,</span>
<span>           type <span class="op">=</span> <span class="st">"two.sample"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt;      Two-sample t test power calculation 
#&gt; 
#&gt;               n = 98.62942
#&gt;               d = 0.5
#&gt;       sig.level = 0.008333333
#&gt;           power = 0.8
#&gt;     alternative = two.sided
#&gt; 
#&gt; NOTE: n is number in *each* group</code></pre>
</div>
</div>
<p>The corrected alpha requires substantially larger samples than the nominal 0.05 would suggest, a direct consequence of the multiple testing overhead that is easy to overlook at the design stage and costly to discover at the analysis stage.</p>
</section><section id="a-design-checklist" class="level3" data-number="12.4.15"><h3 data-number="12.4.15" class="anchored" data-anchor-id="a-design-checklist">
<span class="header-section-number">12.4.15</span> A Design Checklist</h3>
<p>Before finalising any experimental design, work through the following questions:</p>
<p><strong>Randomisation:</strong></p>
<ul>
<li><p>Is every experimental unit randomly assigned to a treatment?</p></li>
<li><p>Is the randomisation documented and reproducible?</p></li>
<li><p>Are any known confounders balanced across treatment groups?</p></li>
</ul>
<p><strong>Replication:</strong></p>
<ul>
<li><p>What is the experimental unit i.e.&nbsp;the entity that received the treatment independently?</p></li>
<li><p>How many independent replicates are there per treatment at the level of the experimental unit?</p></li>
<li><p>Is this number justified by a power analysis?</p></li>
</ul>
<p><strong>Blocking:</strong> - Are there known sources of nuisance variation?</p>
<ul>
<li><p>Can they be controlled by blocking before randomisation?</p></li>
<li><p>Is the block factor included in the intended analysis?</p></li>
</ul>
<p><strong>Analysis:</strong> - Is the intended model formula written down?</p>
<ul>
<li><p>Does it match the design, specifically the randomisation structure and the hierarchy of units?</p></li>
<li><p>Has the power been calculated for the primary comparison using the intended analysis?</p></li>
</ul>
<p><strong>Practical:</strong> - Is the expected attrition rate accounted for in the sample size?</p>
<ul>
<li><p>Is the response variable sensitive and precise enough to detect the effect of interest?</p></li>
<li><p>Are all measurements taken blind to treatment allocation where possible?</p></li>
</ul>
<p>A design that passes all of these checks will not guarantee a significant result, nothing can do that, but it will guarantee that whatever result emerges is worth trusting.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Going Further
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p><strong>Cox, D. R., &amp; Reid, N. (2000). The Theory of the Design of Experiments. CRC Press.</strong> The theoretical foundation for readers who want to understand randomisation theory, optimality criteria, and the mathematical basis for why blocking works. Not light reading, but authoritative.</p></li>
<li><p><strong>Quinn, G. P., &amp; Keough, M. J. (2002). Experimental Design and Data Analysis for Biologists. Cambridge University Press.</strong> A comprehensive experimental design reference specifically written for biologists. Covers randomisation, blocking, factorial designs, and split-plot in much greater depth.</p></li>
<li><p><strong>Mead, R., Gilmour, S. G., &amp; Mead, A. (2012). Statistical Principles for the Design of Experiments. Cambridge University Press.</strong> Specifically focused on the principles rather than the computations. It adress why designs work, what makes a good design, how to choose among alternatives.</p></li>
<li><p><strong>Lawson, J. (2014). Design and Analysis of Experiments with R. CRC Press.</strong> The most directly R-oriented design textbook available. Every design in this book. A natural companion for students.</p></li>
<li><p><strong>Montgomery, D. C. (2017). Design and Analysis of Experiments (9th ed.). Wiley.</strong> The engineering-oriented classic that covers every design mentioned in this book and many more. The book is Heavier on mathematics than Quinn &amp; Keough but authoritative and thorough.</p></li>
</ul>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Bates2015" class="csl-entry" role="listitem">
Bates, Douglas, Martin Mächler, Ben Bolker, and Steve Walker. 2015. <span>“Fitting <span>Linear Mixed-Effects Models Using</span> Lme4.”</span> <em>Journal of Statistical Software</em> 67 (October): 1–48. <a href="https://doi.org/10.18637/jss.v067.i01">https://doi.org/10.18637/jss.v067.i01</a>.
</div>
<div id="ref-Green2016" class="csl-entry" role="listitem">
Green, Peter, and Catriona J. MacLeod. 2016. <span>“<span>SIMR</span>: An <span>R</span> Package for Power Analysis of Generalized Linear Mixed Models by Simulation.”</span> <em>Methods in Ecology and Evolution</em> 7 (4): 493–98. <a href="https://doi.org/10.1111/2041-210X.12504">https://doi.org/10.1111/2041-210X.12504</a>.
</div>
</div>
</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ebedthan\.github\.io\/maov\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./05-good-practice.html" class="pagination-link" aria-label="Good Practice and Reproductibility">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Good Practice and Reproductibility</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05b-reporting.html" class="pagination-link" aria-label="Reporting ANOVA Results">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Reporting ANOVA Results</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Modern Analysis of Variance by Anicet Ebou.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Ebedthan/maov/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li><li><a href="https://github.com/Ebedthan/maov/edit/main/05a-experimental-design.qmd" class="toc-action"><i class="bi empty"></i>Edit this page</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>